kubev2v/forklift

pkg/controller/plan/kubevirt.go, pkg/controller/plan/kubevirt_test.go, pkg/controller/plan/validation.go, validation/policies/io/konveyor/forklift/ovirt/name.rego, validation/policies/io/konveyor/forklift/vmware/name.rego
This PR changes VM names to match the DNS1123 RFC conventions,
As a first step, the names will be automatically adjusted to make the VMs ready for migration without user actions.
A newly generated name will be created and validated with the destination, if exists, will add the first 4 chars from the ID to the new name to avoid dups.
A new annotation with the previous name and ID will be added to the imported VM.
Currently, implementation checks the following:
contain at most 63 characters
contain only lowercase alphanumeric characters or '-'
start with an alphanumeric character
end with an alphanumeric character
In case the VM name is completely deleted after the adjustments a new name in the format vm-$ID will be given.
https://bugzilla.redhat.com/show_bug.cgi?id=1959883
=> Change VM names comply with RFC 1123 DNS Subdomain

pkg/controller/plan/adapter/ovirt/BUILD.bazel, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/provider/BUILD.bazel, pkg/controller/provider/container/ovirt/resource.go, pkg/controller/provider/model/ovirt/model.go, pkg/controller/provider/web/ovirt/vm.go, validation/policies/io/konveyor/forklift/ovirt/cpu_policy.rego, validation/policies/io/konveyor/forklift/ovirt/cpu_policy_test.rego
When importing a VM from oVirt it has the property of CPU Pinning Policy.
Only having none or dedicated is supported on CNV. Therefore, only both
of them will be respected.
As for dedicated the user should enable the CPU manager on the nodes,
or else the VM won't be able to schedule and the migration will hang.
NUMA is out of the scope for this PR.
More about the feature at the [dedicated cpu resources page](https://kubevirt.io/user-guide/virtual_machines/dedicated_cpu_resources/).
=> Support ovirt CPU Policy

pkg/controller/plan/kubevirt_test.go
changing the VM test name to match the final auto-generated name convention.
=> Fix unit test for vm name change

pkg/controller/host/validation.go
Migration of: https://github.com/konveyor/forklift-controller/pull/445
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1958826
Issue:
When selecting the migration network on the VMware host and entering the wrong credentials the thrown error is unclear.
=> migrate host validation: change vmware fail error msg

WORKSPACE
Previously we used the digest of v1.22 which got changed with every new release of 1.22.Z. Now we will use the v1.22.0 which hopefully will no longer be overwritten.
=> Fix digest ansible-operator-image

operator/config/crd/bases/forklift.konveyor.io_providers.yaml, pkg/apis/forklift/v1beta1/provider.go, pkg/controller/provider/controller.go, pkg/controller/provider/validation.go
Add phase status to Ptoviders CRD.
K8S resources uses `status.phase` fields to help users follow the resources life cycle from creation to deletion.
the `phase` helps users to easily catch resource that stray into sad paths or get stuck.
`phase`s do not replace `conditions`, `conditions` role is to report the state of the resource while `phase` report the place of the resource during it's life voyage.
Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
Issue:
The UI want to show the resource stage in it's life cycle as a way to help users easily glance the happiness of there cluster. Currently providers only report it's `conditions`, and require the users to guess the stage of the providers using this conditions.
Proposed solution:
Add `phase` field to the providers …
=> Add phase status

pkg/controller/plan/kubevirt.go
With the new [CDI change](https://github.com/kubevirt/containerized-data-importer/pull/2421), the data volumes being deleted when the import completes. However, the controller lookup for the data volumes in order to know when the disk transfer is complete and continue with the migration flow. In order to prevent it, an annotation is added to the data volumes.
=> Prevent data volume deletion

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, validation/policies/io/konveyor/forklift/vmware/uefi_boot.rego
Since we can't transfer NVRAM or TPM data, it is better to have EFI VMs without secure boot.
=> Switch to EFI without secure boot

.bazelrc, README.md, operator/config/manager/manager.yaml, operator/config/manifests/bases/forklift-operator.clusterserviceversion.yaml, operator/config/rbac/role.yaml, operator/config/samples/forklift_v1beta1_forkliftcontroller.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/ui-plugin/configmap-ui-plugin.yml.j2, operator/roles/forkliftcontroller/templates/ui-plugin/console-plugin.yml.j2, operator/roles/forkliftcontroller/templates/ui-plugin/deployment-ui-plugin.yml.j2, operator/roles/forkliftcontroller/templates/ui-plugin/service-ui-plugin.yml.j2
Add forklift ui plugin from https://github.com/kubev2v/forklift-console-plugin This patch adds to the operator:
- RBAC config so the operator have permission to add the ConsolePlugin
- New parameter `feature_ui_plugin` to enable/disable the plugin installation
The UI plugin installation is made of 4 parts:
- ConfigMap with nginx configuration
- Deployment for the forklift UI plugin itself
- Service
- ConsolePlugin
Results:
=> Add UI plugin to operator

pkg/apis/forklift/v1beta1/register.go, pkg/controller/provider/web/base/auth.go
Previously, querying '/providers' by users that don't have cluster-admin
permissions failed because the request doesn't specify a UID of a
provider to query and thus, we ended up checking if the user has
permissions on all resources.
With this change, we'd always query 'providers.forklift.konveyor.io' for
'get' when a provider is specified and for 'list' otherwise. That way,
all users with ClusterRole on providers.forklift.konveyor.io can access
the data of providers from the inventory.
=> Enable non-admin users to query providers from inventory

.github/workflows/pull-request.yml, Makefile, tests/base_test.go
The test will perform a single VM migration from existing ovirt
provider.
An existing k8s cluster with forklift installed, and a storage class
are required.
To use the CI in kind using fakeovirt, the test should be executed as
is. Otherwise the user shold provided enviromental variables:
`OVIRT_CUSTOM_ENV`, set `true` if you wish to use existing ovirt
environment.
`OVIRT_USERNAME`, the username in ovirt such as `admin@internal`.
`OVIRT_PASSWORD`, the password in ovirt.
`OVIRT_URL`, the API endpoint `https://<engine-fqdn>/ovirt-engine/api`.
`OVIRT_CACERT`, the CA certificate, located locally in a file:
`/path/to/cert`.
STORAGE_CLASS, the storage class to map the disks to.
`OVIRT_VM_ID`, the VM ID in ovirt.
`MIGRATION_TIMEOUT`, set the number of minutes to the migration completion
- by …
=> E2E sanity ovirt test

WORKSPACE
This image is required for our CI virt-v2v stub container
https://github.com/kubev2v/forkliftci/pull/28
=> Add cirros image to the  WORKSPACE

pkg/controller/provider/container/ovirt/client.go, pkg/controller/provider/container/ovirt/collector.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/controller.go, pkg/controller/provider/validation.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go, pkg/lib/cmd/inventory/main.go, pkg/lib/inventory/container/container.go, pkg/lib/inventory/container/ocp/collector.go
Issue: when a user enters the correct username for the provider but an incorrect password it will try to connect multiple times to the engine. Which locks the user account.
Fix: Adding a special case of condition ConnectionAuthFailed and finishing the reconciliation.
Migrated patches from: https://github.com/konveyor/controller/pull/104 and https://github.com/kubev2v/forklift-controller/pull/447
=> Add ConnectionAuthFailed for one try auth check

Makefile, operator/config/crd/bases/forklift.konveyor.io_hooks.yaml, operator/config/crd/bases/forklift.konveyor.io_hosts.yaml, operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_networkmaps.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, operator/config/crd/bases/forklift.konveyor.io_providers.yaml, operator/config/crd/bases/forklift.konveyor.io_storagemaps.yaml
This fixes the following issue:
When running the opm to create the index from bundle, it reads the base files. A few of the base files started with empty space on top and --- right after it. Which the OPM understood as the end of an empty file.
Replaces #57
=> Update controller-gen to v0.10.0

WORKSPACE
Bazel's platform constraints, a dependency of `io_bazel_rules_docker`, were moved into separate project. With Bazel 6 the builds now fail and `io_bazel_rules_docker` need to be updated to at least v0.21.0 to work properly. Update to latest available version.
No other changes seem to be necessary.
=> build: update io_bazel_rules_docker to v0.25.0

pkg/controller/provider/web/openstack/image.go
Implement With method to have the return value properly populated.
Example
```shell
$ curl -X GET https://forklift-inventory-konveyor-forklift.apps-crc.testing/providers/openstack/a6ea4fc8-cbf1-4cc6-aab4-d8473d51120e/images --header "Authorization: Bearer $TOKEN"
[{"id":"f8c432bc-1973-4ca3-8f21-120bb202a527","revision":1,"name":"shalom-snap","selfLink":"providers/openstack/a6ea4fc8-cbf1-4cc6-aab4-d8473d51120e/images/f8c432bc-1973-4ca3-8f21-120bb202a527"},{"id":"bbe910c8-39b3-490a-ba67-d8c110fc595f","revision":1,"name":"hello-snap","selfLink":"providers/openstack/a6ea4fc8-cbf1-4cc6-aab4-d8473d51120e/images/bbe910c8-39b3-490a-ba67-d8c110fc595f"},{"id":"de078608-80c6-4115-8907-9dacbc66c7f5","revision":1,"name":"cirros","selfLink":"providers/openstack/a6ea4fc8-cbf1-4cc6-aab4-d8473d51120e/image …
```
=> openstack: fix image endpoints

pkg/controller/provider/container/openstack/client.go
Otherwise the token will expire after an hour by default and subsequent calls will fail
=> openstack: enable Reauth for gopehrcloud authentication

pkg/controller/provider/BUILD.bazel, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/validation.go
This is a preparation for future changes. Virt-v2v and libvirt cannot handle SSL certificates that it cannot verify (e.g. self-signed) and need a flag that tell it to disable checks. This does not mean we don't need the thumbprint (certificate fingerprint). Thumbprint is still needed by controller and will remain necessary for conversion pod when VDDK is used.
=> vsphere: Allow insecure connection to the server

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/kubevirt.go, pkg/settings/migration.go
we want to be able to run virt-v2v on nodes without KVM capabilities (ci)
=> making kvm device for the virt-v2v pod optional

.github/workflows/pull-request.yml
We don't generate any codecov report there so this step doesn't do anything at the moment.
=> Drop codecov-action from setup_ci job

operator/config/manager/manager.yaml
this is completion PR to  https://github.com/kubev2v/forklift/pull/36 , adding VIRT_V2V_DONT_REQUEST_KVM env to the operator, so it can be properly propagated to the controller pod.
=> add VIRT_V2V_DONT_REQUEST_KVM env to the forklift operator

Makefile
This target builds and pushes all the images that are configured in this repository.
In order to use it, one just needs to:
1. Enable access to the image registry
2. Configure the REGISTRY, REGISTRY_ACCOUNT and REGISTRY_TAG variables
=> Add push-all-images that work with Podman and Openshift/OKD

pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
This is a cleanup for #54 :
- Add debug information to logs in secret admitter
- Return proper error from secret-admitter
=> Cleanup in validation of provider secrets

Makefile
We need to push the image with our entrypoint and not just the bare virt-v2v image.
=> build: Build and push proper virt-v2v image

.github/workflows/build-push-images.yml
Issue: When the action from the main branch pushes to the quay it does not update the latest tag but only the main tag.
=> GitHub Action: Set REGISTRY_TAG 'latest' on main branch

.github/CODEOWNERS
@bennyz was not added as a reviewer of #116  - fixing the definition of openstack code owners
=> Update pattern of openstack owners

operator/config/rbac/role.yaml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/api/mutatingwebhookconfiguration-forklift-api.yml.j2, pkg/forklift-api/api.go, pkg/forklift-api/webhooks/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook.go, pkg/forklift-api/webhooks/mutating-webhook/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutating-webhook.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutators/ovirt-cert-mutator.go, pkg/forklift-api/webhooks/util/util.go, pkg/forklift-api/webhooks/validating-webhook/validating-webhook.go, pkg/forklift-api/webhooks/webhooks.go
Currently, in case users have configured ovirt engine with a 3rd party certificate when this engine will be added as a new provider in forklift with only that certificate the migration of the VMs will fail and no prior indication will be displayed when adding the provider.
This PR introduces a new mutating webhook that will automatically run for each new provider of type ovirt that will automatically retrieve the engine CA certificate if missing and post it to the existing provider secret following the 3rd party one without any action by the user.
=> Add mutating webhook to modify missing ovirt CA

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go
Instead of relying on disk source being part of DataVolume.Spec we store the source also in the annotation. This is a preliminary change that will ease our transition from CDI.
=> plan: store disk source in annotation

pkg/forklift-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutators/ovirt-cert-mutator.go
As part of the mutating webhook flow, changing the admission response to be empty instead of a response with redundant patch operation for providers type different than oVirt.
=> Returning empty reply for providers different than oVirt 

Makefile
The build targets for virt-v2v warm image and operator bundle were broken after commit a9043160.
=> build: fix virt-v2v image builds

.github/workflows/pull-request.yml, tests/suit/tests_suite_test.go
1. By default use 'kubectl', assuming it's within PATH rather than `/home/eslutsky/bin/kubectl`
2. Do not store kubeconfig in /tmp before executing the end-to-end tests, there's no need for this anymore (see https://github.com/kubev2v/forkliftci/pull/55)
=> Ease execution of forkliftci locally

.bazelrc, Makefile, README.md, WORKSPACE, operator/BUILD.bazel
- Prefer `podman` over `docker` in Makefile builds
- Make the build fully customizable through environment
variables.
- Use `CONTROLLER_GEN` var to specify which `controller-gen`
binary must be used and make sure the correct version is
installed when using the default one.
- Make consistent use of parentheses instead of curly braces
for variable delimitation.
- Add sandbox writeable paths, needed after `bazel clean`.
=> Make the Makefile build fully customizable

.bazelrc, Makefile, README.md
Previously, the version was 99.0.0 although the upcoming version is 2.4.0.
This PR also includes two more changes, in a separate commit, that I had to do in order to deploy to CRC using the `deploy-to-crc.sh` script
=> Set version to 2.4.0

pkg/controller/plan/kubevirt.go, pkg/controller/plan/kubevirt_test.go, validation/policies/io/konveyor/forklift/ovirt/name.rego, validation/policies/io/konveyor/forklift/vmware/name.rego
Follow up the automated VM name renaming feature, improving some flows:
1. [MTV-404](https://issues.redhat.com/browse/MTV-404): Fixing long name handling, in case the name exists in the system and its length is already 63 chars after adding the VM ID as a unique identifier the name will exceed the allowed length limit and the migration will fail.
2. [MTV-480](https://issues.redhat.com/browse/MTV-480): change the check scope for the already existing VM name from the cluster to the plan namespace.
3. [MTV-382](https://issues.redhat.com/browse/MTV-382): Fix VM length validation to be a maximum of 63 chars and not 64.
=> Improving automated VM rename handling

cmd/ovirt-populator/ovirt-populator.go
When calling the populator we add args, it expected to get `volume-path` but we sent `file-name`. This cause a failure to the populator container.
=> Fix the file-name to vol-name

pkg/controller/plan/migration.go
When changing the phasing of the disk transfer before the VM creation, the scheduling of the VM removed. Doing so, we didn't end up with the Initialization phase, and signal the step as completed. It caused the the phase to keep running and harmed the time counter for the upcoming phases.
This patch ends the step and fix the issue above.
=> Fix the step and phasing for initialization

WORKSPACE
The CI fails on the build/push of the virtv-v2v image with error
```
MANIFEST_UNKNOWN: manifest unknown; map[]
```
https://github.com/kubev2v/forklift/actions/runs/4072203778/jobs/7014720982
=> Bazel: Fix libguestfs-appliance digest

.github/workflows/build-push-images.yml, Makefile
This patch will push the populator image that contains both populator controller and the populator itself to quay. Later on we will split the images.
=> Push the populator image

WORKSPACE, hack/virt-v2v-stream8-rpm-deps.sh, rpm/BUILD.bazel, virt-v2v/cold/entrypoint, virt-v2v/warm/entrypoint
libguestfs in EL8 cannot use appliance in QCOW2. Use compressed tar archive for transport.
This is tied to https://github.com/kubev2v/libguestfs-appliance/pull/2 and depends on #146.
=> virt-v2v: Extract compressed tar with libguestfs appliance

.bazelrc, Makefile, README.md, hack/release-images.sh, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, virt-v2v/cold/entrypoint
This is a set of patches that modify Forklift controller and forklift-virt-v2v image to make virt-v2v do the data copying instead of CDI.
The gap we will have with this is that progress for data copying is not reported as it used to. That is still work to be done and a topic for a separate PR.
=> Let virt-v2v copy the data

.github/workflows/build-push-images.yml, Makefile, README.md, cmd/ovirt-populator/BUILD.bazel, cmd/ovirt-populator/ovirt-populator.go, cmd/populator-controller/BUILD.bazel, cmd/populator-controller/populator-controller.go, hack/ovirt-populator/Containerfile, hack/release-images.sh
This patch will split the populator image.
One image acts as a controller to the populator - 'populator-controller' and the actual populator action will be executed by the 'ovirt-populator' image.
This will allow a separation in logic, allowing to add more source providers images and use the same controller for all.
=> Split the populator image

.github/workflows/pull-request.yml, Makefile, tests/suit/openstack_test.go
when we trigger  a ci  job from the matrix,  we want specify which provider env setup is needed (openstack/ovirt/vsphere), so we will  run tests only on that provider.
- split the setup jobs across different providers
- depends on this PR https://github.com/kubev2v/forkliftci/pull/59
this PR doesn't  cover the whole ginko test suite for OSP.
=> Introduce openstack test suite to the CI

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/kubevirt.go, pkg/controller/plan/vm_name_handler.go, pkg/controller/plan/vm_name_handler_test.go
Currently, during the migration, if the VM has an invalid name and the newly generated name exists in the namespace, a name of the format `vm-vmId[0:4]` is picked as a unique identifier.
For oVirt, this solution works well, but for vmware, the vm Id is in the following format: `vm-#vm_number_counter`. Because the counter can be any number and is not sufficiently unique, attaching it to the new name can cause issues.
To address this issue, this PR introduces a tool that generates a new random string of six lowercase letters and digits.
Also, this PR separates all VM name changing flow into a new file. 
=> Introducing random suffix generator for VM name in case of an already used name.

virt-v2v/cold/BUILD.bazel, virt-v2v/cold/WORKSPACE
The rules have been extracted from Bazel and are in external repository now. Use of the original rules is deprecated.
Also, container build fails on Bazel 6.0 withe the original rules reporting error:
no such attribute 'mode' in '_real_pkg_tar' rule
=> build: Use packaging rules from external repository

cmd/ovirt-populator/ovirt-populator.go
In case we are exiting from ovirt-imgio with an error - we should end the pod with fatal error, indicating a failure in the transfer.
Until now, it just printed the error and could finish as completed even when it didn't.
=> ovirt-populator: change an error to fatal

.github/workflows/pull-request.yml
the cert path has changed  in the CI https://github.com/kubev2v/forkliftci/pull/63
=> fix for ovirt CI migration test e2e_cacert.cer changed path

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/web/base/auth.go, pkg/controller/provider/web/base/auth_test.go, pkg/controller/provider/web/ocp/provider.go, pkg/controller/provider/web/openstack/provider.go, pkg/controller/provider/web/ovirt/provider.go, pkg/controller/provider/web/vsphere/provider.go
Issue: currently the authentication code checks if user can list providers on all namespaces (or on "POD_NAMESPACE" env variable if available) but list the providers using a URL param, this may allow users to list providers the do not have permission to list.
Fix:
example of use:
``` bash
export TOKEN=[secret-token]
curl -k -H "Authorization: Bearer ${TOKEN}" http://localhost:8080/providers?namespace=forklift | jq
```
=> Authenticate requests for the currect namespace

tests/suit/openstack_test.go, tests/suit/ovirt_test.go, tests/suit/utils/networkmap.go, tests/suit/utils/plan.go, tests/suit/utils/storagemap.go, tests/suit/vsphere_test.go
The end-to-end tests were not executed properly with the changes that we done in #165 as the framework's generated namespaces are created in BeforeEach and we tried to retrieve them before that.
In addition, there's a problem with running the vSphere tests when the entities are created within the generated namespace, so we keep using the 'konveyor-forklift' namespace until this will be further investigated.
=> Fix end-to-end tests

pkg/controller/provider/container/openstack/collector.go, pkg/controller/provider/container/openstack/model.go
Currently we save the time where the last sync has been
successful for all the objects.
If any object is updated in that sync interval it's possible
to loose updates.
The proposed changes try to fix this issue.
=> Fix race condition on inventory synchronization

pkg/controller/plan/kubevirt.go
When passing on the storage profile it can have multiple accessmodes and multiple volume modes. We prefer the block volume mode and set the access modes accordingly.
=> Fix the access modes of the PVC

operator/config/crd/bases/forklift.konveyor.io_openstackvolumepopulators.yaml, operator/config/crd/bases/forklift.konveyor.io_ovirtvolumepopulators.yaml
For OpenStack the names are: osvp, osvps.
For oVirt the bames are: ovvp, ovvps.
The ease querying the populator CRs from the CLI a bit.
=> Short names for OpenStack/oVirt volume populators

operator/roles/forkliftcontroller/defaults/main.yml
Previously the 'feature_ui_plugin' var wasn't set with a default value
and thus triggered the following error when it wasn't define in
ForkliftController:
The conditional check 'feature_ui_plugin|bool and not k8s_cluster|bool'
failed. The error was: error while evaluating conditional
(feature_ui_plugin|bool and not k8s_cluster|bool): 'feature_ui_plugin'
is undefined
Now this variable is defined and set to 'true' in order to deploy the
console plugin by default.
=> Enable UI plugin by default

cmd/openstack-populator/openstack-populator.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/provider/container/openstack/client.go
Rename insecure secret key to insecureSkipVerify in openstack to macth the secret key in vmware and ovirt
Issue:
Currently we use `insecureSkipVerify` secret key in oVirt and vmWare secrets, and `insecure` in openstack provider
Fix:
Align the openstack secret key with ovirt and vmWare
=> Rename insecure secret key to insecureSkipVerify in openstack

pkg/controller/plan/kubevirt.go
When migrating using the populator, a secret is required. It differs in the data and name compared to DataVolumes. The secret is required in the target namespace. This patch ensure the secret will be there with the relevant data and name.
=> Create the relevant secret for populator

pkg/controller/plan/kubevirt.go
When we don't require KVM, we shouldn't filter hosts that have kubevirt.io/schedulable=true
=> Do not set 'kubevirt.io/schedulable' when VirtV2vDontRequestKVM is set

tests/suit/vsphere_test.go
With CDI 1.56.0, the vSphere test fails with the 'standard' storage class. While we need to investigate this, it seems like the right time to align with ovirt's and openstack's tests, and use nfs-csi also in the vsphere test.
=> Use nfs-csi in vSphere test

pkg/lib-volume-populator/populator-machinery/controller.go
Having the SeccompProfile set to runtime caused an issue starting the pod with the error:
`
E0308 21:59:06.167954 1 controller.go:418] error syncing 'pvc/arik/2d096ab7-44fa-4935-b0d0-333532e84e5f': pods "populate-f4436d1b-2075-4a51-b6a1-3b1d72e29cde" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations[[container.seccomp.security.alpha.kubernetes.io/populate](http://container.seccomp.security.alpha.kubernetes.io/populate)]: Forbidden: seccomp may not be set, provider "containerized-data-importer": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{107}: 107 is not an allowed group, spec.containers[0].securityContext.runAsUser: Invalid value: 107: must be in the …
=> Drop SeccompProfile from populator pod

pkg/controller/plan/context/migration.go
We should use virt-v2v on el9 only on cold-migration from vsphere to the same cluster that forklift runs on.
=> Fix UseEl9VirtV2v

operator/config/manager/manager.yaml, pkg/controller/plan/kubevirt.go
1. Fix seg fault in `guestConversionPod`
2. Add missing VIRT_V2V_WARM_IMAGE env var to CSV
=> Fix imports using virt-v2v to remote clusters

cmd/virt-v2v-monitor/BUILD.bazel, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, tests/suit/framework/BUILD.bazel, virt-v2v/cold/BUILD.bazel
When having a storage class with `WaitForConsumer` the disk transfer won't start until the PVC had a consumer and it has the annotation `volume.kubernetes.io/selected-node`. For that, we will create a simple pod associated with the PVC to let kubernetes schedule it - making a consumer to the PVC.
When executed by the volume populator, the PV won't create, letting the volume populator to be executed. As for vSphere, the data is overriden when transferred.
The pod will remain on destination namespace. Once the plan is archived it will be cleaned up.
=> Create a consumer to PVC

operator/config/crd/bases/forklift.konveyor.io_openstackvolumepopulators.yaml, operator/config/crd/bases/forklift.konveyor.io_ovirtvolumepopulators.yaml, pkg/apis/forklift/v1beta1/openstackpopulator.go, pkg/apis/forklift/v1beta1/ovirtpopulator.go
1. Add 'optional' comments to the status properties of OpenstackVolumePopulator
2. Add 'shortNames' as comments for OpenstackVolumePopulator and OvirtVolumePopulator
And updated the manifets with `make manifests`
=> Fix generation of manifests for populator CRDs

operator/config/crd/bases/forklift.konveyor.io_openstackvolumepopulators.yaml, operator/config/crd/bases/forklift.konveyor.io_ovirtvolumepopulators.yaml, pkg/apis/forklift/v1beta1/openstackpopulator.go, pkg/apis/forklift/v1beta1/ovirtpopulator.go
1. Add 'optional' comments to the status properties of OpenstackVolumePopulator
2. Add 'shortNames' as comments for OpenstackVolumePopulator and OvirtVolumePopulator
=> Fix generation of manifests for populator CRDs (backport)

pkg/controller/plan/kubevirt.go
We previously named all volumes within the pod we start for binding the PVCs with the same name, "init". Now, each volume is named after the PVC it is expected to bind. The container is now named "main" rather than "init" - init is a bit misleading as it might suggest we refer to an init-container.
=> Fix import of multi-volume VMs from vSphere (backport)

pkg/controller/plan/kubevirt.go
Having `RunAsNonRoot` requires to specify the user the container is intended to run with.
=> Fix PVC consumer pod security

pkg/controller/plan/kubevirt.go
Having `RunAsNonRoot` requires to specify the user the container is intended to run with.
=> Fix PVC consumer pod security (backport)

virt-v2v/cold/entrypoint
This is useful for downstream builds and may become also necessary for upstream soon since we plan to abandon the pre-built Kubevirt appliance.
=> virt-v2v: cold: extract the appliance if it is stored in compressed tar

pkg/controller/plan/kubevirt.go
We may benefit from the image we chose for the consumer pod. This patch adds a comment about it.
Fixes https://github.com/kubev2v/forklift/issues/219
=> Add a comment about the consumer image

cmd/ovirt-populator/ovirt-populator.go
Setting `insecureSkipVerify` to be false in the populator in case its not set in the secret.
=> Fix default setting for insecureSkipVerify

operator/roles/forkliftcontroller/tasks/main.yml
Issue:
```
TASK [Set console_plugins variable] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'plugins'\n\nThe error appears to be in '/opt/ansible/roles/forkliftcontroller/tasks/main.yml': line 264, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n - name: \"Set console_plugins variable\"\n ^ here\n"}
```
Fix:
Set `console_plugins` as an empty list in case there are no other plugins
=> operator: Fix console_plugins list in case there are no other plugins

pkg/controller/plan/adapter/ovirt/builder.go
When running an import with CDI, the PVC is not named based on the source input. In that case we need to use the generated name of the PVC to be claimed by the VM. This relevant for non volume populator imports such as warm imports and imports to remote clusters.
=> Attach the right PVC in different flows

cmd/ovirt-populator/ovirt-populator.go
Backport [insecure fix for default value]( https://github.com/kubev2v/forklift/pull/243) for 2.4 release.
=> Fix default setting for insecureSkipVerify (backport)

pkg/controller/plan/kubevirt.go
In order to have the PVC bind with a host with KVM, which is required by the conversion pod. The consumer need to run on a node that has KVM enabled as well.
=> Require KVM to the PVC consumer pod (backport)

pkg/controller/plan/kubevirt.go
Having the consumer container and the v2v conversion container with the KVM device as required caused:
`spec.containers[0].resources.limits: Required value: Limit must be set for non overcommitable resources`. This patch switch it back to be as Limit of the container as it was before.
Fixes #263
=> Switch the KVM resource to limits

pkg/controller/plan/kubevirt.go
Having the consumer container and the v2v conversion container with the KVM device as required caused:
`spec.containers[0].resources.limits: Required value: Limit must be set for non overcommitable resources`. This patch switch it to be as Limit and Request of the container.
=> Switch the KVM resource to limits (backport)

cmd/openstack-populator/openstack-populator.go, pkg/controller/provider/container/openstack/model.go, pkg/controller/provider/container/openstack/resource.go
Request changes since using the time in the controller may be an issue if there is a time difference between openstack and openshift.
Instead, where possible, this patch attempts to use the time from resource's updated_at field as the value for changes-since.
=> openstack: use openstack time instead of openshift time

pkg/controller/plan/kubevirt.go
To avoid including oVirt PVCs, we need to make sure we look only at PVCs relevant for the current migration
=> openstack: check the migration label value

pkg/controller/plan/kubevirt.go
To avoid including oVirt PVCs, we need to make sure we look only at PVCs relevant for the current migration
=> backport: openstack: check the migration label value

pkg/controller/plan/kubevirt.go
When executing warm migration from ovirt to a storage class with binding mode `WaitForFirstConsumer` the importer pod won't start until the PVC is bound.
An annotation is added to the DataVolume (passing to the PVC), telling CDI to start immediate without bounding.
=> Bind PVC with WaitForFirstConsumer storage classes when CDI imports

pkg/controller/plan/adapter/vsphere/builder.go
While virt-v2v should copy the data only for cold-migrations to the host cluster.
=> CDI should copy disks from vSphere to remove clusters

pkg/controller/plan/kubevirt.go
When executing warm migration to a storage class with binding mode `WaitForFirstConsumer` the importer pod won't start until the PVC is bound. This may happen on warm migrations and migrations with a remote destination.
An annotation is added to the DataVolume (passing to the PVC), telling CDI to start immediate without bounding.
=> Bind PVC with WaitForFirstConsumer storage classes when CDI imports (backport)

pkg/controller/plan/adapter/openstack/builder.go
Currently the graphics device is disabled by default
for the migrated VM unless the "hw_video_model" property
is set to "none" in the image. This logic is wrong
and it's exactly the opposite of the desired behavior.
=> openstack: fix graphics device mapping

virt-v2v/cold/entrypoint
Separate the VM name from rest of the arguments with `--`. Thus make sure the name is not confused for argument if it starts with dash.
=> virt-v2v: make sure VM name is not confused for argument

pkg/controller/plan/adapter/openstack/builder.go
- openstack: Add missing virtual hardware constants
- openstack: Map unsupported "vmxnet3" interface
=> openstack add missing constants

pkg/controller/plan/kubevirt.go
Replace the Update method with Patch for setting ownerReferences on PVCs to avoid potential failures due to resource version conflicts which may happen because the volume populator controller removes the finalizer after the PVC is marked as Bound.
=> Use patch instead of update to set PVC owner references

pkg/controller/plan/adapter/openstack/builder.go
Add all the missing OpenStack VIF models and map
them to the supported values in OpenShift. Fallback
to `virtio` if the model is not supported by OpenShift
Fixes #304
=> openstack: map all the OpenStack VIF models

operator/config/manager/manager.yaml, operator/config/prometheus/monitor.yaml, operator/config/rbac/authproxy/service.yaml, operator/roles/forkliftcontroller/templates/controller/configmap-controller.yml.j2, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, operator/roles/forkliftcontroller/templates/controller/route-inventory.yml.j2, operator/roles/forkliftcontroller/templates/controller/service-inventory.yml.j2
Issue: The control-plane field is immutable so once the operator tried to deploy the 2.4 it failed.
Fixes: https://github.com/kubev2v/forklift/issues/314
=> Operator: Use original control-plane name

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
Currently the BeforeTransferHook waits for all images to be ready before creating the PVCs. However, some images will be slower than other to create, so instead we create the PVC as soon as the image is ready to save some time.
=> openstack: parallelize creation of PVCs

.bazelrc, hack/virt-v2v-cold-rpm-deps.sh, virt-v2v/cold/.bazerlc, virt-v2v/cold/BUILD.bazel, virt-v2v/cold/WORKSPACE
The appliance from Kubevirt [1] is missing some packages we need. For legal
reasons it is not possible to include the missing packages there. We need to
build our own fixed appliance.
We imitate multi-stage Dockerfile build in Bazel. Unfortunately
container_run_and_extract() does not work with Podmana [2] and Bazel's
linux-sandbox. Slightly less secure but working processwrapper sandbox
is used as a workaround.
[1] https://github.com/kubevirt/libguestfs-appliance/pull/17
[2] https://github.com/bazelbuild/rules_docker/issues/2251
=> Build our own libguestfs appliance

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/kubevirt.go
Using 'ReadWriteOncePod' with others access modes causing a conflict. Basing on CDI usage to determine the access mode based on storage profile, we should fetch only one combination, basing on the storage profile is sorted to 'Block' and 'ReadWriteMany' by CDI when creating a storage profile. If the user overrides the defaults, we will respect it.
=> Use single combination of access mode (backport)

virt-v2v/cold/WORKSPACE
Bazel requires the exact SHA of the arch it uses instead of the parent SHA.
=> Fix centos9 image SHA

operator/roles/forkliftcontroller/templates/api/deployment-forklift-api.yml.j2, operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-forklift-api.yml.j2, pkg/forklift-api/webhooks/util/util.go, pkg/forklift-api/webhooks/validating-webhook.go, pkg/forklift-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go, pkg/forklift-api/webhooks/webhooks.go
When using the volume populator, it can't migrate to a static storage class. This patch will prevent from starting such plan, indicating the problem to the user.
=> Validate dynamic storage class

pkg/controller/plan/kubevirt.go
Reverts kubev2v/forklift#328
This is related to the issue: https://github.com/kubev2v/forklift/issues/333
It does not fix it, it just removes the commit form 2.4.1 so we can have a stable release.
=> Revert "Use patch instead of update to set PVC owner references (backport)"

pkg/controller/plan/kubevirt.go
Revert of Revert https://github.com/kubev2v/forklift/pull/334
And fix the client `r.Client.Patch` -> `r.Destination.Client.Patch`
=> Revert Revert "Use patch instead of update to set PVC owner references"

.github/workflows/pull-request.yml
instead of always using the latest CI code switch to tags. 
this will allow more precise control over the CI infrastructure code.
=> change CI to use forkliftci tags

pkg/controller/plan/adapter/openstack/builder.go
- Fix wrong VMWare VIF models
- Fix wrong VMWare to Kubevirt VIF mapping
- Map all unknown VIF models to default VIF model (virtio)
=> openstack: fix virtual interface mapping

operator/BUILD.bazel, operator/config/rbac/api/role.yaml, operator/config/rbac/api/role_binding.yaml, operator/config/rbac/api/service_account.yaml, operator/config/rbac/kustomization.yaml, operator/roles/forkliftcontroller/templates/api/deployment-forklift-api.yml.j2
forklift-api doesn't need big amount of permissions to resources. Therefore, a new service account for the API with strict permissions can be introduced.
=> Split forklift-api service account

.github/workflows/pull-request.yml
part of the effort to eliminate CI job instability of OpenStack,we want to include  the packstack container journal in the CI artifacts.
=> CI collect systemd journal log for packstack container

virt-v2v/cold/BUILD.bazel
For some reason latest glibc in CentOS Stream 9 causes QEMU in TCG emulation to fail to boot and leads to kernel panic. Revert to previous glibc version when building the libguestfs appliance.
There is another issue somewhere causing that when the appliance build triggers kernel panic the build will not terminate and QEMU is stuck waiting forever. This makes the investigation of a failure complicated, but it's something we cannot fix on our side.
=> virt-v2v: cold: do not use glibc-2.34-66

pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/migration.go
After moving VM creation to the end of the flow checkpoint update became
broken. As a result old snapshots were not removed during incremental
warm migration and checkpoints were not updated on DateVolume CR.
Fixes #301
=> VMware snapshots removal during warm migration

.github/workflows/pull-request.yml
improve OpenStack CI job stability,include the packstack  rabbitmq logs in the CI artifacts.
=> CI collect rabbitmq log for packstack container

pkg/controller/provider/container/ovirt/client.go
The oVirt provider uses the GET request instead of the POST to authenticate the provider. The issue is that if the auth fails the url is logged with all credentials to the pod log. Using the POST logs only the url.
=> oVirt provider: Use POST request instead of GET for auth

pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/context/migration.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/validation.go, pkg/controller/provider/validation.go
Do not require VDDK image to be configured in the VMware provider. Instead of validating on the provider level we now validate on the plan. For migration that do not use the EL9 virt-v2v image (cold to remote cluster and warm) the VDDK image remains mandatory.
=> controller: vsphere: make VDDK image optional

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/ovirt/BUILD.bazel, pkg/controller/plan/adapter/ovirt/client.go, pkg/settings/migration.go
Because of ovirt-engine's internal locks, starting a snapshot removal operation will lock the VM, and will prevent other snapshot removals on the same VM, leaving all snapshots around except for the first one.
This patch waits for each snapshot removal to complete before starting the next one. And if one fails it would retry 3 times, because there is a possible race with image transfer, as CDI does not currently wait correctly for the transfer to finish.
=> ovirt: perform snapshot removal sequentially

cmd/ovirt-populator/ovirt-populator.go
Make the log more pleasant to look at, example:
```
I0605 13:04:29.609857       1 ovirt-populator.go:131] {"transferred": 0, "elapsed": 2.337852492928505e-06, "description": "creating transfer"}
I0605 13:04:30.707293       1 ovirt-populator.go:131] {"transferred": 0, "elapsed": 1.0974310429301113, "description": "command failed"}
I0605 13:04:30.707454       1 ovirt-populator.go:131] {"transferred": 0, "elapsed": 1.0978067519608885, "description": "command failed"}
I0605 13:04:30.719615       1 ovirt-populator.go:131] 2023-06-05 13:04:30,707 ERROR   (MainThread) [tool] Command failed
I0605 13:04:30.719698       1 ovirt-populator.go:131] Traceback (most recent call last):
I0605 13:04:30.719769       1 ovirt-populator.go:131]   File …
```
=> ovirt: do not show json parsing error in the log

pkg/controller/plan/adapter/ovirt/client.go
=> ovirt: limit snapshot cleanup to warm migrations only

cmd/openstack-populator/openstack-populator.go, cmd/ovirt-populator/ovirt-populator.go
When creating the populate pod all the secret var being fetch and read, including the CA filed for insecure flow.
From the UI it's not causing any issue because this field is automatically added with empty value,
but from the CLI if a secret being create without the CA (like it should for insecure migration) the pod creation will failed and crush when trying to read this value, this fix should solve the issue.
=> Fix CA var reading for insecure flow

pkg/controller/plan/controller.go
We lost the execution-completed condition on the plan when adding the `populatorLabels` annotation because the plan was returned back from the server (while patched) with conditions that are not 'staged'. We also preserve the Referenced data of the plan when patching it, as we do elsewhere when updating it.
=> Fix transition of plans back to Ready state once they are completed

operator/docs/k8s.md, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/api/service-forklift-api.yml.j2, operator/roles/forkliftcontroller/templates/controller/ca.yml.j2, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, operator/roles/forkliftcontroller/templates/controller/route-inventory.yml.j2, operator/roles/forkliftcontroller/templates/controller/service-inventory.yml.j2, operator/roles/forkliftcontroller/templates/must-gather-api/ca.yml.j2, operator/roles/forkliftcontroller/templates/must-gather-api/deployment-must-gather-api.yml.j2, operator/roles/forkliftcontroller/templates/must-gather-api/service-must-gather-api.yml.j2, operator/roles/forkliftcontroller/templates/ui/configmap-ui.yml.j2, operator/roles/forkliftcontroller/templates/validation/ca.yml.j2, operator/roles/forkliftcontroller/templates/validation/deployment-validation.yml.j2, operator/roles/forkliftcontroller/templates/validation/service-validation.yml.j2, pkg/settings/inventory.go, validation/entrypoint.sh
Previously, users had to disable TLS when running Forklift on plain Kubernetes.
However, since it was introduced forklift-api requires to generate certificates also on Kubernetes using cert-manager.
This PR forces the validation, inventory and must-gather-api services to use TLS on Kubernetes in a similar way.
The ui service has not changed since it is going to be dropped soon.
=> Enforce TLS on Kubernetes

operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
For the 'main' container in the 'forklift-controller' pod.
=> Drop inventory's API_TLS_CA env var on OpenShift 

tests/suit/framework/ovirt.go
this PR fixes issue in ovirt  tests infra where connection to oVirt fails due to missing password   and error is not handled
example: 
https://github.com/eslutsky/forkliftci/actions/runs/5303377976/jobs/9598959057#step:8:41 
```
Test Panicked
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:260
```
=> missing password in ovirt custom Environment tests

pkg/controller/provider/container/ovirt/model.go
Previously, this event was handled as an operation that updates a VM and thus VMs that were imported from an export domain or from an OVA were not added to the inventory. This is now solved by handling this event as an operation that adds a VM.
=> ovirt: treat IMPORTEXPORT_IMPORT_VM as 'add' operation

pkg/controller/plan/adapter/openstack/builder.go, validation/policies/io/konveyor/forklift/openstack/floating_ips.rego, validation/policies/io/konveyor/forklift/openstack/floating_ips_test.rego
Although the OpenStack Floating IPs do not represent any physical
network interface within the VM, they are associated to specific
VM's IP/Port and therefore they both use the same MAC addresses.
As this is causing conflicts in network mappings we will
ignore them.
=> openstack: Ignore OpenStack floating IP addresses

pkg/controller/provider/container/ovirt/client.go, pkg/lib/inventory/web/client.go
The oVirt auth request must be Content-type `application/x-www-form-urlencoded`, which requires the URL encoding inside the POST data request. [1]
For this was necessary to update the Post method in Client. If the posted body is a type string, it will pass it as it is. If the body is any other type, it uses the json.Marshal for json formatting, which the oVirt auth API does not support.
[1] https://www.ovirt.org/documentation/doc-REST_API_Guide/#oauth-authentication
=> oVirt provider: Fix the POST auth request

.github/workflows/create-new-pr.yml, .github/workflows/run-osp-extended-tests.yml
this GH action will trigger  openstack extended tests in  a self hosted runner .
this PR consists of the following items:
-  [x] trigger the test  with a certain comment and report the job status on the PR.
-  [ ] provision self hosted fedora VM on ovirt and join as a runner to forklift gh repo.
each template is configured to work with specific `org/repo`
-  [x] run the extended on the self hosted runner.
-  [x] remove the runner VM
-  [x] make sure only [codeowner](https://github.com/kubev2v/forklift/blob/main/.github/CODEOWNERS#L5) in `tests/ can trigger the job using  comment.
-  [ ] scale-out - support multiple  concurrent runs (up to maximum)
=> run e2e-openstack-extended test in self hosted runner

pkg/controller/plan/controller.go
When updating the plan some data is not loaded from the server, like status. We previously fixed this issue partially in commits c286c78 and c97a2b8.
=> Prevent unnecessary renaming of imported VMs

pkg/controller/provider/container/ovirt/client.go, pkg/lib/inventory/web/client.go
Continuation of: https://github.com/kubev2v/forklift/pull/403
Commits:
oVirt provider: Use POST request instead of GET for auth https://github.com/kubev2v/forklift/commit/ae45b2ee79e5f78d72b47ea9a041326705700789
oVirt provider: Fix the POST auth request https://github.com/kubev2v/forklift/commit/fbd454fcda60bcbdc76e0f4f3d92c38aad873dbf
=> Backport for 2.4.2: Use POST request instead of GET for auth with fix

hack/ovirt-populator/Containerfile
Fix oVirt populator build when done in a git workspace
Resolves #411
=> ovirt: fix ovirt-populator build

validation/policies/io/konveyor/forklift/openstack/bios_boot_menu.rego, validation/policies/io/konveyor/forklift/openstack/cpu_shares.rego, validation/policies/io/konveyor/forklift/openstack/host_devices.rego, validation/policies/io/konveyor/forklift/ovirt/bios_boot_menu.rego, validation/policies/io/konveyor/forklift/ovirt/cpu_shares.rego, validation/policies/io/konveyor/forklift/ovirt/host_devices.rego
=> openstack: update validation rules

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/provider/container/ovirt/resource.go, pkg/controller/provider/model/ovirt/model.go
Add a bootable attribute to the ovirt provider, which allows us to specify from which disk the VM should be booted.
=> ovirt: Add bootable attribute to the provider

.github/workflows/pull-request.yml
we want to free some space from the default runner instance for our CI needs.
=> remove unused packages from ubuntu gh-runner

pkg/controller/provider/container/openstack/client.go
Unwrapping the error converts all the gophercloud errors to
gophercloud.ErrUnexpectedResponse type so it does not make
sense to check ErrDefault404, ErrResourceNotFound and ErrDefault403.
We will check the status code instead.
=> openstack: Fix isNotFound and isForbidden methods

pkg/controller/provider/container/ovirt/model.go
The IMPORTEXPORT_IMPORT_VM event should be treated exactly like USER_ADD_VM_FINISHED_SUCCESS, as both mean a VM was added to oVirt - this way imported VMs won't get stuck in Analysing state.
=> Fix handling of VMs that are imported to oVirt

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/provider/container/ovirt/model.go, pkg/controller/provider/container/ovirt/resource.go, pkg/controller/provider/model/ovirt/model.go, pkg/controller/provider/web/ovirt/disk.go, validation/policies/io/konveyor/forklift/ovirt/disk_storage_type.rego, validation/policies/io/konveyor/forklift/ovirt/disk_storage_type_test.rego
This patch will allow importing direct LUNs from oVirt provider to
kubeVirt. The attached direct LUNs will be created in the destination
cluster. It will be connected to the VM as PVC and a PV which contains
the relevant direct LUN details.
Only on late oVirt version the API provides the relevant details.
Therefore, older version can not perform this flow.
The storage should be exposed to the destination environment.
=> Migrate VMs with direct LUNs from ovirt

pkg/lib/inventory/web/client.go
It seems that in
`pkg/controller/watch/handler/handler.go`
```go
func (r *Handler) Error(w *libweb.Watch, err error) {
log.Info(
"event: error.",
"id",
r.id,
"error",
err.Error())
if !r.ended {
_ = w.Repair()
}
}
```
err will always be nil if we get there from:
```go
case libmodel.Error:
r.handler.Error(&Watch{reader: r}, nil)
```
=> fix NPE when libmodel.Error is received

cmd/forklift-api/BUILD.bazel, cmd/forklift-api/forklift-api.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/plan-mutator.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
- Fix the 'entrypoint' logger that wasn't set correctly
- Fix for 'odd number of arguments passed as key-value pairs for logging' error
=> Improve logs of forklift-api

pkg/controller/provider/container/openstack/client.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator.go
- Shorten checks of errors we get from gophercloud
- Shorten definition of boolean variables in secret-mutator.go
=> Minor cleanup

pkg/controller/provider/web/ocp/resource.go
Add compatibility ID field for OCP base resource type
Why this is needed:
Users of forklift API (for example the UI) expect an "id" json field and not a "uid" field.
=> Add compatibility ID field for OCP base resource type

operator/config/manifests/bases/forklift-operator.clusterserviceversion.yaml
Added 2.5 and which versions of openshift it supports in the operator description.
=> Add compatibility to the operator description

pkg/controller/plan/migration.go
LUNs disks are a special case. They do not have a task when migrating and we do not need to update their progress. The disk are pre-made and just being attached. Therefore, we need to skip them.
=> Skip LUN task progress

pkg/controller/plan/kubevirt.go
In c33a65b, we dropped by mistake the libvirt-domain-xml and vddk-vol-mount mounts from the virt-v2v container when migrating from vSphere (and kept them only when migrating from OVA provider). This broke warm migration from vSphere and decrease the speed of cold-migrations significantly. Thus, adding back the missing mounts.
=> Add missing mounts for virt-v2v container

pkg/apis/forklift/v1beta1/plan/migration.go
When migrating a LUN disk from ovirt source in warm migration we need to mark the CopyDisk as completed.
=> Fix LUN warm migration

pkg/apis/forklift/v1beta1/plan/migration.go
When migrating a LUN disk from ovirt source in warm migration we need to mark the CopyDisk as completed.
=> Fix LUN warm migration (backport)

validation/policies/io/konveyor/forklift/openstack/shared_disk.rego, validation/policies/io/konveyor/forklift/openstack/shared_disk_test.rego
Fix the shared disk validation when the attachments
array is empty.
=> validation: fix openstack shared disk validation

pkg/controller/plan/adapter/ocp/adapter.go, pkg/controller/plan/adapter/ocp/builder.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/context/migration.go
Since migration can be done from a remote source we have to use the source client
=> ocp: use source client where needed

pkg/controller/plan/adapter/ova/validator.go, pkg/controller/provider/container/ova/collector.go, pkg/controller/provider/container/ova/model.go, pkg/controller/provider/container/ova/resource.go, pkg/controller/provider/model/ova/doc.go, pkg/controller/provider/model/ova/model.go, pkg/controller/provider/model/ova/tree.go, pkg/controller/provider/web/ova/BUILD.bazel, pkg/controller/provider/web/ova/base.go, pkg/controller/provider/web/ova/client.go, pkg/controller/provider/web/ova/doc.go, pkg/controller/provider/web/ova/provider.go, pkg/controller/provider/web/ova/storage.go, pkg/controller/provider/web/ova/tree.go
This fix changes the storage mapping for OVA provider from disk -> SC into general storage name -> SC.
The mapping should be in the following format:
```
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
name: storage-map
namespace: konveyor-forklift
spec:
map:
- destination:
storageClass: nfs-csi
source:
name: VM storage
provider:
destination:
name: host
namespace: konveyor-forklift
source:
name: provider-ova
namespace: konveyor-forklift
```
=> Change the storage mapping for OVA

virt-v2v/cold/entrypoint
Since we now support two flows in the virt-v2v image, it doesn't end with the actual `virt-v2v` command. In that case the pod may end with success although, it didn't. Now the script will exit with an error on the first error occurrence.
Fix https://github.com/kubev2v/forklift/issues/494#issuecomment-1664686693
=> Exit when virt-v2v cold hit an error

virt-v2v/cold/entrypoint
Since we now support two flows in the virt-v2v image, it doesn't end with the actual `virt-v2v` command. In that case the pod may end with success although, it didn't. Now the script will exit with an error on the first error occurrence.
=> Exit when virt-v2v cold hit an error (backport)

virt-v2v/cold/entrypoint
fixing the error in the entrypoint script:
line 5: [: missing `]'
=> Fix virt-v2v bracket

virt-v2v/cold/entrypoint
fixing the error in the entrypoint script:
line 5: [: missing `]'
backport of #503
=> Fix virt-v2v bracket (backport)

.bazelrc, WORKSPACE, virt-v2v/cold/.bazerlc, virt-v2v/cold/BUILD.bazel
This patch will bump the ubi9-minimal image and include the fix of the SSL connection to the cold virt-v2v.
=> Fix TLS SSL connection on FIPS enabled systems

pkg/controller/provider/web/ocp/client.go
When looking up VMs in plans we need to use the namespace from the Ref, and not rely on splitting the name
backport of #513
=> ocp: use namespace from Ref when present

pkg/lib/client/openstack/client.go
The format has to always be raw for OpenShift Virtualization
=> openstack: use raw format for images

virt-v2v/cold/entrypoint
Since we added OVA we had two options to execute the virt-v2v command. Now the command will be built and will be executed at the end without conditions regarding the source. This will allow us to know if we had an error and fail the pod in such case.
=> Fix virt-v2v entrypoint script

pkg/apis/forklift/v1beta1/mapping.go
Consider namespace/name format for source NAD
=> ocp: fix mapping name check

virt-v2v/cold/entrypoint
Since we added OVA we had two options to execute the virt-v2v command. Now the command will be built and will be executed at the end without conditions regarding the source. This will allow us to know if we had an error and fail the pod in such case.
=> Fix virt-v2v entrypoint script (backport)

pkg/controller/plan/adapter/ovirt/BUILD.bazel, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/migration.go, pkg/controller/provider/web/client.go
Issue:
If there is some operation on VMs snapshots (creation, deletion). The migration fails because of the locked disks, and the migration ends.
Fix:
Add a retry in the form of a different exception, `ProviderNotReadyError`, which does not end the migration but reconciles. 
There was another issue during this fix. Every try created another failed job with the same correlation ID which failed the migration. The fix for this was to use events and check the proper event codes.
=> ovirt client: Add retry for creating of snapshot 

.bazelrc, WORKSPACE, virt-v2v/cold/.bazerlc, virt-v2v/cold/BUILD.bazel
This patch will bump the ubi9-minimal image and include the fix of the SSL connection to the cold virt-v2v.
backport of #509 , #511
=> Fix TLS SSL connection on FIPS enabled systems (backport)

pkg/controller/plan/adapter/ovirt/BUILD.bazel, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/migration.go, pkg/controller/provider/web/client.go
Backport of #483 to release-v2.5.0
=> Backport ovirt client: Add retry for creating of snapshot

cmd/forklift-controller/BUILD.bazel, virt-v2v/cold/WORKSPACE, virt-v2v/warm/.bazelrc, virt-v2v/warm/BUILD.bazel, virt-v2v/warm/WORKSPACE, virt-v2v/warm/entrypoint
Similar to #226 but on el8 (the appliance used with el8 libguestfs does not support qcow2 images so the image is still compressed within the container image and extract by the 'entrypoint' script).
fix #479
=> virt-v2v: Build our own fixed appliance on el8

pkg/controller/plan/adapter/ocp/builder.go
Otherwise we end up using the variable which we copy over the same interface and keep the type
https://github.com/golang/go/wiki/LoopvarExperiment
=> ocp: copy loop var when iterating over interfaces

pkg/controller/plan/adapter/ocp/builder.go
https://github.com/kubev2v/forklift/pull/532
=> backport: ocp: copy loop var when iterating over interfaces

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
It seems like dv.PVC is always nil because we don't create a DV from a PVC, this leads to failing to find the DV whenever the importer pod fails and it will restart forever instead of 3 times
=> Check claimName on DV status

pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
When no firmware is provided by the OVF of the imported OVA, default the firmware to EFI.
=> Default OVA VMs firmware to EFI

pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
When no firmware is provided by the OVF of the imported OVA, default the firmware to EFI.
backport of #564
=> Default OVA VMs firmware to EFI (backport)

operator/config/rbac/api/role.yaml, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
When a new provider being created in the first run we sets the fields of the secrete and in the second iteration the owner reference of the provider, since the second iteration counts as `update` operation the webhook blocks the provider creation.
This fix checks if the URL filed wasn't changed and if not the operation is permitted, this allow to the creation of the provider to pass successfully.
=> Fix secret admitter to allow OVA provider creation

virt-v2v/cold/BUILD.bazel
Both methods work the same way but the latter better aligns with how we create other images, like must-gather.
=> Replace 'printf' with 'echo -ne'

pkg/controller/provider/container/openstack/BUILD.bazel, pkg/controller/provider/container/openstack/model.go
If a volume of a VM changes we need to update the VM's revision to make sure it is revalidated
=> openstack: update VM revision on volume change

validation/policies/io/konveyor/forklift/openstack/image_format.rego, validation/policies/io/konveyor/forklift/openstack/image_format_test.rego
The format of the image is stored as image.diskFormat rather than image.disk_format - change the validation and its tests accordingly.
=> openstack: fix image format validation

operator/BUILD.bazel, operator/config/rbac/kustomization.yaml, operator/config/rbac/populator-controller/role.yaml, operator/config/rbac/populator-controller/role_binding.yaml, operator/config/rbac/populator-controller/service_account.yaml, operator/roles/forkliftcontroller/templates/controller/controller-scc.yml.j2, operator/roles/forkliftcontroller/templates/populator/deployment-populator-controller.yml.j2, pkg/controller/plan/kubevirt.go, pkg/lib-volume-populator/populator-machinery/controller.go
In order to run on restricted namespaces, the v2v/populator pods need to be set with securityContext.seccompProfile.type that is either RuntimeDefault or Localhost. Thus, we set it in the security context constraints of the service account forklift-controller.
This PR also introduces a new service account for the forklift-populator-controller pod. Currently, it uses the same RBAC as forklift-controller service account. Later on, we will restrict the RBAC to what the populator-controller needs.
Fixes #173
=> Fix migrations to restricted namespaces

tests/suit/framework/framework.go
This change will make the target namespaces of the migrations to be restricted.
=> Tests: make the namespaces restricted

cmd/forklift-api/BUILD.bazel, cmd/forklift-api/forklift-api.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
... rather than when the hooks are called to avoid "concurrent map read and map write" error.
=> api: Add Forklift API to scheme during initialization

virt-v2v/cold/BUILD.bazel
These changes disable EMS checks when FIPS is enabled by changing configuration files in /etc.
The link /etc/pki/tls/fips_local.cnf that points to a configuration file within the FIPS crypto policy is replaced with a regular file, and Options=RHNoEnforceEMSinFIPS is added to the crypto_policy section in /etc/pki/tls/openssl.cnf
Fix #556
=> Disable EMS check without changing /usr/share

pkg/controller/plan/adapter/ocp/BUILD.bazel, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/adapter/ocp/validator_test.go
The namespace may be missing from the network name, in this case we need to use the VM's namespace
=> ocp: consider missing namespace in network name

pkg/controller/plan/adapter/openstack/builder.go
Backport of https://github.com/kubev2v/forklift/pull/601
=> backport: openstack: consider volume type names as well

pkg/controller/plan/adapter/ocp/validator.go
name and namespace were in an incorrect order
=> ocp: fix network lookup

operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-plans.yml.j2, operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-providers.yml.j2, operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-secrets.yml.j2
10 seconds are usually enough but in some cases, it takes few seconds to instantiate a client for interacting with the cluster and then this 10 seconds timeout is reached. Therefore, aligning the timeout of the validation webhooks with that of mutating webhooks.
=> Increase timeout of validation webhooks to 30 seconds

operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-plans.yml.j2, operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-providers.yml.j2, operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-secrets.yml.j2
10 seconds are usually enough but in some cases, it takes few seconds to instantiate a client for interacting with the cluster and then this 10 seconds timeout is reached. Therefore, aligning the timeout of the validation webhooks with that of mutating webhooks.
backport of https://github.com/kubev2v/forklift/pull/607
=> Increase timeout of validation webhooks to 30 sec

cmd/forklift-api/BUILD.bazel, cmd/forklift-api/forklift-api.go, pkg/forklift-api/BUILD.bazel, pkg/forklift-api/api.go, pkg/forklift-api/webhooks/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutators/plan-mutator.go, pkg/forklift-api/webhooks/validating-webhook.go, pkg/forklift-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go, pkg/forklift-api/webhooks/webhooks.go
By using a single client that is injected to the webooks we not only decrease the execution time of webhooks that interact with the cluster (and thus need the client) but also resolve an issue that happens in some environments where it takes relatively long time to instantiate the client (few seconds) and then the execution of the webhook reaches a 13-seconds timeout. The deployment of Forklift gets stuck when this repeatedly happens when trying to add the "default host provider".
=> use a single client in webhooks

cmd/forklift-api/BUILD.bazel, cmd/forklift-api/forklift-api.go, pkg/forklift-api/BUILD.bazel, pkg/forklift-api/api.go, pkg/forklift-api/webhooks/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutators/plan-mutator.go, pkg/forklift-api/webhooks/validating-webhook.go, pkg/forklift-api/webhooks/validating-webhook/admitters/BUILD.bazel, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go, pkg/forklift-api/webhooks/webhooks.go
By using a single client that is injected to the webooks we not only decrease the execution time of webhooks that interact with the cluster (and thus need the client) but also resolve an issue that happens in some environments where it takes relatively long time to instantiate the client (few seconds) and then the execution of the webhook reaches a 13-seconds timeout. The deployment of Forklift gets stuck when this repeatedly happens when trying to add the "default host provider".
=> use a single client in webhook

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/provider/BUILD.bazel, pkg/controller/provider/container/ova/client.go, pkg/controller/provider/controller.go, pkg/controller/provider/ova-setup.go
Until now when adding a new OVA provider we were mount the NFS volume directly to the server/ conversion pod, this worked for some of the cases but wasn't supported on a restricted or different namespaces from forklift/MTV since NFS is not permitted. This fix switch the use of NFS to used shared PVC for both of the cases instead.
=> OVA: changing nfs mount to server and conversion pod to use shared PVC

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/provider/BUILD.bazel, pkg/controller/provider/container/ova/client.go, pkg/controller/provider/controller.go, pkg/controller/provider/ova-setup.go
Until now when adding a new OVA provider we were mount the NFS volume directly to the server/ conversion pod, this worked for some of the cases but wasn't supported on a restricted or different namespaces from forklift/MTV since NFS is not permitted. This fix switch the use of NFS to used shared PVC for both of the cases instead.
=> Backport https://github.com/kubev2v/forklift/pull/592

WORKSPACE
It's not used, let's make it more clear by dropping it from the workspace.
=> Drop goproxy from the WORKSPACE

virt-v2v/cold/WORKSPACE, virt-v2v/warm/WORKSPACE
After upgrading io_bazel_rules_docker, there is a requirment to have com_github_pkg_errors.
```
Analyzing: target //:push-forklift-virt-v2v (47 packages loaded, 519 targets configured)
ERROR: /home/runner/.cache/bazel/_bazel_runner/77ef990d3c7f0c39ee8ff0e654aac8c8/external/io_bazel_rules_docker/container/go/cmd/pusher/BUILD:22:11: no such package '@com_github_pkg_errors//': The repository '@com_github_pkg_errors' could not be resolved: Repository '@com_github_pkg_errors' is not defined and referenced by '@io_bazel_rules_docker//container/go/cmd/pusher:go_pusher'
ERROR: Analysis of target '//:push-forklift-virt-v2v' failed; build aborted: 
```
=> Fix the build of virt-v2v images

pkg/controller/provider/ova-setup.go
Currently migration to restricted namespaces is working but the provider creation is failing since the ova-server pod doesn't have proper security configuration to run on such namespaces, this fix adds the missing parts.
=> Fix creation of ova provider in restricted namespaces.

WORKSPACE
CVE-2023-45142 was resolved in 0.57.1, upgrading to 0.58.0 (latest)
=> Bump OPA for CVE-2023-45142

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
Long time ago, we posted VMs at the beginning of the migration and then started and stopped them during the migration and therefore in order to restore their original power state, we had to initiate another call to patch the VM with its desired power state.
However, now that we post the VMs at the very last steps of the migration, we can set their desired power state in their specification and avoid another call to the target environment.
=> fix #437: Post VMs with desired 'Running' state

pkg/controller/plan/adapter/ocp/client.go
The client's PowerOn function is supposed to start the VM on the source environment when the migration is canceled, thus replacing the destination client with the source client in OCP client's PowerOn function.
=> fix OCP client's PowerOn

pkg/apis/forklift/v1beta1/plan/vm.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
The function Client#PowerState returned the power state as a string under the assumption that its values would be On, Off, or Unknown. However, that was not enforced and it was easy to get confuse and return different values. The client for OpenStack did just that and returned the status that is received from OpenStack, for instance ACTIVE, and that led to have different power state than On when a VM was running on OpenStack at the time the migration was triggered, resulting in not setting the migrated VM with Running = true and therefore the migrated VM was stopped in KubeVirt even though it was supposed to start.
Therefore, we change the return argument for the power state in the Client#PowerState function to have its own type (reverting b4ff20b), VMPowerState, and change this function …
=> Fix power state handling from OpenStack

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
When we migrate from oVirt, vSphere, OpenStack and OVA, we override the Features and Clock sections  of the VMs that are based on the template in KubeVirt that corresponds to the operating system of the migrated VM, if such a template exists. This PR changes the relevant Builders to avoid overriding these sections with empty settings. It's OK to override fields that are taken from the template with values based on the configuration of VMs in the source system, but it makes no sense to override fields from the template with empty values, as for example it clears Hyperv features that are useful for Windows guests.
When we take Hyperv flags from the template, we need to make sure that the clock is also taken from the template (since it needs to be Hypervclock). …
=> Set Hyperv features from KubeVirt template

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/util/BUILD.bazel, pkg/controller/plan/util/utils.go, pkg/settings/logging.go, pkg/settings/migration.go, pkg/settings/policy.go, pkg/settings/profiler.go, pkg/settings/settings.go
This patch will allow the user to configure the filesystem overhead. Currently it defaults to 10%. The overhead is mainly required for ext4 and the root partition.
=> Make the filesystem overhead configurable

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/util/BUILD.bazel, pkg/controller/plan/util/utils.go, pkg/settings/logging.go, pkg/settings/migration.go, pkg/settings/policy.go, pkg/settings/profiler.go, pkg/settings/settings.go
This patch will allow the user to configure the filesystem overhead. Currently it defaults to 10%. The overhead is mainly required for ext4 and the root partition.
https://issues.redhat.com/browse/MTV-699
=> Make the filesystem overhead configurable (backport)

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/lib-volume-populator/populator-machinery/BUILD.bazel, pkg/lib-volume-populator/populator-machinery/controller.go
This patch will keep the populator pod existence when failing. It won't restart or recreated. This is in the mind of aligning with v2v pod failure and the thought that once we fail, we will most likely keep failing. This change will allow to get the populator logs in case of failure in a easy way.
=> Keep the populator pod on failure

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/lib-volume-populator/populator-machinery/BUILD.bazel, pkg/lib-volume-populator/populator-machinery/controller.go
This patch will keep the populator pod existence when failing. It won't restart or recreated. This is in the mind of aligning with v2v pod failure and the thought that once we fail, we will most likely keep failing. This change will allow to get the populator logs in case of failure in a easy way.
=> Keep the populator pod on failure (backport)

pkg/settings/migration.go
We should never fallback to use hard-coded images but rather fail when
an image is missing. Thus, removing DefaultVirtV2vImage that pointed to
forklift-virt-v2v:latest in quay.io and returning an error when
VIRT_V2V_IMAGE is not specified instead.
Also replace ordinary if-statements with if-with-a-short-statement to reduce
the length of Migration#Load.
=> Remove DefaultVirtV2vImage

pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/host.go, pkg/controller/provider/container/vsphere/collector.go
The client to vSphere didn't respect the value to use insecure connections. Now, it will be taken out from the secret and will be respected.
=> Respect unsecured connections to vSphere

pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/host.go, pkg/controller/provider/container/vsphere/collector.go
The client to vSphere didn't respect the value to use insecure connections. Now, it will be taken out from the secret and will be respected.
=> Respect unsecured connections to vSphere (backport)

pkg/controller/provider/ova-setup.go
When a new namespace is created in OpenShift, it is automatically labeled with `pod-security.kubernetes.io/audit`, which refers to a secondary, restricted security level. The situation diffrent in Kubernetes and for the default namespace, where such automatic labeling does not occur. When a namespace is marked as restricted, an additional label, `pod-security.kubernetes.io/enforce`, is added. This label represents the highest security level, where violations are not permitted. When deploying an OVA server pod, it is created with standard settings across all namespaces, except those marked only with the enforce option. In these cases, extra configuration is required to eliminate any potential security violations.
=> Fix creation of OVA server pod under enforced restricted namespaces

pkg/controller/provider/ova-setup.go
When a new namespace is created in OpenShift, it is automatically labeled with `pod-security.kubernetes.io/audit`, which refers to a secondary, restricted security level. The situation diffrent in Kubernetes and for the default namespace, where such automatic labeling does not occur. When a namespace is marked as restricted, an additional label, `pod-security.kubernetes.io/enforce`, is added. This label represents the highest security level, where violations are not permitted. When deploying an OVA server pod, it is created with standard settings across all namespaces, except those marked only with the enforce option. In these cases, extra configuration is required to eliminate any potential security violations.
=> Fix creation of OVA server pod under enforced restricted namespaces (backport)

.gitignore, Makefile, hack/post-vendor.sh
It's hard to enforce developers to use `make vendor` so dropping the post-vendor.sh script that removed unused files that introduce warning by code analyze tools and we will use .gitignore rules instead.
=> Replace post-vendor.sh with a .gitignore rule

pkg/controller/provider/container/ova/collector.go, pkg/controller/provider/container/ova/model.go
Currently when a VM is deleted from the NFS share it is not removed from the inventory, this change will support it.
https://issues.redhat.com/browse/MTV-733
=> OVA: Add support for removing deleted vms from the inventory

pkg/controller/plan/kubevirt.go
Before version 2.4, the virt-v2v conversion pod operated on a local disk after the disk was retrieved by CDI. CDI considered the transfer network when transfering the data from vSphere.
As from version 2.4, when running a cold-migration to the local cluster, virt-v2v is also responsible to connect to vSphere and retrieve the disk(s) from there, therefore it now needs to consider the transfer network that is selected as well.
This patch adds the transfer network, if set, on the conversion pod in both cases.
https://issues.redhat.com/browse/MTV-835
=> Set transfer network on the conversion pod

pkg/controller/plan/kubevirt.go
This label is used for identification of the virtual machine instance(s) that will be created from the VM, for example for load balancing, see:
https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/d3b008cb5d7855b54ab912dda9f8d174dd93dcbc/workshop/content/08_migrate_vms.adoc#review-and-configure-migrated-virtual-machines
https://issues.redhat.com/browse/MTV-843
=> Add 'app' label to the template of the migrated VM

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/util/utils.go, pkg/settings/migration.go
This patch will allow the user to configure the block overhead.
Currently it defaults to 0. The overhead is required when migrating to
encrypted Ceph RBD (block). The pod may see less space on the disk and
therefore the migration will fail when it tries to allocate the last
sectors. See more about encrypted Ceph RBD in:
https://docs.ceph.com/en/quincy/rbd/rbd-encryption/
The value needs to be set in the ForkliftController spec under the
value: `controller_block_overhead`. The addition will be the fixed
number provided to the size of the disk.
=> Make the block overhead configurable

.github/workflows/pull-request.yml
In order to align with the whole project and not failing the CI, this patch will lock bazel to 5.4.0.
=> Lock bazel in CI build

pkg/controller/plan/adapter/ovirt/builder.go
Adds el9, win11 and win2k22 for the OS mappings when importing from ovirt. This will help selecting the right template for the VM in the destination cluster.
The OS templates names are taken using:
https://gitlab.com/libosinfo/osinfo-db/-/tree/main/data/os
=> Add missing OS from mapping

operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/util/utils.go, pkg/settings/BUILD.bazel, pkg/settings/migration.go
When specifying resources like disk sizes, the value is expected to represent a quantity rather than an integer so users can set values like "1Gi". Applying this to controller_block_overhead as well.
=> Change controller_block_overhead to quantity

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/util/utils.go, pkg/settings/BUILD.bazel, pkg/settings/migration.go
This patch will allow the user to configure the block overhead. Currently it defaults to 0. The overhead is required when migrating to encrypted Ceph RBD (block). The pod may see less space on the disk and therefore the migration will fail when it tries to allocate the last sectors. See more about encrypted Ceph RBD in:
https://docs.ceph.com/en/quincy/rbd/rbd-encryption/
The value needs to be set in the ForkliftController spec under the value: `controller_block_overhead`. The addition will be the fixed number provided to the size of the disk.
=> Make the block overhead configurable (backport)

cmd/openstack-populator/BUILD.bazel, cmd/openstack-populator/openstack-populator.go, cmd/openstack-populator/openstack-populator_test.go, cmd/ovirt-populator/ovirt-populator.go, pkg/lib-volume-populator/populator-machinery/controller.go
* This PR also changes the populator controller and ovirt-populator to use `envFrom` instead of a file to pass the secret.
This will eventually go into the CDI controller PR, but is also useful here for now
=> openstack: add simple test for the openstack-populator

pkg/controller/provider/controller.go, pkg/controller/provider/ova-setup.go, pkg/controller/provider/validation.go
While the OVA provider pod is being created, the pod status currently displays `connectionFailed` until the OVA pod is actually up and running, this gives the wrong impression that something went wrong during the OVA provider creation. This fix changes the phases for the OVA provider. Once the provider is added, the status will immediately show `staging`. If there is a failure during the OVA provider creation process, or if the pod is not running after 10 minutes (consider as a timeout), the status will change to `connectionFailed`.
=> OVA: Fix phases display for OVA provider creation

operator/config/manager/manager.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/openstack/BUILD.bazel, pkg/controller/plan/adapter/openstack/client.go, pkg/settings/migration.go
Before removing the snapshot attempt to make sure the volume has been removed
=> openstack: wait for volume to be removed

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/builder.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
=> openstack: fix cognitive complexity

Makefile
Until now we didn't test the unit tests of the validation image unless executed manually. Now it will be tested as part of `make test`.
=> Add validation unit tests to generic tests

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go, validation/policies/io/konveyor/forklift/ovirt/tpm.rego, validation/policies/io/konveyor/forklift/ovirt/tpm_test.rego, validation/policies/io/konveyor/forklift/vmware/tpm_enabled.rego, validation/policies/io/konveyor/forklift/vmware/tpm_enabled_test.rego
When having a TPM device from the source(oVirt - based on having windows 2022 or windows 11 OS),
create it also for the destination VM.
The data is persist in oVirt. Therefore, if supported by kubevirt the TPM will be persistent TPM,
otherwise the TPM without persistent data.
**A warning will be shown as the data will be lost during the migration**
In order to have the TPM persistent it is required to have kubvirt
v1.0.0 and adding configuration manually as described in:
https://kubevirt.io/user-guide/virtual_machines/persistent_tpm_and_uefi_state/
It is also supported in CNV running on OCP 4.14, and you need to follow:
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/virtualization/virtual-machines#virt-using-vtpm-devices …
=> Add a warning and support of TPM

pkg/controller/provider/container/vsphere/collector.go
The addition of the property "summary.config.tpmPresent" breaks compatibility with vSphere 6.5 ("InvalidProperty" error is returned when building the inventory). This patch reverts this part temporarily until we change this to work also with older versions of vSphere.
Related to #665
=> Disable TPM gathering from vSphere temporarily

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/openstack/common.go
Image based migrations can get stuck since there is no check to ensure they were created in the inventory before attempting to progress, this will lead to the migration progressing to the next phase, but the PVC will not be created.
This patch adds the relevant property and checks the snapshot image is in the inventory before progressing
=> openstack: check image is in the inventory before progressing

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/provider/container/ovirt/model.go, pkg/controller/provider/container/ovirt/resource.go, pkg/controller/provider/model/ovirt/doc.go, pkg/controller/provider/model/ovirt/model.go, pkg/controller/provider/model/ovirt/tree.go, pkg/controller/provider/web/ovirt/BUILD.bazel, pkg/controller/provider/web/ovirt/base.go, pkg/controller/provider/web/ovirt/client.go, pkg/controller/provider/web/ovirt/cluster.go, pkg/controller/provider/web/ovirt/doc.go, pkg/controller/provider/web/ovirt/servercpu.go, pkg/controller/provider/web/ovirt/tree.go, pkg/controller/provider/web/ovirt/workload.go
If the user may wish to migrate and preserve the cluster CPU model.
Therefore, in the plan spec it will be possible now to set `PreserveClusterCPUModel` to `true` and forklift
will set the VMs with the source cluster CPU model.
=> Keep the cluster CPU

pkg/controller/plan/adapter/vsphere/host.go
Currently, all validations fail because we cannot access the hosts with secure connections. In https://github.com/kubev2v/forklift/pull/656 the code has changed to take the configuration of the client connection from the secret, however, the secret of the ESXi hosts is never set with the insecure flag.
This change practically makes the client to the hosts be always insecure. It's not that significant because the data we get from the host does not include data that could be confidential.
=> Fix validation of ESXi network configuration

pkg/controller/plan/adapter/vsphere/host.go
Currently, all validations fail because we cannot access the hosts with secure connections. In https://github.com/kubev2v/forklift/pull/656 the code has changed to take the configuration of the client connection from the secret, however, the secret of the ESXi hosts is never set with the insecure flag.
This change practically makes the client to the hosts be always insecure. It's not that significant because the data we get from the host does not include data that could be confidential.
=> Fix validation of ESXi network configuration (backport)

pkg/controller/provider/container/vsphere/BUILD.bazel, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/collector_test.go
Since #694, we disabled the TPM gathering to avoid "InvalidProperty" error.
vSphere started supporting TPM API in 6.7, based on that version we will gather the TPM on supported versions.
=> Enable TPM gathering from vSphere

operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/api/mutatingwebhookconfiguration-providers.yml.j2, operator/roles/forkliftcontroller/templates/api/mutatingwebhookconfiguration-secrets.yml.j2, pkg/apis/forklift/v1beta1/provider.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/forklift-api/webhooks/mutating-webhook.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/BUILD.bazel, pkg/forklift-api/webhooks/mutating-webhook/mutators/provider-mutator.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go, pkg/forklift-api/webhooks/webhooks.go, tests/suit/BUILD.bazel, tests/suit/ova_test.go, tests/suit/vsphere_test.go, virt-v2v/cold/entrypoint
This PR adds the ability to add a vSphere provider that connects to SDK that is served by an ESXi host, instead of that of  vCenter. This allows users to import directly from environments that comprise of ESXi hosts, without vCenter.
We don't add a new type of provider since most of the code is similar in both cases, the SDK that is exposed from ESXi aligns with the one exposed from vCenter. The only difference is that in case we operate with an ESXi host, we need to set the libvirt URL with `esx://` rather than `vpx://` for virt-v2v.
For vSphere providers that interact with an ESXi hosts, the backend doesn't assume clients specify the credentials for the host as these credentials were already specified for the provider - a mutating webhook copies the credentials from the secret of the …
=> Support adding an ESXi host as a source provider

pkg/controller/plan/adapter/vsphere/builder.go
We do not enable selecting a network to interact with vCenter so there's no point in using an IP rather than a hostname. Using a hostname also allows us to use certificates from the vCenter host.
=> Use hostname rather than IP for vCenter

.bazelrc, .github/workflows/pull-request.yml, operator/config/crd/bases/forklift.konveyor.io_providers.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/api/deployment-forklift-api.yml.j2, operator/roles/forkliftcontroller/templates/api/route-services.yml.j2, operator/roles/forkliftcontroller/templates/api/service-services.yml.j2, operator/roles/forkliftcontroller/templates/api/services-ca.yml.j2, operator/roles/forkliftcontroller/templates/ui-plugin/console-plugin.yml.j2, pkg/apis/forklift/v1beta1/provider.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/provider/container/BUILD.bazel, pkg/controller/provider/container/util.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/validation.go, pkg/forklift-api/BUILD.bazel, pkg/forklift-api/api.go, pkg/forklift-api/services/BUILD.bazel, pkg/forklift-api/services/services.go, pkg/forklift-api/services/tls-certificate.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go, tests/suit/utils/secrets.go, tests/suit/vsphere_test.go, virt-v2v/cold/.bazerlc, virt-v2v/cold/BUILD.bazel, virt-v2v/cold/entrypoint
Since 2.4 we require users to provide fingerprint/thumbprint, also for insecure providers, and secure migrations practically don't work for vSphere providers.
This main contributions in this PR are:
1. We enable secure migrations from vSphere in case the required certificate doesn't exist in the system pool: the forklift-controller and virt-v2v pods use a certificate that is specified in the provider's secret.
2. We drop the fingerprint field for (secure/insecure) vSphere providers
This PR also introduces an additional service that returns the TLS certificate for a given URL. The idea is that clients, and specifically forklift-console-plugins, would use it to simplify the certificate gathering for users (by getting the certificate over an insecure channel, and asking the user to confirm …
=> Enable secure migrations from vSphere

cmd/ovirt-populator/ovirt-populator.go
The ovirt-img found in `/usr/local/bin` which is part of `$PATH`. There is no reason to give a full path to the binary which may change on different versions.
=> Change ovirt-img path

pkg/controller/provider/web/vsphere/BUILD.bazel, pkg/controller/provider/web/vsphere/base.go, pkg/controller/provider/web/vsphere/base_test.go
We used to break when encontering a datacenter while creating a path of a host. That was ok in most cases since Datacenters typically reside within the root folder named "Datacenters" that should not be part of the path that is passed to virt-v2v and libvirt.
However, it is possible to create nested datacenters, which reside within a folder under the aforementioned root folder, and in this case we need to include the parent folder of the datacenter in the path of the host. Therefore, we now don't stop traveling when encountering a datacenter but rather continue and break when we encounter a folder that has an empty parent instead, without adding this folder (the root folder) to the path.
=> vsphere: consider parentless folder a terminal node

.github/workflows/pull-request.yml
This PR started with bumping codecov-action to v4 but this version seems to be premature at this point.
Instead, we now set a token for the action and print the cover.out to the log for debugging
=> Attempting to fix upload coverage report

WORKSPACE
We no longer build the OVA provider server using a dockerfile so we can drop 'ova-provider-server-image-dockerfile' which is the only place where dockerfile_image is used.
=> Drop dockerfile_image

.github/workflows/pull-request.yml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/BUILD.bazel, pkg/controller/plan/controller.go, pkg/controller/plan/migration.go, pkg/controller/plan/validation.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go, pkg/settings/migration.go, tests/suit/vsphere_test.go
This PR introduces two-step validation of the VDDK init image:
1. The provider's validating webhook fails providers with empty VDDK init image setting. VDDK can be omitted when users don't want to use it (though it's highly recommended to use VDDK to accelerate migrations from vSphere) but it cannot be set with empty value now.
2. The validation of plans in forklift-controller creates a job on the target provider that checks the validity of the specified VDDK image by checking the existence of `/opt/vmware-vix-disklib-distrib/lib64/libvixDiskLib.so`. The job is set with `ActiveDeadlineSeconds` of 300  seconds (which is configurable) so that if the VDDK image cannot be pulled, the job would fail. There can be more than a single job for a plan in case the VDDK image for the provider changes …
=> Validate VDDK

validation/policies/io/konveyor/forklift/ovirt/vm_os.rego, validation/policies/io/konveyor/forklift/ovirt/vm_os_test.rego, validation/policies/io/konveyor/forklift/vmware/vm_os.rego, validation/policies/io/konveyor/forklift/vmware/vm_os_test.rego
This patch will warn the user if an unsupported OS is being migrated.
Currently only EL6 is being checked.
Fixes https://issues.redhat.com/browse/MTV-413
=> Validate incoming EL6 OS

validation/policies/io/konveyor/forklift/ova/cpu_affinity.rego, validation/policies/io/konveyor/forklift/ova/cpu_affinity_test.rego, validation/policies/io/konveyor/forklift/ova/cpu_memory_hotplug.rego, validation/policies/io/konveyor/forklift/ova/cpu_memory_hotplug_test.rego, validation/policies/io/konveyor/forklift/ova/memory_ballooning.rego, validation/policies/io/konveyor/forklift/ova/memory_ballooning_test.rego, validation/policies/io/konveyor/forklift/ova/name.rego, validation/policies/io/konveyor/forklift/ova/name_test.rego, validation/policies/io/konveyor/forklift/ova/rules_version.rego, validation/policies/io/konveyor/forklift/ova/uefi_boot.rego, validation/policies/io/konveyor/forklift/ova/uefi_boot_test.rego, validation/policies/io/konveyor/forklift/ova/validate.rego
Adding VMs validations for OVA, since the OVA model is a subset of the vSphere one (using a similar structure and variable names in the inventory) the same validation were used, excluding the one that related to cluster/hosts or running state of the VM or any other configuration that are not relevant for OVA VMs.
=> Add VMs validation for OVA provider

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ova/validator.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/lib/util/util.go
As the signature of the function is:
Wrap(err error, kvpair ...interface{})
It expects to get an error and key-value pairs. However, in some places we also pass a message after the error, which breaks this expectation. In this PR those messages are dropped to remain with an odd number of arguments.
=> Fix calls to liberr.Wrap with even number of args

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/kubevirt.go, pkg/controller/plan/util.go, pkg/controller/plan/validation.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go
1. Fix the provider-admitter to allow changing the VDDK init image for a vSphere provider that serves as the source provider for existing plans.
2. Ensure the target namespace exists in the target provider before creating the VDDK validation job.
=> Follow up on VDDK validation

cmd/forklift-api/BUILD.bazel, cmd/forklift-controller/BUILD.bazel
We used to enable static linking for forklift-api and forklift-controller which is not needed anymore.
=> Drop static linking

pkg/controller/provider/container/ovirt/collector.go
Currently when the connection test returns 500 we have no error reported which makes the connection test succeed despite failure.
Return an error when the status returned by the connection test is not 200
=> ovirt: fix connection test

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
An issue has been identified where manually constructed names for PVCs lead to migration failures, especially during restarts or when reusing the same plan names. This occurs because of conflicts with existing PVCs. To address this, the implementation now utilizes `GeneratedName` to ensure unique naming and prevent collisions. Correspondingly, the cleanup process has been changed to accommodate these changes.
=> OVA: generate random names for NFS pv and PVS used for migration

pkg/controller/plan/adapter/vsphere/builder.go
Users should specify the URL in the secret in case they like the system to validate the provider configuration using a webhook (additional labels are also required on the secret in this case). But when users ar not interested in such validations, they can omit the URL from the secret and the migration from a valid provider should succeed.
However, recent changes in the builder of vSphere caused the URL we pass to virt-v2v to be taken from the secret and thus virt-v2v was provided with an empty URL in the aforementioned case, causing the migration to fail. Here, we replace that part and rather take the URL from the configuration of the provider (instead of its secret).
=> vSphere: URL in the secret is optional

pkg/controller/plan/adapter/ovirt/builder.go
When having an error creating a PVC, the real cause wasn't shown in the logs. Now the reason will appear both on the plan status and in the controller logs.
Fixes: [MTV-928](https://issues.redhat.com/browse/MTV-928)
=> Propagate PVC creation error

pkg/controller/plan/adapter/ovirt/builder.go
When having an error creating a PVC, the real cause wasn't shown in the logs. Now the reason will appear both on the plan status and in the controller logs.
Fixes: [MTV-928](https://issues.redhat.com/browse/MTV-928)
=> Propagate PVC creation error (backport)

pkg/controller/plan/validation.go
The security context was set with RunAsNonRoot = true while the user wasn't specified, which lead to an error when migrating to the default namespace: container has runAsNonRoot and image will run as root. This issue is fixed by setting the user to the QEMU user (107).
=> vSphere: Fix security context of VDDK validation pod

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go
In OCP 4.15, CDI dropped their annotation of the import disk ID. We added an annotation `forklift.konveyor.io/disk-source` before to the DataVolumes only which propagates to the PersistentVolumeClaim. Now it will also be included on other non-CDI flows.
This change is made as we used the CDI annotation to be an identifier when importing a disk. Not having it caused an NPE. Now we will use the forklift annotation.
=> Add forklift disk ID annotation to DV and PVCs

pkg/controller/plan/validation.go
When validating a plan we have specific logic that applies for source providers of type OpenShift but the check of the type of the source provider didn't take into consideration that the source provider may be invalid, leading to a sig fault. Here we extend the function that validates the source providers of type OpenShift with nil-check of the source provider as done in other validation function for a plan, and also nil-check of the destination provider.
=> Fix validation of plans with an invalid source provider

pkg/controller/plan/adapter/ova/builder.go
currently for some cases the vm is not being match correctly in the builder which leads to not fetching the firmware value set by virt-v2v, which lead to that the default firmware value being set for bios VMs.
* need to be verified -  the bug is currently randomly reproducing.
=> OVA: match the correct vm for the firmware value

pkg/controller/plan/adapter/ovirt/builder.go
The liberr.Wrap function should get an odd number of arguments, otherwise the description of the specified error would be overridden (follow-up on #772).
=> Do not override description of wrapped error

operator/requirements.yml
Version 2.4.2 contains the fix for newer OCP versions.
=> Bump kubernetes.core ansible collection

operator/requirements.yml
Version 2.4.2 contains the fix for newer OCP versions.
=> Bump kubernetes.core ansible collection (backport)

cmd/ova-provider-server/ova-provider-server.go
In some of the OVF file the configuration can be found under `ExtraConfig` rather that `Config`, currently the first option isnt supported in the OVA server and we may miss some impotent information,  this PR adds it.
example:
`<vmw:Config ovf:required="false" vmw:key="cpuHotRemoveEnabled" vmw:value="false"/>`
`<vmw:ExtraConfig ovf:required="false" vmw:key="firmware" vmw:value="efi"/>`
=> OVA: map vm configuration from extraConfig in ovf file

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go
Since percentages are not fractions we need to divide
=> ovirt,openstack: divide progress by 100

virt-v2v/cold/entrypoint.go
When importing from vSphere a multiple-boot operation system v2v will ask the user which one to use. In our case virt-v2v isn't interactively. Therefore, we will default to the first boot device as we done previsouly.
=> Add root=first to cold v2v command

pkg/controller/plan/adapter/ova/ovfparser.go, pkg/controller/plan/kubevirt.go, virt-v2v/cold/entrypoint.go
The change to use `-o kubvirt` requires too many adjustments to the virt-v2v pod. For version 2.6, we will continue using -o local and add the firmware type to the created XML after it is detected from the virt-v2v output. Then, this value will be consumed in the controller to determine the missing firmware.
=> OVA: workaround for consuming firmware from virt-v2v

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ovirt/builder.go
In OCP 4.15, CDI dropped their annotation of the import disk ID. We added an annotation `forklift.konveyor.io/disk-source` before to the DataVolumes only which propagates to the PersistentVolumeClaim. Now it will also be included on other non-CDI flows.
This change is made as we used the CDI annotation to be an identifier when importing a disk. Not having it caused an NPE. Now we will use the forklift annotation.
=> Add forklift disk ID annotation to DV and PVCs (backport 2.5)

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/adapter/converter.go, pkg/controller/plan/adapter/openstack/BUILD.bazel, pkg/controller/plan/adapter/openstack/adapter_suite_test.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/destinationclient.go, pkg/controller/plan/adapter/openstack/destionationclient_test.go, pkg/controller/plan/adapter/ovirt/BUILD.bazel, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/ovirt/destinationclient.go, pkg/controller/plan/adapter/ovirt/destinationclient_test.go, pkg/controller/plan/adapter/ovirt/ovirt_suite_test.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/kubevirt_test.go
To avoid conflicts with leftover resources, use generated names.
Note: This can lead to storage filling up due to multiple imports of the same disk
=> use generated name for PVCs and populator CRs

pkg/controller/plan/kubevirt.go
When importing and using DVs, always set the annotation to bind WFFC. This commit removes the consumer pod for vsphere flows as we can use the annotation for it.
=> Always bind WFFC for data volumes

pkg/controller/plan/kubevirt.go
When importing and using DVs, always set the annotation to bind WFFC. This commit removes the consumer pod for vsphere flows as we can use the annotation for it.
=> Always bind WFFC for data volumes (backport 2.6)

pkg/controller/plan/kubevirt.go
When importing and using DVs, always set the annotation to bind WFFC. This commit removes the consumer pod for vsphere flows as we can use the annotation for it.
=> Always bind WFFC for data volumes (backport 2.5)

validation/policies/io/konveyor/forklift/ovirt/tpm.rego, validation/policies/io/konveyor/forklift/vmware/tpm_enabled.rego
Replace "VM configured with a TPM device" with "TPM detected", to align it with what we display for UEFI.
=> Shorten the label of the warning on TPM device

pkg/controller/plan/adapter/openstack/builder.go
Currently, because bootOrder was declared outside the loop, it would keep the same value from a previous iteration, being set on a disk that shouldn't be set.
=> openstack: fix bootOrder setting

virt-v2v/cold/entrypoint.go
When breaking the scanner loop for firmware detection, we cause the virt-v2v pod to run indefinitely. The call to virtV2vCmd.Wait() waits for the virtV2vCmd process to exit. However, once its `stdout` or `stderr` is not being consumed—in our case, the consumer, virtV2vMonitorCmd for `stdout`, and the scanning loop for `stderr`—so once we break the loop, the consumption stops, and the main command will wait forever for an action that will not happen.
It was intentionally dropped from the code, and I've missed that part addition in the previous code review.
=> OVA: Remove the break to properly consume stderr

pkg/controller/plan/adapter/ovirt/builder.go
Previously, when migrating to the cluster Forklift is deployed on using a cold migration, all disks of the migrated VM were transferred to the same storage class, which is one of the target storage class that appear in the storage mapping that is set for the migration plan.
With these changes, each disk will be mapped to a target storage class based on its original storage domain and the storage mapping that is defined for the migration plan.
=> ovirt: Respect storage mapping

pkg/controller/plan/adapter/vsphere/builder.go
The problem these changes address is as follow: when initiating a cold migration from vSphere to a remote provider of a VM with a snapshot(s), the transferred disk didn't include the most updated state of the disk because the very first volume of the disk, that doesn't include later changes, was transferred.
Unlike warm migrations, in which we intend to transfer the first (base) volume of the disk initially and then copy the changes using CBT, in cold migrations we need to transfer the state of the very last volume to include the most updated state of the disk.
In Forklift 2.3 and below, this issue affected all cold migrations. As from 2.4, it only affects cold migrations to a remote cluster, in which we still use CDI to transfer the disks from vSphere.
=> vsphere: transfer updated disk state on remote migrations

pkg/controller/provider/controller.go
If the OVA provider server fails to be created for any reason, we keep hitting the timeout check in the reconcile and return from there, so we do not reach the cleanup. To solve this issue, a check was added for the provider query to perform only when the provider has not started the deletion process.
=> Do not deploy OVA server pod when the provider is being deleted

pkg/controller/provider/controller.go
If the OVA provider server fails to be created for any reason, we keep hitting the timeout check in the reconcile and return from there, so we do not reach the cleanup. To solve this issue, a check was added for the provider query to perform only when the provider has not started the deletion process.
=> Backport: Do not deploy OVA server pod when the provider is being deleted

pkg/apis/forklift/v1beta1/doc.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/openstack/builder_test.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/provider/web/openstack/client.go, tests/suit/BUILD.bazel, tests/suit/openstack_test.go, tests/suit/utils/storagemap.go
Since it's possible to create a plan without storage maps, image based VMs that have no volumes attached will crash the controller with an NPE when attempting to fetch the storage map
=> openstack: avoid NPE when there's only an image attached

pkg/controller/plan/kubevirt.go
The name of importer pods starts with `importer-<pvc name>`. This patch will change the way we find the importer pods for a particular PVC name.
=> Get the proper importer pods

pkg/controller/plan/kubevirt.go
The importer pods name starts with `importer-<pvc name>`. This patch will change the way we find the importer pods for a particular PVC name.
=> Get the proper importer pods (backport)

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
Previously we didn't set the guest memory but only memory request, since the guest memory property is optional and according to the documentation it "Defaults to the requested memory in the resources section if not specified.". However, if we don't set it and the migrated VM is based on a template/instancetypepreference, the value of this field would be retrieved from the template/instancetypepreference, which may be different than what the VM had on the source and this could lead to various issues, e.g., starting with insufficient memory for booting.
=> Set guest memory

pkg/controller/plan/kubevirt.go
In 98b06ec we switched an Error log to Info and by that we lost the trace from the code that tries to find a template in KubeVirt in case it raises an error. Switching that log to Error again in order to restore this information.
=> Log a non-nil error from findTemplate

operator/roles/forkliftcontroller/templates/controller/configmap-osmap-ovirt.yml.j2, operator/roles/forkliftcontroller/templates/controller/configmap-osmap-vsphere.yml.j2
Until now, if the user wished to create his own OS map for preferences the operator would think his new config map is managed by itself. This will cause the operator to add mappings for which the keys don't exist.
Backport of #843
=> Let the os maps be fully customized (backport)

pkg/controller/plan/kubevirt.go
We always looked up for cluster wide preference even when we found a local one.
=> Fix local preference

pkg/controller/plan/kubevirt.go
We always looked up for cluster wide preference even when we found a local one.
Backport of #841
=> Fix local preference (backport)

pkg/controller/provider/container/vsphere/BUILD.bazel, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/container/vsphere/utils.go
when we get datastores from the ESXi SDK, their identifier may be in the form of '10.11.12.13:/vol/virtv2v/function' which leads to invalid endpoints in the inventory so we sanitize such identifiers
=> Sanitize datastore identifiers from ESXi providers

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
When using preferences the timer configuration may conflict with the empty timer we used to set. That would lead windows VMs to fail running.
=> Don't set time within clock

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
When using preferences the timer configuration may conflict with the empty timer we used to set. That would lead windows VMs to fail running. Since `Time` is optional and we used to have it empty - this patch will drop it.
Backport of #853
=> Don't set time within clock (backport)

pkg/controller/plan/kubevirt.go
In b0d0a68, we incorrectly dropped a check that skips setting the "cdi.kubevirt.io/storage.bind.immediate.requested" annotation when using virt-v2v on el9 - in that case, the conversion pod acts as the first-consumer of the data volume and thus, there is no need in artificial first-consumer pod.
See https://issues.redhat.com/browse/CNV-40266
=> vSphere: skip immediate binding when using virt-v2v on el9

pkg/settings/migration.go
Reduce the amount of timeouts for larger PVCs
=> ocp: increase export timeout to 12 hours

pkg/controller/plan/kubevirt.go
We may have VM without OS set. In such case we get an empty string from the map. This patch will prevent querying and erroring when we hit this case.
=> Skip querying preference if OS is empty

pkg/settings/migration.go
https://github.com/kubev2v/forklift/pull/863
=> backport: ocp: increase export timeout to 12 hours

Makefile, virt-v2v/cold/BUILD.bazel, virt-v2v/cold/colde_test.go, virt-v2v/cold/entrypoint.go
Currently, the function generating the disk names didn't work as expected, and instead of matching the disk number with the corresponding letter, it caused the letters to be attached from the previous disk. This resulted in only the first disk being properly copied due to incorrect linking. With these changes, the disk name generation works as expected.
=> Fix virt-v2v disk name generation

Makefile, virt-v2v/cold/BUILD.bazel, virt-v2v/cold/cold_test.go, virt-v2v/cold/entrypoint.go
Currently, the function generating the disk names didn't work as expected, and instead of matching the disk number with the corresponding letter, it caused the letters to be attached from the previous disk. This resulted in only the first disk being properly copied due to incorrect linking. With these changes, the disk name generation works as expected.
backport: https://github.com/kubev2v/forklift/pull/872
=> backport: fix virt-v2v disk name generation

operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/configmap-trusted-ca.yml.j2
apparently, recent versions of OpenShift doesn't set the 'trustedCA' property in the cluster's Proxy, leading to our operator failing on checking "proxy_cluster.spec.trustedCA.name|length > 0". we no longer need the config map as we dropped the old, standadlone, UI.
=> drop trusted-ca config map

pkg/controller/plan/migration.go
When MTV is not installed on the remote OCP cluster and we try to cleanup we won't succeed. This patch won't try to remove or edit forklift entities, as if MTV doesn't exist there, it will fail - causing the plan to fail.
Backport of #865
=> Don't cleanup forklift entities on remote cluster (backport)

pkg/controller/plan/kubevirt.go, pkg/controller/provider/container/vsphere/model.go, validation/policies/io/konveyor/forklift/vmware/datastore.rego, validation/policies/io/konveyor/forklift/vmware/datastore_test.rego
=> Backports of 81db7e6 and bc7f240

pkg/controller/plan/kubevirt.go, pkg/settings/features.go
Removed the retainAfterCompletion annotation from DataVolumes.
This is still configurable by setting `FEATURE_RETAIN_PRECOPY_IMPORTER_PODS`.
=> Drop retainAfterCompletion

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/vsphere/builder.go, pkg/settings/migration.go, virt-v2v/cold/entrypoint.go
Add an argument for extending the virt-v2v command with additional arguments that are taken from ForkliftController. This allows to modify the virt-v2v command, without creating new images.
=> v2v: add extra args

pkg/forklift-api/services/tls-certificate.go, pkg/lib/util/util.go
The content-type of the response that included the TLS certificate wasn't set, and therefore static analysis tools could have thought we intend to return text/html that wasn't sanitized. However, in this case the return value is not in the form of text/html but text/plain. Now the content-type is set accordingly to avoid that and so that clients won't treat the output as HTML.
This commit also reverts 3848777a.
=> Set content-type of tls-certificate response

operator/roles/forkliftcontroller/tasks/main.yml
We no longer deploy must-gather-api but we haven't made sure that we remove the deployment when it already exists and therefore the must-gather-api pod remains running when upgrading from a version in which must-gather-api is deployed.
=> operator: remove must-gather-api deployment on upgrade

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/provider/container/ovirt/BUILD.bazel, pkg/controller/provider/container/ovirt/collector.go, pkg/controller/provider/container/ovirt/collector_suite_test.go, pkg/controller/provider/container/ovirt/collector_test.go
Since
https://github.com/kubev2v/forklift/commit/0e9edd7f45ebe54aac80fa35278e359d144da4e0, the way we get PVCs associated with VMs has changed. This patch adds the relevant labels to the LUN PVCs, so we can get them correctly.
Also, there is a difference of versioning between ovirt to rhv. Now we can use them both in the version validation.
=> Fix direct LUN migrations

pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/provider/container/ovirt/BUILD.bazel, pkg/controller/provider/container/ovirt/collector.go, pkg/controller/provider/container/ovirt/collector_suite_test.go, pkg/controller/provider/container/ovirt/collector_test.go
Since
https://github.com/kubev2v/forklift/commit/0e9edd7f45ebe54aac80fa35278e359d144da4e0, the way we get PVCs associated with VMs has changed. This patch adds the relevant labels to the LUN PVCs, so we can get them correctly.
Also, there is a difference of versioning between ovirt to rhv. Now we can use them both in the version validation.
Backport of #897
=> Fix direct LUN migrations (backport)

cmd/virt-v2v-monitor/BUILD.bazel, cmd/virt-v2v-monitor/virt-v2v-monitor.go, virt-v2v/cold/entrypoint.go
After switching to use a Go wrapper, not all the information was redirected to the virt-v2v monitor command. Additionally, with changes done in the virt-v2v progress display, the progress was not reported to the controller. This patch fixes the piping to the virt-v2v monitoring command and the regex used to determine the copy disk progress of the migration.
https://github.com/kubev2v/forklift/pull/901
=> Fix virt-v2v progress update

cmd/virt-v2v-monitor/BUILD.bazel, cmd/virt-v2v-monitor/virt-v2v-monitor.go, virt-v2v/cold/entrypoint.go
After switching to use a Go wrapper, not all the information was redirected to the virt-v2v monitor command. Additionally, with changes done in the virt-v2v progress display, the progress was not reported to the controller. This patch fixes the piping to the virt-v2v monitoring command and the regex used to determine the copy disk progress of the migration.
=> Fix virt-v2v progress after using go wrapper

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
Change connection refuse check for virt-v2v vm configuration server, and change the order of the functions so it will fully complete the progress and only then fetch the vm configuration.
=> OVA: Change connection refuse check for virt-v2v vm configuration server

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/plan/adapter/ova/validator.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/builder_test.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/adapter/vsphere/validator_test.go, pkg/controller/plan/adapter/vsphere/vsphere_suite_test.go, pkg/controller/plan/controller.go, pkg/controller/plan/validation.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go, pkg/lib/condition/condition.go, virt-v2v/cold/cold_test.go, virt-v2v/cold/entrypoint.go
This patch will get the static IPs configurations from the vSphere provider to each guest and will propagate it to virt-v2v to set it up while converting the VM.
Backport https://github.com/kubev2v/forklift/pull/852
=> Map vSphere static IPs (backport)

pkg/controller/plan/kubevirt.go, pkg/settings/features.go
Removed the retainAfterCompletion annotation from DataVolumes. This is still configurable by setting
`FEATURE_RETAIN_PRECOPY_IMPORTER_PODS`.
Backport of #858
=> Drop retainAfterCompletion (backport)

pkg/controller/plan/adapter/vsphere/builder.go
When migrating from an ESXi provider, always take the fingerprint from the status of the provider, even when there is a transfer network configured for the host since the SDK of ESXi doesn't return the fingerprint of the host as vCenter does.
=> Always take fingerprint from ESXi provider

operator/config/manager/manager.yaml
The forklift-operator pod is not CPU intensive, so minimal CPU time should be sufficient. When it comes to memory, in some environments it consumes ~40Mi and in others ~100Mi, so asking for 64Mi seems reasonable.
see [this](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4079#issuecomment-1959939530)
=> Set resource requests for forklift-operator

pkg/controller/plan/scheduler/vsphere/scheduler.go
when scheduling migrations to accommodate the controller_max_vm_inflight setting for vSphere, we didn't take into account that disks are transferred sequentially by virt-v2v (as opposed to CDI that transfers them in parallel by different pods). This lead to performance degregeration since could have triggered more migrations, in case of migrations of multi-disk VMs, simultaneously without exceeding the value of controller_max_vm_inflight. This is fixed by setting the cost of each VM for which the disks are transferred by virt-v2v to 1.
=> vsphere: virt-v2v transfers disks sequentially

pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/lib/ref/ref.go
1. load hosts per source provider
When looking for the configuration of an ESXi host that a certain VM resides on, we query all the hosts in the namespace and then looking for the host by its MOR (Managed Object Reference). This almost always works but it could be wrong when there are several providers within the same namespace that refer to the same host. This is more likely to happen during tests where we define two providers with different propreties for the same vSphere environment. Therefore, adding another check that ensures the host refers to the provider which is the source provider on the plan of the migrated VM, otherwise skip that host.
2. skip archived plans when counting inflight vms
It could be that we have VMs for which the migration is marked as started and not marked as …
=> Fixes for vSphere providers

pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/lib/ref/ref.go
=> Backport fixes for vSphere providers

pkg/controller/plan/BUILD.bazel, pkg/controller/plan/adapter/base/BUILD.bazel, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/BUILD.bazel, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/BUILD.bazel, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/util/utils.go
Previously, when running warm migrations from a vSphere provider with vCenter as its SDK endpoint, we ran create snapshot, set-checkpoints and remove-snapshots on vCenter, even when there was a network defined for an ESXi host. That cause CDI to fail: the identifier of a snapshot that was recievd from vCenter was different than the identifier of the same snapshot in ESXi and therefore CDI, that interacts with ESXi hosts in this scenario, failed to find the snapshot.
Now, when running CBT operations we check whether the disk(s) will be transferred from vCenter or ESXi, and perform the aforementioned CBT operations on the corresponding component.
=> vsphere: perform CBT operations on hosts when needed

virt-v2v/warm/BUILD.bazel
Since we still use it and the mirrorlist isn't pointing to the `vault` repos. A command added to switch the repos. Now they will point `vault`, letting us use `dnf` commands later on.
=> Switch CentOS stream8 repos

.bazelrc, WORKSPACE, operator/BUILD.bazel, operator/Containerfile
We cannot push the operator image with recent images of Ubuntu in GitHub actions because recent versions of Docker create the image differently and as a result, they cannot be pushed to quay.io. Thus, replacing the way we build the operator image to match how other images are built and this way, we are able to push the image to quay.io.
=> Build operator with rules_docker instead of containerfile

operator/config/rbac/leader_election_role.yaml, operator/config/rbac/role.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, operator/roles/forkliftcontroller/templates/monitor/service-metrics.yml.j2, operator/roles/forkliftcontroller/templates/monitor/servicemonitor-metrics.yml.j2
Backport https://github.com/kubev2v/forklift/pull/932
=> Add monitor resources creation to forklift operator

operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, operator/config/rbac/forklift-controller_role.yaml, pkg/apis/forklift/v1beta1/plan/vm.go, pkg/controller/plan/BUILD.bazel, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/builder.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/provider/container/ocp/BUILD.bazel, pkg/controller/provider/container/ocp/collection.go, pkg/controller/provider/container/ocp/collector.go, pkg/controller/provider/model/ocp/BUILD.bazel, pkg/controller/provider/model/ocp/doc.go, pkg/controller/provider/model/ocp/model.go, pkg/controller/provider/web/ocp/BUILD.bazel, pkg/controller/provider/web/ocp/client.go, pkg/controller/provider/web/ocp/clusterinstancetype.go, pkg/controller/provider/web/ocp/doc.go, pkg/controller/provider/web/ocp/instancetype.go
Setting the `instanceType` to the VM will set the specific VM in
the plan with the selected instance type available in the destination
cluster (if found). This means, the VM won't be set with their original
CPUs and memory they had in the source environment.
=> Add support for instance types

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/util.go, pkg/settings/migration.go
Add an optional configuration for a config map in which users can specify configuration files, that should be accessible from within the conversion pod, for virt-v2v.
=> configmap for user-provided v2v configuration files

pkg/controller/plan/vm_name_handler.go, pkg/controller/plan/vm_name_handler_test.go
=> Replace dots with dashes when renaming VMs

pkg/controller/plan/migration.go
In a2170ea we've added the following logic: when using storage classes that are set with WaitForFirstConsumer in migrations from vSphere, we treat the PendingPopulation status as Succeeded since the conversion pod would be the first consumer of the PVCs. This PR applies the same logic also to migrations from OVA providers.
=> Fix migration of OVA to WFFC storage classes

pkg/controller/plan/adapter/ovirt/builder.go
In oVirt, the 'serial' of disks is set to their disk ID. We have noticed that it could be useful for users to preserve the serial that is set in oVirt in order to maintain correlations between disks and their configuration within the guest operating system so we now provide the 'serial' as an input to KubeVirt to achieve this.
[1] https://github.com/oVirt/ovirt-engine/blame/ovirt-engine-4.5.3.z/backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java#L2215
=> ovirt: preserve disk's serial

pkg/monitoring/metrics/forklift-controller/metrics.go, pkg/monitoring/metrics/forklift-controller/migration_metrics.go
To accurately track the total number of migrations in the system, we should change the migration metrics type to a counter. This will help us gather precise data on all migration events, providing better insights. Since the running status applies to all migrations at some point, it was removed from the metrics as it doesn't provide any meaningful information.
=> Change the migration metrics type to counter

operator/roles/forkliftcontroller/templates/ui-plugin/console-plugin.yml.j2
Ref:
https://github.com/openshift/api/pull/1856
https://issues.redhat.com//browse/OCPBUGS-36213
Issue:
Openshift console operator will stop supporting `v1alpha1` version in 4.17.0
Fix:
This PR convert the consoleplugin `v1alpha1` CR to `v1` format
=> Bump consoleplugin cr to console.openshift.io/v1

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-595
**Issue**:
When migrating a simple RHEL8 VM from VMware 7 to OCPv 4.13 the name of the network interfaces changes and the static IP configuration for the VM no longer works
**Why we need this change**:
in MTV-595 we plan to introduce code that will support static IP defined using RHEL7 and above NetworkManager, we will need an indicator for user selecting preserveStaticIPs
**Why this is safe:**
We add a new env var, no other change needed
=> [MTV-595] Add V2V_preserveStaticIPs env var for virt-v2v pod

pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/builder_test.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/adapter/vsphere/validator_test.go
Ref: https://issues.redhat.com/browse/MTV-595
**Issue:**
When migrating a simple RHEL8 VM from VMware 7 to OCPv 4.13 the name of the network interfaces changes and the static IP configuration for the VM no longer works
**What this PR do:**
This PR check if the OS is not Windows, in this case it collects the mac to static IP map, and send it to the `virt-v2v` pod.
Notes:
- On linux we don't check for `origin=manual` because this information is missing on linux. 
- We only send this information when user choose to force static IPs
- The user must run the VM while MTV inventory server is running to create the mapping, IP information is added to the inventory MTV is collecting only when the VM is running, once the IP data is collected, user can power down the VM and MTV will persist this …
=> [MTV-595] Send mac to ip mappings for linux

virt-v2v/cold/customize-rhel.go, virt-v2v/cold/customize-rhel_test.go, virt-v2v/cold/entrypoint.go
Ref: https://issues.redhat.com/browse/MTV-595
Issue:
The original issue was reported on RHEL8, after discussions with reporter we found out that this fix may be helpful for other distributions.
Concerns:
The fix will work for machines that use network manager, but will no nothing in other cases.
=> [MTV-595] Refactor run virt-customize for linux on any non windows

pkg/controller/plan/kubevirt.go
Issue: Right now we leave the placement of the conversion pod up to the kubernetes scheduler. But it can cause issues in large scale enviroments as the scheduler can place all migration pods on one node. This can cause the node to run out of the resources and can slow down the migration.
Fix: Add pod anti affinity which will distribute the migration pods evenly across the nodes.
=> MTV-1354 | virt-v2v add pod anti affinity to the guest conversion pod

virt-v2v/cold/entrypoint.go, virt-v2v/cold/scripts/rhel/run/network_config_util.sh
=> Backport | Initial fix for failting customization

virt-v2v/cold/scripts/rhel/run/network_config_util.sh, virt-v2v/cold/scripts/rhel/run/network_config_util_test
**Issue:**
Our network config script is writen for `bash` and will fail for distributions that link `/bin/sh` to `dash`
**What happen:**
When running the scripts on `ubuntu` we get a syntex error:
```bash
dash virt-v2v/cold/scripts/rhel/run/network_config_util_test
virt-v2v/cold/scripts/rhel/run/network_config_util_test: 31: 
/github.com/kubev2v/forklift/virt-v2v/cold/scripts/rhel/run/network_config_util.sh: Syntax error: 
"(" unexpected (expecting "then")
```
**What should happen:**
```bash
dash virt-v2v/cold/scripts/rhel/run/network_config_util_test 
Test output:
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="aa:bb:cc:dd:ee:ff",NAME="eth0"
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="aa:bb:cc:dd:ee:fe",NAME="eth3"
All tests passed successfully.
```
**Fix:**
Dashifying the code to run …
=> Dashify network utils script

virt-v2v/cold/scripts/rhel/run/network_config_util.sh, virt-v2v/cold/scripts/rhel/run/network_config_util_test
**Issue:**
a mac to ip line looks like` --mac aa:bb:cc:dd:ee:ff:ip:ipaddr[,gw[,len[,ns,ns,...]]]`
aa:bb:cc:dd:ee:ff:ip:192.168.1.10,192.168.1.245,23,,
but in the tests we tested the format:
aa:bb:cc:dd:ee:ff:ip:192.168.1.10
**What happen:**
tests pass with wrong input
**What should happen:**
use currect input for tests, and tests should fail
**Fix:**
fix tests and error in the script
=> Allow more text after ip

pkg/controller/plan/kubevirt.go
Issue: When a user has a plans across many namespaces the v2v anti-affinity does not look for the other pods in different namespaces when using the anti-affinity.
Fix: This PR disables the namespace selector so it looks across whole cluster for the pods and distributes the pods evenly.
=> MTV-1354 | Ignore namespaces when choosing the v2v pod on the nodes

virt-v2v/cold/scripts/rhel/run/network_config_util.sh, virt-v2v/cold/scripts/rhel/run/network_config_util_test
**Issue:**
If network configuration file has quotes the name, this quotes will be transferred to the udev config file.
**Fix:**
Remove quotes. 
**Tests:**
`shellcheck virt-v2v/cold/scripts/rhel/run/network_config_util.sh` - pass
``` sh
bash virt-v2v/cold/scripts/rhel/run/network_config_util_test 
Test output:
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="aa:bb:cc:dd:ee:ff",NAME="eth0"
SUBSYSTEM=="net",ACTION=="add",ATTR{address}=="aa:bb:cc:dd:ee:fe",NAME="eth3"
All tests passed successfully.
```
=> Remove double quates from network config files

virt-v2v/cold/customize-image.go
Issue:
When running `virt-customize` we get a warning:
```
WARNING: Image format was not specified for '/dev/block0' and probing guessed raw.
Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
Specify the 'raw' format explicitly to remove the restrictions.
\x1bc\x1b[?7l\x1b[2J\x1b[0mSeaBIOS (version 1.16.3-2.el9)
```
Fix:
Specifying the format explicitly as raw
=> [MTV-595] Add --format raw to virt-customize call

pkg/controller/plan/migration.go
Issue: The controller gets into a specific setup when it's waiting for the conversion pod put it is not created yet due to some other reasons. This causes the pod to crash and entry crashloopbackoff and if the pod won't be created the controller can't get out of it.
I was also able to find this issue in my testing this is my log:
```
{"level":"info","ts":"2024-09-03 12:25:25.653","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"plan","object":{"name":"copy-of-test-centos-7","namespace":"openshift-mtv"},"namespace":"openshift-mtv","name":"copy-of-test-centos-7","reconcileID":"3d0f9cfb-56e7-43b0-b1ad-2623496bd41c"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: …
```
=> MTV-1353 | Fix NPE when conversion pod does not exists

pkg/controller/provider/web/base/auth.go
Issue: When we request the inventory web endpoint the auth functions
allows the user to get the endpoint even with the incorrect token.
Fix: Change the permit function logic so we do not set the auth=true.
Issue: Right now the request with an invalid token returns 403 instead of
the expected 401.
Fix: Change the `permit` function to return the status code instead of
Boolean.
=> MTV-1377 | Fix the auth to return 401 instead of 403

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/provider/web/base/auth.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1014
- https://github.com/kubev2v/forklift/pull/1013
- https://github.com/kubev2v/forklift/pull/1006
- https://github.com/kubev2v/forklift/pull/999
=> Backport MTV-1354, MTV-1353, MTV-1377 to 2.6.6

virt-v2v/scripts/rhel/run/network_config_util.sh, virt-v2v/scripts/rhel/run/network_config_util_test
Add netplan config parding sh utility for ubuntu static ip
=> Add netplan config parding sh utility for ubuntu static ip

virt-v2v/cold/scripts/rhel/run/network_config_util.sh, virt-v2v/cold/scripts/rhel/run/network_config_util_test
=> Backport | Add netplan config parding sh utility for ubuntu static ip

operator/config/manifests/bases/forklift-operator.clusterserviceversion.yaml
- bump the csv description to 2.7.
- bump the csv minkube version to ocp 4.15
=> Bump forklift csv to 2.7

virt-v2v/pkg/customize/scripts/rhel/run/network_config_util.sh
Support old ubuntu netplan
Issue:
Ubuntu 18 uses vertion of netplan that does not support the get subcommand
Fix:
a. add a python script that mimics netplan get command
b. check if current version of netplan support get
c. run the python script in cases netplan does not support get
=> Support old ubuntu netplan

Makefile, virt-v2v/cold/scripts/rhel/run/network_config_util.sh
Backport of https://github.com/kubev2v/forklift/pull/1036 and https://github.com/kubev2v/forklift/pull/1035
=> Backport | Fix netplan for ubuntu 18

cmd/forklift-controller/main.go, docs/profiling-guide.md
Profiling guide: 
```bash
oc port-forward -n konveyor-forklift pods/forklift-controller-5c99c54dd8-77blm 6060:6060
go tool pprof -http=:9001 localhost:6060/debug/pprof/goroutine
go tool pprof -http=:9002 localhost:6060/debug/pprof/heap
curl -k http://localhost:6060/debug/pprof/trace\?debug\=1\&seconds\=5 -o cpu-trace.out
go tool trace -http=:9003 ./cpu-trace.out
curl -k -o stage.out http://localhost:6060/debug/pprof/goroutine\?debug\=1
```
=> MTV-1343 | Add pprof to the controller

operator/roles/forkliftcontroller/templates/ui-plugin/console-plugin.yml.j2
Issue:
The latest operator fails with error:
`forklift-console-plugin is invalid: spec.proxy[0].endpoint.type: Required value`
=> Operator | Fix console-plugin template

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/plan/adapter/ova/validator.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/validation.go
Issue:
Right now we have a check to fail the migration when we start to create the VM which does not have the CBT enabled. We should throw error much earlier before the customer even start the migration.
Fix:
Add a CBT check to the plan validation. This fix right now affects only VMware migrations.
=> MTV-446 | Warm: Add cbt check before migration

pkg/lib/inventory/web/client.go
Issue: When the request from main to the inventory pod fails the main pod crashes due to nil pointer.
Fix: Move the request close to case when we get the response body.
=> MTV-1482 | Fix main pod inventory watch NPE

build/ovirt-populator/Containerfile
I based the creation of the Dockerfile on this [file](https://github.com/kubev2v/forklift/blob/main/cmd/ovirt-populator/BUILD.bazel) and that is why I'm using `pip install` to install those dependencies. There is another way by using this [copr repo](https://copr.fedorainfracloud.org/coprs/ovirt/ovirt-master-snapshot/) @mnecas @yaacov LMK what you guys prefer
=> chore: add Dockerfile for oVirt populator

build/forklift-api/Containerfile, build/forklift-controller/Containerfile, build/forklift-operator/Containerfile, build/openstack-populator/Containerfile, build/ova-provider-server/Containerfile, build/ovirt-populator/Containerfile, build/populator-controller/Containerfile, build/validation/Containerfile, build/virt-v2v/Containerfile
Needed because we were encountering [this issue](https://gitlab.cee.redhat.com/konflux/docs/users/-/blob/main/topics/getting-started/passing-ec.md#missing-red-hat-manifests-or-sbom) in the EC policy
=> fix: add vendor label to Containerfiles

pkg/controller/plan/kubevirt.go, virt-v2v/cmd/entrypoint.go
Issue:
During the refactoring I have enabled the server, via which we expose the virt-v2v gathered information to the controller, to both migraiton types. The flow is that we request all nessasry information form pod and then manually kill it from the controller. But right now we can't reuqest the server which are in remote clusters.
Fix:
Disable the server in the remote migrations. This will cause the pod to be terminated and the controller will check the pod status and will continue if the pod succeded.
Note:
Because of this we can't get the OS nor Firmware form the remote migrations. This should not be a large issue as we use them right now only for prefenrace in kubevirt.
=> Fix migration to remote cluster

virt-v2v/cmd/entrypoint.go
Issue: 
The windows is missing the static IP address mapping.
Fix:
Add the `--mac` mapping so the virt-v2v-in-place flow.
=> Fix warm migration windows static ip

virt-v2v/cmd/entrypoint.go
Issue:
We have two way to run the v2v either the `virt-v2v` for the cold migration or the `virt-v2v-in-place` for the warm migration. These commands share a lot of arguments and the `virt-v2v-in-place` was missing a lot of them which we already have available for the cold migration.
Fix:
Add shared arguments which should be added to both of the commands.
=> MTV-1495 | Add common arguments for v2v

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/builder_test.go
Issue:
We are not passing the gateway to the `virt-v2v` when there are multiple interfaces.
Fix:
Remove the limitation to have just one gateway and pass everything to the `virt-v2v`.
The MTV should not touch the configuration the VM should be the same after migration as it was before.
Test log:
```
exec: /usr/bin/virt-v2v -v -x -o kubevirt -os /var/tmp/v2v --root first -i libvirt -ic vpx://administrator%40vsphere.local@10.73.213.102/data/host/10.73.212.38?no_verify=1 -ip /etc/secret/secretKey --mac 00:50:56:92:ee:06:ip:10.73.100.100,10.73.100.10,24,10.73.100.1 --mac 00:50:56:92:25:f0:ip:192.168.24.50,192.168.24.1,24,192.168.24.10 -it vddk -io vddk-libdir=/opt/vmware-vix-disklib-distrib -io vddk-thumbprint=86:25:2F:5E:74:5C:43:D9:28:62:31:E0:1F:BB:1F:FD:AC:18:A5:93 -- …
```
=> MTV-1497 | Pass all gateways to the virt-v2v

build/forklift-operator-bundle/Containerfile, operator/export-vars.sh
1. Add a script that Konflux will update with the latest references to the operands. This script is also used during the build for producing the variables that will be used when generating the manifests from templates.
2. Add a Containerfile for building the bundle.
=> Add configs for building a bundle with Konflux

build/virt-v2v/Containerfile
Konflux tests are currently failing because virt v2v component is missing the description label
=> add a description label to Virt-v2v

pkg/controller/plan/migration.go
Issue:
When the virt-v2v pod fails the plan does not fail.
=> MTV-1569 | Fail plan when the conversion pod fails

virt-v2v/cmd/entrypoint.go
Issue:
The MTV specifies the `-on` argument in the wrong place /usr/bin/virt-v2v [...] -- epassaroMigrate-2 -on epassaromigrate-2
Fix:
/usr/bin/virt-v2v [...] -on newname -- oldname
=> MTV-1555 | Fix virt-v2v with new name

pkg/controller/plan/scheduler/vsphere/scheduler.go
Issue:
When running the warm migration with VMs more than the MaxInFlight disks. The VMs over this number won't start the migration till the cutover. Once the cutover is started the VMs which were not started migrate same as in the old migration. So there is larger downtime.
Fix:
Ignore the cost when in `CopyingPaused`, this allows the other Migrations to start as the cost is reduced when the VM disk transfer is finished.
Note:
This patch also improves the cold migration as it ignores the count when creating the VM so the other VM migrations can get started. And dramaticially improves the warm migration time as we are not waiting for the guest conversion as we already have the disk so we start the guest conversion and do not halt the scheduler.
Fixes: …
=> MTV-1543 | Fix warm migration scheduler

pkg/controller/plan/scheduler/vsphere/scheduler.go
Issue: When we start the warm migration with VM which has a lot of disks we wait for the whole VM to get migrated. We do not ignore the disks that has been already migrated. This can cause that when we have 2 VMs with 10 disks each and on each there is one larger disk the whole scheduler will be halted untill they finish. So even if the left 9 disks will be done no migration will be started.
Fix: Subtract the finished disks from the disk count.
Fixes: https://issues.redhat.com/browse/MTV-1537
=> MTV-1537 | Optimalise the plan scheduler

pkg/controller/plan/validation.go
There are multiple cases that can lead to a "VDDK Init image is invalid" error message for a migration plan. They are currently handled with a single VDDKInvalid condition.
This patch adds a new error condition VDDKImageNotFound (and a new advisory condition VDDKImageNotReady) to help diagnose an issue of a missing image or incorrect image url.
Resolves: https://issues.redhat.com/browse/MTV-1150
=> Distinguish between different VDDK validation errors

pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, virt-v2v/cmd/entrypoint.go
Backport:
- https://github.com/kubev2v/forklift/pull/1089
- https://github.com/kubev2v/forklift/pull/1088
- https://github.com/kubev2v/forklift/pull/1087
- https://github.com/kubev2v/forklift/pull/1086
- https://github.com/kubev2v/forklift/pull/1085
- https://github.com/kubev2v/forklift/pull/1084
=> Backport changes to 2.7

pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/controller/plan/scheduler/vsphere/scheduler_test.go
Now we allow migrating with more disks than the MaxInFlight in case there is no VM being migrated at that time. This is done for the user's convenience.
Related to: https://github.com/kubev2v/forklift/pull/1087
=> Fix VMware scheduler test

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
Issue:
When running the migration archive we do not delete the DataVolumes.
Fix:
Add deletion of the DataVolumes when running the archive and the VM migration failed.
At some cases the migration in the context is missing the migration ID so we can use the plan instead to find the DataVolume.
Fixes: https://issues.redhat.com/browse/MTV-1477
=> MTV-1477 | Add DataVolume deletion when archiving

pkg/controller/provider/container/vsphere/model.go, pkg/lib/condition/condition.go
Issue:
When customer applies the CBT on running VM by:
`govc vm.change -vm VM_NAME -e "ctkEnabled=TRUE"`
The customer gets a critical conidtion which does not allow them to migrate the VM.
Fix:
The changes are not propagated to the VM config but to the extra arguments which we need to query.
Fixes: https://issues.redhat.com/browse/MTV-1576
=> MTV-1576 | VMware apply CBT from extra args

pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/controller/plan/scheduler/vsphere/scheduler_test.go, pkg/controller/provider/container/vsphere/model.go, pkg/lib/condition/condition.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1096
- https://github.com/kubev2v/forklift/pull/1091
- https://github.com/kubev2v/forklift/pull/1094
=> Backport to release-2.7

virt-v2v/BUILD.bazel, virt-v2v/WORKSPACE
Issue:
The Centos 9 AppStream repo has an outdated Windows virtio driver which does not support Windows 2022 and has issues with 2019. This change updates the rpm to the fedora package.
This is not a proper fix but WA as the base image is ubi9 and we should not mix the packages.
Fixes: https://github.com/kubev2v/forklift/issues/982
Fixes: https://github.com/kubev2v/forklift/issues/1029
Fixes: https://issues.redhat.com/browse/MTV-1483
=> MTV-1483 | Fix virtio-win driver version

pkg/controller/plan/kubevirt.go
Issue:
When running the virt-v2v with the latest tag it does not pull the updated image.
=> Add Always pull policy for virt-v2v

operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/tasks/webhooks.yml, operator/watches.yaml
When uninstalling the forklift operator, not all resources are removed from the cluster. In particular, there are at least 3 validatingwebhookconfiguration objects and 3 mutatingwebhookconfiguration objects that are left behind. By using a finalizer on the operator, we can ensure that these objects are removed from the cluster.
=> Use a finalizer to make sure web hooks are removed when operator is uninstalled

pkg/controller/plan/controller.go
Commit 0f92c03 backported a patch to add metrics collection to the
controllers, but it was backported incorrectly. The migration controller
and the plan controller both called `RecordMigrationMetrics()`, which
starts the same a goroutine and accesses the same data without
synchronization. The Plan controller should have instead called
`RecordPlanMetrics()` as it does in the upstream code.
Fixes: https://issues.redhat.com/browse/MTV-1530
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
=> Fix crash in 'concurrent map read and write' in v2.6

Makefile, docs/debugging.md, pkg/controller/provider/controller.go, pkg/controller/provider/web/base/client.go, pkg/settings/inventory.go
- Fix forklift-controller missing certs when running locally
- Added a DEBUG_VARS block with default values for key configuration variables.
- Implemented `build-debug-%` target for building binaries with debugging flags.
- Implemented `debug-%` target to run Delve debugger in headless mode.
=> Add debugging makefile targets

pkg/lib/inventory/web/handler.go
Ref:
https://issues.redhat.com/browse/MTV-1220
Issue:
When having lot of VMs in the inventory the controller can fail with:
```
panic: concurrent write to websocket connection
panic: concurrent write to websocket connection
goroutine 4943150 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc004688300, 0x1, {0x0?, 0x29b1560?, 0xc00824b808?})
/remote-source/app/vendor/github.com/gorilla/websocket/conn.go:632 +0x4b8
github.com/gorilla/websocket.(*messageWriter).Close(0x30?)
/remote-source/app/vendor/github.com/gorilla/websocket/conn.go:746 +0x35
github.com/gorilla/websocket.(*Conn).beginMessage(0xc00aa1fce0, 0xc0044ec870, 0x1)
/remote-source/app/vendor/github.com/gorilla/websocket/conn.go:493 +0x47
```
This is caused by the concurrent write to websocket connection this …
=> MTV-1220 | Add lock to the inventory handler

pkg/controller/plan/kubevirt.go, pkg/lib-volume-populator/populator-machinery/controller.go
The importer pod can get stuck creating if there are multiple networks and the wrong default network override annotation is configured. This changes the annotation as requested in [MTV-1645](https://issues.redhat.com/browse/MTV-1645).
I reproduced the bug without the change, and managed a successful transfer with the change applied.
=> MTV-1645 Change default network annotation.

pkg/controller/plan/migration.go
Issue:
When monitoring the migration process the forklift requests the PVC from DV ClaimName. On top of that the forklift checks the Annotation "cdi.kubevirt.io/storage.import.importPodName". But this annotation is missing in the main PVC but is present in the prime pvc, whose format is "prime-$UID_MAINPVC". This annotation points to the created pod which imports the volume.
Fix:
Search the prime PVC instead of the main PVC, so the forklift is able to check the importer pod status.
Ref: https://issues.redhat.com/browse/MTV-1627
=> MTV-1627 | Fix the PVC search for the progress

pkg/controller/plan/migration.go
Issue:
The `CreateSnapshot` is after `RemovePreviousSnapshot` so with the warm migration, we always skipped the snapshot cleanup step. 
Fix:
Get the next migration phase dynamically. This way the VMware migration will run `RemovePreviousSnapshot` and the other migrations will run `CreateSnapshot``.
Ref:
https://issues.redhat.com/browse/MTV-1656
=> VMware warm migration - Fix snapshot cleanup

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/migration.go
Issue: When deleting the snapshot the users with slow storage could get data corruption due to the consolidation process. The consolidation writes the snapshot overlay to the disk and if the user has slow storage it can take a long time. However, the Forklift Controller does not check if the consolidation is finished and creates a new snapshot. This new snapshot could be created in the middle of the writing process and it would not see the changes in the underlying image from the consolidation.
Wrong order
1. Delete snapshot
2. Create snapshot
3. Consolidate
Correct order
1. Delete snapshot
2. Consolidate
3. Create snapshot
Fix: Disable consolidation in the middle of migration and consolidate in RemoveFinalSnapshot phase. This will make the warm migration faster as we don't need to wait …
=> MTV-1656 | Disable snapshot consolidation

operator/config/rbac/leader_election_role.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/tasks/main.yml, operator/roles/forkliftcontroller/templates/monitor/recordingrole-migrations.yml.j2
Following the request of adding recording rule in https://github.com/openshift/cluster-monitoring-operator/pull/2461
=> Add recording rule to collect migrations data to telemetry.

Makefile
`make install` was broken because the directory name had an `s` at the end.
=> fix: change make install target to use the right directory name

virt-v2v/BUILD.bazel, virt-v2v/WORKSPACE
Regression introduced by: https://github.com/kubev2v/forklift/pull/1214 
When running the `./hack/virt-v2v-rpm-deps.sh` it will automatically replace the newer driver with the older available drivers.
=> Fix regression virtio win driver for v2v

pkg/controller/provider/container/vsphere/model.go
Bug MTV-1291 describes an issue where, on ESXi providers, opening the modal dialog for changing the migration network for a host may display a list with multiple copies of the same network listed as options. This same issue was not observed with the vCenter endpoint type for the same provider.
I managed to reproduce this behavior by simply starting a vm on the host. After the VM boots up, the ESXi provider will emit an ObjectUpdate for the host object which contains ChangeSets that assign new values to the list of PNICs, VNICs, portgroups, and vswitches for that host. It doesn't appear that these values have changed, so it's unclear why we're getting change notifications for them. But, the end result is that every time a vm is started, a duplicate list of networks is being appended to the …
=> Fix duplicated network interfaces on ESXi provider

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/network.go
Issue: When user has NSXT managed network it is represented as opaque network and the VM has opaque nic.
Fix: Add opaque network model mapping to inventory
Ref: https://issues.redhat.com/browse/MTV-1695
=> MTV-1695 | Add missing NIC for opaque network

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/migration.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/network.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1211
- https://github.com/kubev2v/forklift/pull/1209
=> Backport to 2.7.5

pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/provider.go
This PR add fetching of the instanceUuid to About model.
=> Fetch Vsphere instanceUuid

pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/network.go
This PR add a support for fetching VlanIDs for the DVPortGroups and standart porgroups.
Jira: https://issues.redhat.com/browse/ECOPROJECT-2359
=> Fetch Vlan IDs

pkg/controller/plan/controller.go, pkg/controller/plan/validation.go, pkg/lib/condition/condition.go
Ref: https://issues.redhat.com/browse/MTV-1458
When selecting "preserve static IP" and migrating a VM without a static IP configuration, then the backend is reporting that the VM was not run. But thi sis incorrect, the VM was run, but it just does not have a static IP configuration (nt inside, and also not repoetred by the VMw API).
Issue:
Currently if a VM does not have static IP, and we set "preserve static IP" the plan is blocked,
Fix:
Changing the condition from "critical" to "warn" will unblock the plan, while still warning the user we may have an issue.
=> MTV-1458 | Make Guest information on vNICs is missing a warning

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
This change exposes the feature flag to retain the CDI importer pods on the controller CR. Disabled by default.
=> Expose FEATURE_RETAIN_PRECOPY_IMPORTER_PODS

pkg/controller/plan/kubevirt.go, pkg/controller/plan/validation.go
The Plan controller will now look for an annotation `forklift.konveyor.io/route` on the NetworkAttachmentDefinition that was specified as the transfer network for the Plan.
The annotation is expected to have a single IP address as its value, which will be set as the default route when configuring the secondary network on the importer pods.
The annotation is optional, but if it is present then the Plan validator will ensure that its value is a valid IP address.
Replaces https://github.com/kubev2v/forklift/pull/1241
=> Look for annotation on NAD to set transfer route

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/migration.go, pkg/settings/migration.go
Issue: When CDI is managing lot of DVs at once it can take some time before the CDI reconciles the DVs status and start the import. In the function `updateCopyProgress` we check the DV status and if it is paused we do continue and as next phase we have snapshot removal. So if the DV is still in paused state and we start the cutover and MTV skips over the phase thinking it already finished as the DV is in paused.
Fix: Add WaitForDataVolumesStatus phase to wait until the DVs do not have the paused status.
Ref: https://issues.redhat.com/browse/MTV-1717
https://github.com/kubev2v/forklift/blob/ea83264881b3dcd4a88dd627c1ca75da2483f408/pkg/controller/plan/migration.go#L1573-L1575
=> MTV-1717 | Wait for DV status to not be paused

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/migration.go, pkg/settings/migration.go
Issue: The migration fails with `Another task is already in progress`. This is caused because of the snapshot creation is started right after snapshot removal and the snapshot removal did not finish due to the consolidation.
Fix: I have added a timeout which users can control using the `controller_snapshot_removal_check_retries` variable. This will wait some time right after snapshot removal. This is just a temporary solution to unblock the users. I'll fix it properly using the VM events and tasks, but that will require a lot of changes in the controller inventory and main.
Ref: https://issues.redhat.com/browse/MTV-1753
=> MTV-1753 | Add wait for snapshot removal timeout

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/migration.go, pkg/settings/migration.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1253
- https://github.com/kubev2v/forklift/pull/1243
=> Backport to 2.7.6

pkg/controller/plan/migration.go
Issue:
This issue is visible with a combination of two problems. The first problem is if there is some step/phase that takes some time to finish and halts the process. An example of such an issue MTV-1775. This causes the VM migration startup to take some time as we don't start all available VMs at once but we add VMs one by one in the reconcile. This in large-scale migration can take a long time. For example on the scale of 200 VMs in best case scenario it would take 10 minutes to start all VMs as we have 3s reconciled.
Fix:
Start all available VMs from the scheduler at once.
Ref: https://issues.redhat.com/browse/MTV-1774
=> MTV-1774 | Start all available VMs from scheduler

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/migration.go, pkg/settings/migration.go
Issue:
When the Forklift creates the snapshot we need to wait for the task to finish. Right now we are using task.WaitForResult, this causes the whole process to wait for the snapshot creation and blocks other VM migrations. Same problem we have with snapshot removal, if the ESXi host is busy and we start the snapshot removal the snapshots can take longer than the reconcile cycle (3s) and we can fail due to it.
Fix:
Instead of using the task.WaitForResult the forklift will start querying for the latest tasks per VM, by default it's 10 tasks. This querying will be done in a separate phase then the creation/deletion. So we will have WaitFor phases for each of the object manipulations. We find the specific task for the creation/deletion and check its status. This has the advantage that we …
=> Move waiting for tasks to separate phase to unblock process

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go
Issue: When creating the VM from vSphere on kubevirt the MTV always
defaulted the secureboot to false.
Fix: Add the secureboot to the inventory and to main controller to pass
it to the KubeVirt.
Ref: https://issues.redhat.com/browse/MTV-1632
Signed-off-by: Martin Necas <mnecas@redhat.com>
=> MTV-1632 | Add secureboot to vsphere

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/migration.go, pkg/settings/migration.go
Revert of:  #1262
Reverting due to deeper testing on larger scale, this solution does not support ha tasks.
`haTask-2330-vim.VirtualMachine.createSnapshot-2994898`
=> Revert: Move waiting for tasks to separate phase to unblock process

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/hook.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/validation.go, pkg/controller/provider/ova-setup.go, pkg/settings/migration.go
Issue:
If the user sets ClusterResourceQuota the Forklift will start failing as it does not have the limits or requests on the pods which are created form the Forklift Controller.
Fix:
Add a new parameters to Forklift operator which can be configured depedning on the user env.
Ref: https://issues.redhat.com/browse/MTV-1493
=> MTV-1493 | Add missing resource limits and requests

pkg/controller/plan/adapter/vsphere/builder.go
Issue: When the VM has a secureboot the migration fails due to missing SSM
Fix: Enable the SMM for UEFI secureboot
https://kubevirt.io/user-guide/compute/virtual_hardware/
Ref: https://issues.redhat.com/browse/MTV-1632
=> MTV-1632 | Enable SMM for the uefi secureboot

operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/apis/forklift/v1beta1/plan/vm.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/adapter/openstack/client.go, pkg/controller/plan/adapter/ova/client.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/hook.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/validation.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/ova-setup.go, pkg/controller/provider/web/vsphere/vm.go, pkg/settings/migration.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1269
- https://github.com/kubev2v/forklift/pull/1268
- https://github.com/kubev2v/forklift/pull/1267
- https://github.com/kubev2v/forklift/pull/1265
- https://github.com/kubev2v/forklift/pull/1260
- https://github.com/kubev2v/forklift/pull/1262
- https://github.com/kubev2v/forklift/pull/1263
=> Backport to 2.7.7

pkg/controller/plan/adapter/vsphere/client.go
Issue:
If the snapshot creation task did not finish the controller fails with NPE. This happens due to the taks not returning the result and we are trying to typcase that result (nil) to the ManagedObject.
Fix:
Add check if the task finished or retry.
=> MTV-1775 | Fix not finished task NPE

docs/enhancements/multidisk-ova.md
In the current release of Forklift it is possible to import OVA appliances
that have been exported from a vSphere environment.  However, all of
an appliance's disks are mapped to the same storage class, and it is
not possible for the end user to indicate that certain disks should be
mapped differently from others. In order to support more use cases, it
should be possible to select map a destination storage class for each
disk of an OVA appliance individually. Forklift does not normally allow
such fine-grained storage mapping because it becomes untenable with a
large number of VMs, but because an OVA plan is expected to involve only
a small number of VMs it should be acceptable.
```yaml
spec:
map:
- destination:
storageClass: fast
source:
id: vm1-disk1
- destination:
storageClass: slow …
```
=> Introduce enhancement for mapping OVA disks

pkg/controller/plan/migration.go
Add precopy loop comment to migration itinerary
=> Add precopy loop comment to migration itinerary

pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator.go, pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
Issue:
When testing ESXi Host connection, we don't take into account the mutation of the secret via the mutation hook.
Fix:
a. use the ESXi provider user and password when testing connection in the admission hook, like the secret will be once it's mutated by the mutation hook.
b. when checking for nil user field, also check for empty string to allow for tooling that sand "" instead of nil.
Images:
Before:
After:
https://github.com/user-attachments/assets/4aa589af-075e-4ec9-a0db-7b3d2375339a
Ref:
https://issues.redhat.com/browse/MTV-1682
=> MTV-1682 | Mutate ESXi secret before testing connection

virt-v2v/cmd/entrypoint.go
Issue:
When migrating VM with luks from vmware the migration fails on the
virt-v2v-inspector step.
Fix:
Add common vmware args to the inspector. This contains the luks key args,
root on which we want to do the conversion etc.
Ref: https://issues.redhat.com/browse/MTV-1864
=> MTV-1864 | Add luks to virt-v2v-inspector

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
Issue:
MTV is importing VMs with the requests.memory field and the memory.guest field set. This is problematic as it prevents memor-overcommit and is causing un-necessary memory pressure on VMs in the worst case leading to OOM sitiations.
Fix:
Remove the requests.memory from the builders
Ref: https://issues.redhat.com/browse/MTV-1866
=> MTV-1866 | Remove the requests.memory from the builder

pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
Issue:
VMs imported from vSphere always have the q35 machine type set. but the machine type is "floating", and thus the VM abi can change between reboots (i.e. update from rhel 8 to rhel9 or 10 on the host side).
Fix:
Remove the q35 machine type.
Ref: https://issues.redhat.com/browse/MTV-1865
=> MTV-1865 | Remove the q35 machine type

pkg/controller/provider/container/vsphere/model.go
Assuming I have matched up the right code correctly, MTV-1610 shows an inventory crash pointing here: https://github.com/kubev2v/forklift/blob/v2.7.2/pkg/controller/provider/container/vsphere/model.go#L660
This pull request just adds a nil check on the DnsConfig field that appears to cause the problem. I have not been able to configure an IP stack without DNS in vSphere, but this is low risk for a speculative fix. It is pretty much copied from the previous fGuestNet case, and I don't see this DnsConfig used anywhere.
=> MTV-1610: Avoid uncommon potential inventory crash.

pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Issue:
When creating the warm migration with luks encrypted disks the migration does not even allow us to create the plan. This is because of the validation hook. But the virt-v2v-in-place supports the `--key` parameter and we are already passing it to it.
Fix:
Remove the warm check in the plan validation.
Ref: https://issues.redhat.com/browse/MTV-1864
=> MTV-1864 | Add luks support to the warm migration

build/virt-v2v/Containerfile-upstream
Issue:
The latest virtio-win drivers in the AppStream is `virtio-win-1.9.15-4.el9.noarch` which is missing the latest windows drivers.
There are some legal problems with the latest drivers getting pushed to the AppStream but they are available in the koji.
Fix:
Add the `virtio-win-1.9.40-1.el9.noarch` to the **upstream** build.
=> Add latest win-virtio to upstream virt-v2v build

pkg/controller/plan/controller.go, pkg/controller/plan/migration.go
Fix for MTV-1929, cleans up most active source connections when they are done with their work.
=> MTV-1929 Clean up unused active source connections.

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Allow users to specify the plan.spec.diskBus which will set it on all disks during the creation.
Possible options 'scsi', 'sata' and 'virtio'.
Ref: https://issues.redhat.com/browse/MTV-1635
=> MTV-1635 | Allow to specify the diskBus

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go
Issue: When migrating a VM with shared disks the virt-v2v transfers all disks that are attached to the VM, that includes the shared disks. But if we will transfer 2 VMs with the same shared disk the disk will be migrated twice. This takes a lot of additional resources.
Fix: There are multiple solutions, which vary in complexity. I have chosen the simplest and fastest solution by adding a new Plan parameter migrateSharedDisks this determines if the shared disks should be migrated. By default, it's set to True as that's the default virt-v2v behaviour. If the toggle is turned off the plan will filter out the shared disks and use KubeVirt CDI for disk transfer and virt-v2v-in-place for the guest conversion.
Usage: The user will create 2 plans, one with only one VM and with the …
=> MTV-1442 | Allow to skip shared disks

pkg/apis/forklift/v1beta1/BUILD.bazel, pkg/controller/plan/adapter/vsphere/BUILD.bazel, pkg/forklift-api/webhooks/validating-webhook/admitters/BUILD.bazel
chore: update bazel deps
Issue:
bazel deps uout of date, release-2.7 does not compile using bazel
Fix:
update bazel deps for release-2.7
running
```bash
make bazel-generate
```
=> chore(bazel): chore-running-bazel-generate

build/forklift-api/Containerfile, build/forklift-controller/Containerfile, build/openstack-populator/Containerfile, build/ova-provider-server/Containerfile, build/ovirt-populator/Containerfile, build/populator-controller/Containerfile, build/virt-v2v/Containerfile
When building with bazel, incremental builds (e.g. after changing just a single source file) were pretty quick. After switching away from bazel, running e.g. `make build-controller-image` would do a full rebuild of the entire source code even if only a single file was touched. To reduce the amount of time that builds take, introduce a cache mount in the
build container. This cache will persist the intermediate build artifacts between container builds so that when a single source file is changed, it will only rebuild that one file and re-use the other object files from previous builds. Set the `$GOCACHE` environment variable to point to this cache mount while building.
=> chore(containers): build: use a cache mount for building

operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/host.go, pkg/controller/provider/container/vsphere/collector.go
Issue:
User can't establish TLS handshake with the vSphere server due to wrong ciphersuite and tls version
Fix:
The user can specify new forklift controller spec:
- `vsphere_tls_ciphers` - needs to follow the cipher suites from https://go.dev/src/crypto/tls/cipher_suites.go
- `vsphere_tls_max_version` - needs to be one of (`1.0`,`1.1`, `1.2`, `1.3`)
Ref: https://issues.redhat.com/browse/MTV-1571
=> MTV-1571 | Allow to customize the TLS config for the govmomi client

cmd/ova-provider-server/ova-provider-server.go
See descriptions on the individual commits. This just makes the ova provider a bit more robust to unexpected inputs.
- **ova: Don't crash on ova files when device is missing 'ElementName'**
- **ova: improve handling of extra devices**
=> Fix crash on unexpected ova files

build/forklift-api/Containerfile, build/forklift-controller/Containerfile, build/openstack-populator/Containerfile, build/ova-provider-server/Containerfile, build/ovirt-populator/Containerfile, build/populator-controller/Containerfile, build/virt-v2v/Containerfile
The syntax "ENV VAR VALUE" is supported but is deprecated, and docker complains about it. The proper syntax is "ENV VAR=VALUE". Switch to that syntax in all Containerfiles.
=> chore(containers): use proper syntax for ENV in Containerfiles

pkg/controller/plan/adapter/vsphere/builder.go
ref:
https://issues.redhat.com/browse/MTV-2049
https://issues.redhat.com/browse/CNV-49381
Issue:
After CNV-49381 was fixed in CNV v4.17.1 we don't need the workaround to set the vTPM in MTV
Fix:
Remove the vTPM setup in MTV workaround
=> MTV-2049 | Don't auto add TPM device if BIOS firmware detected

pkg/controller/plan/migration.go, pkg/controller/plan/validation.go, pkg/controller/plan/vm_name_handler.go, pkg/controller/plan/vm_name_handler_test.go
Issue:
Right now we are not allowing to keep the VM names which have the dots in the name but we replace the dots with dashes.
Fix:
Use the IsDNS1123Subdomain validation instead of IsDNS1123Label and ignore the dots in the replacemnet of the new name.
Ref:
https://issues.redhat.com/browse/MTV-1744
=> MTV-1744 | Allow dots in the VM names

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go
Revert of https://github.com/kubev2v/forklift/pull/1318 for release-2.7
=> Revert shared disks in release-2.7

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/builder_test.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go
Issue: When running a migration of a VM which has various bus controllers the PVs are not populated by correct disk. This causes that some larger disks are in small PVs.
This issue happens due to the libvirt domain-VMware API missmatch. The virt-v2v is outputing the disks in order as they are in the libvirt domain but Forklift is using the order from API and sorting the disks by key. The libvirt is sorted in order of devices SCSI, SATA and IDE wheras sorting by key from VMware API results in order IDE, SATA and SCSI.
Fix: Gather information about the disk busses and sort the disks by SCSI, SATA and IDE. And within each of these categories we sort by the key from lower to higer.
Ref: https://issues.redhat.com/browse/MTV-2093
=> MTV-2093 | Sort the disks by bus

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/builder_test.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go
Issue: When running the migration with preserve static IPs, Forklift does not preserve gateway of a NIC from different subnet.
Fix: Right now we are checking if the gateway is from the subnet as correlation between the nic and networks. We need to start using different correlation. The VMware API is exposing the `device` which is the index of the NICs returned from the API in order.
Ref: https://issues.redhat.com/browse/MTV-2018
=> MTV-2018 | Preserve static gateway from different subnet

docs/enhancements/shared-disks.md, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/plan/adapter/ova/validator.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/utils.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/controller/plan/validation.go, pkg/controller/provider/web/vsphere/vm.go, pkg/lib/condition/condition.go
Issue:
In the current release of Forklift, it is possible to import shared disks using cold migration. This is possible because the virt-v2v is transferring all disks attached to the VM, but because the shared disks are attached to multiple VMs the shared disks get migrated multiple times and users right now, need to delete the extra volumes and reattach the disks.
Fix:
Add a new parameter `migrateSharedDisks` to the plan which will determine if the shared disks should be migrated. This parameter will allow the users to choose if the plan should migrate shared disks or not. When the `migrateSharedDisks` will be enabled the Forklift will use the "normal" cold migration flow using virt-v2v and labelling the shared PVC.
When the `migrateSharedDisks` is disabled the Forklift will use the …
=> MTV-1966 | Allow to skip shared disks

HACKING.md, Makefile
Issue:
`make run`  does not run the controller
Fix:
=> chore(develop): Update makefile run action

docs/enhancements/shared-disks.md, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/validator.go, pkg/controller/plan/adapter/openstack/validator.go, pkg/controller/plan/adapter/ova/validator.go, pkg/controller/plan/adapter/ovirt/validator.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/utils.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/controller/plan/scheduler/vsphere/scheduler.go, pkg/controller/plan/validation.go, pkg/controller/provider/web/vsphere/vm.go, pkg/lib/condition/condition.go
Issue:
In the current release of Forklift it is possible to import shared disks using cold migration. This is possible because the virt-v2v is transferring all disks attached to the VM, but because the shared disks are attached to multiple VMs the shared disks get migrated multiple times and users right now, need to delete the extra volumes and reattach the disks.
Fix:
Add a new parameter `migrateSharedDisks` to the plan which will determine if the shared disks should be migrated. This parameter will allow the users to choose if the plan should migrate shared disks or not. When the `migrateSharedDisks` will be enabled the Forklift will use the "normal" cold migration flow using virt-v2v and labeling the shared PVC.
When the `migrateSharedDisks` will be disabled the Forklift will use the …
=> Backport: MTV-1966 | Allow to skip shared disks

cmd/virt-v2v/entrypoint.go, pkg/apis/forklift/v1beta1/provider.go, pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/builder.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go, pkg/virt-v2v/global/variables.go
Issue:
The scale and perf team found a way how to improve the transfer speeds. Right now the only way to enable this feature is to set the v2v extra vars. The v2v extra vars pass the configuration to the virt-v2v and virt-v2v-in-place. The v2v extra vars configuration is general and not specific for VDDK. This causes the warm migration which uses the virt-v2v-in-place to fail as it does not use any VDDK parameters. Those parameters should be passed to the CNV CDI instead.
Fix:
Add a way to easily enable and configure the AIO.
This feature is VDDK and provider-specific as it requires to have specific vSphere and VDDK versions. So we can't enable this feature globally nor by default. So this PR adds the configuration to the Provider spec settings and create a configmap with the necessary …
=> MTV-1804 | Implement VDDK AIO buffer configuration

pkg/controller/plan/adapter/ocp/builder.go
Prevent forklift-controller panic by adding nil check for vmExport external link and logging an error when missing. Fixes #495.
=> Fix panic in cases where vmExport.Status.Links.External is nil.

pkg/controller/provider/web/vsphere/vm.go
Backport of: https://github.com/kubev2v/forklift/pull/1404 to 2.8
=> Backport 2.8 | MTV-1609 | VM source templates should not be selected in the VM table

pkg/controller/provider/web/openstack/workload.go
err was checked for nil twice. Remove the redundant check.
=> Remove tautological checks

pkg/controller/plan/validation.go
Issue: The shared disk has a warning validation which should not block the migration, but due to bug in the code the migration is blocked even with just warning.
Fix: Becuase we are checking in the migration execution if the validation has a SharedDisk type but we do not check what kind of category it is we block the migration even with the warning. Easy solution is to add new validation type with does not match the blocking.
Ref: https://issues.redhat.com/browse/MTV-2187
=> MTV-2187 | Allow to start migration of shared disk with warning validation

pkg/controller/plan/validation.go
Backport of: https://github.com/kubev2v/forklift/pull/1411 to release-2.8
=> Backport 2.8 | MTV-2187 | Allow to start migration of shared disk with warning validation

pkg/controller/plan/adapter/ocp/client.go, pkg/controller/plan/kubevirt.go
Issue:
1. The field spec.running is deprecated
2. Fix spec.running and spec.runStrategy mutually exclusive scenario during migration
=> MTV-2092 | MTV-2105 | spec.running and spec.runStrategy mutually exclusive and spec.running is deprecated on target VM

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/util/utils.go
Issue:
The Kubevirt VM can not boot from hotpluggable disk with scsi bus. We need to keep the virtio bus for boot disk.
https://issues.redhat.com/browse/VIRTCE-24
Fix: Use virtio for boot disk.
Ref: https://issues.redhat.com/browse/MTV-2199
=> MTV-2199 | Set boot disk to always have Virtio bus

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/utils.go, pkg/controller/plan/adapter/vsphere/validator.go
Issue:
Right now when the user will migrate two VMs with the shared disk and the migrateSharedDisks enabled we do not give warning to the user that the disk will be duplicated. Neither if the PVC is already located in the namepsace.
Fix:
Add extra validation for the VMs to show if there would be some disk duplication.
Ref: https://issues.redhat.com/browse/MTV-1966
=> MTV-1966 | Add extra shared disk validations

pkg/controller/plan/migration.go
Issue: Right now when the user canceles one VM inside the migration the cancel method gets called many times as the other VMs from the plan are still running and the plan is being executed. We should skip the execution of those VMs.
Fix: Check if the VM was marked as completed before executing the cancel method.
Ref: https://issues.redhat.com/browse/MTV-1796
=> MTV-1796 | Cancel VM only once

operator/config/crd/bases/forklift.konveyor.io_networkmaps.yaml, pkg/apis/forklift/v1beta1/mapping.go, pkg/controller/map/network/validation.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-1436
Issue:
Add an option or dropdown while creating migration plan for network mapping to not migrate/ convert that network in destination VM.
Fix:
Add a new destination network type "ignored"
Example:
``` yaml
apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
name: test2-gfz5b
namespace: openshift-mtv
spec:
map:
- destination:
type: ignored   <----------------------------------------------------- New type "ignored"
source:
id: dvportgroup-17762
name: VM Network
type: vsphere
provider:
destination:
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
name: host
namespace: openshift-mtv
uid: ee28d0c2-5db3-4d78-9914-a322c442a6f7
source:
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
name: test2
namespace: openshift-mtv …
```
=> MTV-1436 | Add ignored network type

operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan/vm.go, pkg/controller/plan/migration.go, pkg/controller/plan/validation.go
Ref:
https://issues.redhat.com/browse/MTV-383
Issue:
As a migration owner, when creating a migration plan that has VMs with non-conformant names, I would like the ability to change the name of the target VM on the fly before it is migrated.
Currently:
A vm is getting the target name automatically to be unique within the namesapce and to be valid k8s subdomain.
After:
Users can override the automatic mechanism by providing a TargetName
- If the target name is not valid k8s subdomain, plan validation will fail
- If the target name is not unique, plan validation will fail
Example:
``` bash
kubectl sql "\
select \
name as planName, spec.vms[1].name as origName, spec.vms[1].targetName as targetName, \
status.migration.vms[1].name as migratedVMName \
from openshift-mtv/plans \
where targetName …
```
=> MTV-383 | Allow customization of target vm name

pkg/controller/plan/kubevirt.go
Issue: The default vddk config is populated by
`VixDiskLib.nfcAio.Session.BufSizeIn64K`
expected value is
`VixDiskLib.nfcAio.Session.BufSizeIn64KB`
Fix: Add the missing `B` to the end of the config.
Ref: https://issues.redhat.com/browse/MTV-2218
=> MTV-2218 | Fix the vddk config default

pkg/controller/plan/kubevirt.go
Backport of https://github.com/kubev2v/forklift/pull/1425 to release-2.8
=> Backport 2.8 | MTV-2218 | Fix the vddk config default

pkg/controller/plan/validation.go
Issue: When the user creates a plan with 2 VMs without specifying the `targetName` one of the VMs gets error `Duplicate targetName`.
Fix: This issue is caused by the targetName being equal to empty string.
Ref: https://github.com/kubev2v/forklift/pull/1366
=> Fix targetName validation if empty

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Issue: The virt-v2v converts the guests to work only with the virtio-blk, which includes updating the Linux configurations to match the new device names (vda, vdx...) and for Windows where it edits the boot section to work with the virtio-blk drivers. The aim of the DiskBus parameter was to allow the users to specify the Bus because KubeVirt only allows hotplug disks with the SCSI bus. This issue was moved to the KubeVirt and will be resolved on their end.
Fix: Deprecate the parameter from 2.8
Ref: 
- https://issues.redhat.com/browse/MTV-2199
- https://github.com/kubev2v/forklift/pull/1333
=> MTV-2199 | Deprecate plan.spec.DiskBus parameter

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go, validation/policies/io/konveyor/forklift/vmware/disk_serial_numbers.rego, validation/policies/io/konveyor/forklift/vmware/disk_serial_numbers_test.rego
Address [MTV-1368](https://issues.redhat.com/browse/MTV-1368) as much as possible for VMware VMs, by copying disk serial numbers into the KubeVirt YAML. Only do this when the source VM is configured with a SCSI disk and has the **disk.EnableUUID** configuration parameter set, because that appears to be the only case where serial numbers are actually presented through to the guest.
Also raise an informational validation message on the VM during plan creation so it is clear that the serial number is not going to be completely preserved. It will be truncated to 20 characters for VirtIO disks and there is no longer an option for SCSI, so there is not currently a way for MTV to automatically preserve them completely.
=> MTV-1368 Preserve disk serial numbers from VMware.

pkg/controller/plan/adapter/vsphere/utils.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/validation.go, pkg/lib/condition/condition.go
Issue: The condition is adding by specific type. If we want to have different condition msg to different VMs within the same plan we need to change the type so the condition is not overriden by next condition. This way all VMs in the items list had message of the last VM.
Fix: Add VM specific condition types.
Ref:
- https://issues.redhat.com/browse/MTV-2206
- https://issues.redhat.com/browse/MTV-2207
- https://issues.redhat.com/browse/MTV-2209
=> Fix shared disks validations

operator/roles/forkliftcontroller/templates/controller/controller-scc.yml.j2, pkg/controller/plan/kubevirt.go
Issue: Right now the migration using the quay.io/kubev2v/forklift-virt-v2v:latest fails due to the passt missing permissions. The root cause of this issue is in the passt using the `unshare(2)` syscall. The passt was added to the virt-v2v libguestfs which introduced this issue. The CRI-O is missing the `unshare(2)` from the seccomp settings. We need to specify to use the seccomp which allows the `unshare(2)` syscall and add it to the MTVs SecurityContextConstraints.
Fix: Add the unshare seccomp profile to the guest conversion pod.
Ref: https://issues.redhat.com/browse/MTV-2236
=> MTV-2236 | Use unshare seccomp profile

.github/workflows/build-push-images.yml, build/virt-v2v/Containerfile-upstream-fedora
Issue: The migration of SUSE fails due to the BTRFS. The virt-v2v fails to mount the BTRFS
Fix use Fedora base image which has support of BTRFS.
=> Add Fedora guest conversion build for BTRFS support

build/virt-v2v/Containerfile-upstream, build/virt-v2v/Containerfile-upstream-fedora
Add notes to the virt-v2v Containerfiles that we need to remove the static path of the virtio-win drivers from centos-stream10 and use the available packages. Ref https://issues.redhat.com/browse/RHEL-62961
Add a note about why we don't need to use the `libguestfs-winsupport` in Fedora builds.
=> Add virt-v2v container build notes

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-2257
Issue:
When use pvcNameTemplate: {{.VmName}}-disk-{{.DiskIndex}} during migration,
after the migration the random numbers are added to the end of PVC names
E.g. mtv-function-win2022-test-disk-0pv72h -- {{.DiskIndex}}+random numbers
Fix:
Ensure the PVC template ends with "-" char
Screenshots:
Before:
After:
=> MTV-2257 | Ensure pvc generate name ends with -

cmd/virt-v2v/entrypoint.go
Ref: https://issues.redhat.com/browse/MTV-2171
Issue:
MTV can use '-on' option to change guest name automatically when migrate guests from vsphere provider, but MTV can't use '-on' option to change the guest name when migrate guests from ova provider, so MTV should add the same function of changing guest name to ova provider as vsphere provider 
Fix:
add the "-on" flag to the OVA flow in the virt-v2v pod
Screenshot:
Before fix:
After fix:
=> MTV-2171 | New name in ova flow of virt-v2v pod

cmd/virt-v2v/entrypoint.go
Issue:
The upstream virt-v2v-in-place warm migraiton path fails. Error:
```
Failed to execute virt-v2v command: fork/exec /usr/libexec/virt-v2v-in-place: no such file or directory
```
Fix:
Lets not specify full path of the virt-v2v-in-place.
=> Fix virt-v2v-in-place path for upstream builds

pkg/controller/plan/validation.go
Add extra log error if ocp version validation failed
=> Log error if ocp version validation failed

pkg/controller/plan/adapter/vsphere/validator.go
In VMware it is possible to manually configure the MAC address on a virtual network adatper. This results in a MAC address that can contain upper and/or lower case characters.
This results in the IP address of the VM not being preserved during migration
Fix:
Ensures that the Mac Address comparison is case-insensitive
=> MTV 2285 - Preserve Static IPs fails to match manually configured MAC address on VMware VMs

pkg/controller/plan/adapter/vsphere/validator.go
Reverts kubev2v/forklift#1468
we should store the mac in lowercase in the DB
=> Revert "MTV 2285 - Preserve Static IPs fails to match manually configured MAC address on VMware VMs"

pkg/controller/provider/container/vsphere/model.go
Issue:
In VMware it is possible to manaully configure the MAC address on a virtual network adatper.
This results in a MAC address that can contain upper and/or lower case characters.
It appears the validator matches strings without ignoring case.
This results in the IP address of the VM not being preserved during migration:
Fix:
Ensures that the Mac Address comparison is case-insensitive
Ref: https://issues.redhat.com/browse/MTV-2285
=> MTV-2285 | Mac Address comparison case-insensitive

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/validation.go, pkg/controller/plan/validation_test.go
Ref: https://issues.redhat.com/browse/MTV-2249
Issue:
Currently we validate the pvc, network and volume template using label validation, but we need to use DNS1123Label validation 
FIx:
Replace the label validations with DNS1123Label validations
Tasks:
Screenshot:
After:
=> MTV-2249 | Validate template for k8s spec

pkg/controller/plan/scheduler/vsphere/scheduler.go
Now that the migration runner attempts to schedule as many VMs as it can in a single reconcilation,
it has exposed a bug in the scheduler where canceled VMs are rescheduled endlessly in certain pathological cases, preventing the reconciliation from terminating.
(for instance, if a VM is canceled before it has been marked started, it will always appear ready to schedule although there is nothing for the plan controller to do with it.)
The endless rescheduling causes the controller to infinite loop and be unable to reconcile resources, necessitating that the offending Migration resource be deleted and the controller pod be restarted.
Checking for the `Canceled` condition on the VM is adequate to prevent the problem. (Requesting cancelation of the VM via the Migration resource will cause the …
=> vSphere: ignore canceled VMs when scheduling

.gitleaksignore
Issue: right now getting lot of falce positive reports from the gitleaks
Fix: Ignore the examples/docs which contain a ssh key examples on how to use the hooks etc.
=> Add gitleaksignore

pkg/controller/provider/container/vsphere/collector.go
Issue:
MTV doesn't list any virtual machine which is part of a vApp
Fix:
Modify the traversal specs to include vApps
Ref: https://issues.redhat.com/browse/MTV-1153
=> MTV-1153 |  Add VM's from resource pool to VM's list

pkg/controller/plan/kubevirt.go
Ref: https://issues.redhat.com/browse/MTV-2293
Issue:
Error about "could not find template for destination VM" in forklift-controller pod log
Fix:
Embrace the absence of templates, it's ok
=> MTV-2293 | Missing templates are not an error

pkg/controller/plan/adapter/vsphere/builder.go
Issue:
Building order of data volume is not align with building order of disks
Fix:
Refactor data volume build loop to loop over disks instead of mapping pairs.
Description:
Replace the nested loop with a lookup table, so it will be easier to align the template disk index to the builder disk indexes.
=> MTV-2303 (part) | Refactor data volume build loop

pkg/controller/plan/adapter/base/doc.go, pkg/controller/plan/adapter/ocp/builder.go, pkg/controller/plan/adapter/openstack/builder.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/plan/adapter/ovirt/builder.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migration.go
Issue:
When migrating a VM with disks with different busses the disks are sorted differently on the destination than on the source.
We need to do following sorting: 
- libvirt order -> for the guest conversion
- vmware order -> to persist the device names
Fix:
Sort the disks for guest conversion according to the libvirt and for the VM creation according to vmware.
Ref: https://issues.redhat.com/browse/MTV-2262
=> MTV-2262 | Separate sort by vmware and libvirt

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-2303
Sort disks for pvc template indexing same way as the vm builder
Issue:
We don't sort the disks in the data-volume method same as in map-disks method
Fix:
Sort disks using same helper sort method used by the mapDisks method
=> MTV-2303 | Sort disks for pvc template indexing same way as the vm builder

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-2244
Issue:
When using template to generate the volume name, we may generate a name that is longer the 63 chars
Fix:
Truncate names longer then 63 chars
Notes:
Truncating the name may create none unique volume names, other heuristics for ensuring valid volume names, like fall back to default name, may have their own issues. 
Screenshots:
Before:
After:
Plan with long templates:
=> MTV-2244 | Check length of generated volume name when using plan string templates

pkg/controller/provider/container/vsphere/model.go
Issue:
VM snapshot status in the source provider  isn't being synced upon snapshot deletion.
Fix:
Snapshot casting in the model fails when a nil snapshot object is being updated after deletion. In that case we need to set the snaphot object in the model to nil  which will be reflected in the provider status
Ref: https://issues.redhat.com/browse/MTV-1652
=> MTV-1652 | Need to sync the VM snapshot status with source provider

validation/policies/io/konveyor/forklift/openstack/name.rego, validation/policies/io/konveyor/forklift/ova/name.rego, validation/policies/io/konveyor/forklift/ovirt/name.rego, validation/policies/io/konveyor/forklift/vmware/name.rego
Ref: https://issues.redhat.com/browse/MTV-2309
Issue:
In MTV 2.8.0, the VM name is allowed with dot, but in the "Virtual Machine" page, for VM: "mtv.func.win2022", it's still report: Invalid VM Name, need to update this page 
"Warning concerns 
Invalid VM Name"
Fix:
Update the validation to include dots as valid chars, to match 
For example:
`my.vm` will now be a valid name
Screenshots:
Before:
After:
=> MTV-2309 | Update validate vm name .rego files to include dotes as valid chars

pkg/controller/plan/vm_name_handler.go, pkg/controller/plan/vm_name_handler_test.go
Ref: https://issues.redhat.com/browse/MTV-2308
Issue:
When we auto correct the VM name to conform to DNS1123 domain name, we do not trim multiple dots
Fix:
Trim multiple dots
Screenshots:
Before
After
=> MTV-2308 | VM name should not contain multiple dots

validation/policies/io/konveyor/forklift/openstack/name.rego, validation/policies/io/konveyor/forklift/ova/name.rego, validation/policies/io/konveyor/forklift/ovirt/name.rego, validation/policies/io/konveyor/forklift/vmware/name.rego
Restrict VM name to 64 chars
Issue:
We may use the VM name as source for entities that may require shorted length then K8s subdomain length
Fix:
Restrict the VM name to 63 chars, similar to K8s labels
=> Restrict VM name to 64 chars

validation/policies/io/konveyor/forklift/openstack/name.rego, validation/policies/io/konveyor/forklift/ova/name.rego, validation/policies/io/konveyor/forklift/ovirt/name.rego, validation/policies/io/konveyor/forklift/vmware/name.rego
Fix bad regexp in VM name k8s subdomain regexp
Issue:
While fixing the VM name rego validation ( https://github.com/kubev2v/forklift/pull/1505 ) i allowed the "_" char in the vm name
Fix:
Don't allow the "_" char in VM names
=> Fix bad regexp in vm name k8s subdomain regexp

pkg/controller/plan/adapter/vsphere/builder_test.go
Issue: The CI build test stoped working due to renaming one of the menthods.
Fix: Use correct name
=> Fix CI sort test

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-2356
Safe vm name for templates
Issue:
VM name may include dots, we need to sanitize the vm name before using it in the template.
Fix:
Check length and remove "." from vm name, before using it in the teamples.
Screenshots:
After plan spec:
After plan run:
=> MTV-2356 | Safe vm name for templates

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go
Refs: 
https://issues.redhat.com/browse/MTV-2349
Issue:
PVC name is generated with a HASH suffix to prevent name collisions, some automation requires to set the name verbatim without adding a suffix
Fix:
When users use automation that sets the PVC name, we allow them to take responsibility of the name collision issues, and set the PVC name verbatim.
Screenshot:
Before:
After:
=> MTV-2349 | Add PVCNameTemplateUseGenerateName field to plan

README.md, operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/configmap-controller.yml.j2, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/validation.go, pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go, pkg/settings/migration.go, pkg/settings/settings.go
Ref: https://issues.redhat.com/browse/MTV-2345
Add optional vddk image global settings
Issue:
As a migration administrator I would like to create the VDDK container image automatically and set it as a global settings for all vmWare providers
What happen now:
As a migration administrator I set the vddk image for each new vmware provider
What happen with the fix:
As a migration administrator I create a vddk image using my automation, and set it to be the default image
When creating new vmware provider I can skip setting the vddk image, and migration will fall back into the image I set in the global settings.
Fix:
Why this is safe:
when the configuration is empty, fall back to using providers vddk image or empty
Screenshot:
=> MTV-2345 | Add optional vddk image global settings

operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/apis/forklift/v1beta1/plan/vm.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/validation.go
Ref: https://issues.redhat.com/browse/MTV-2338
Issue:
As a migration owner,
I want customize the PVC names so I can identify shared disks using the PVC name,
so that when I create VMs with shared disks, I can identify the shared PVCs.
Fix:
Add Shared to the pvc template information
example:
```yaml
pvcNameTemplate: '{{if .Shared}}shared-{{end}}{{.VmName}}-{{.DiskIndex}}'
```
Screenshots:
Plan yaml:
Plan running:
=> MTV-2338 | Add Shared to the pvc template information

operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/migration.go
Issue: When migration completes and user decides to delete VM, resources such as PVC and PV are kept in terminating state because guest conversion pod exists. The pod finished, however it is still referencing the PVC used by VM and thus blocking it's deletion. This happens because of kubernetes `pvc-protection` finalizer.
Fix: Add option for users to define if they want to delete the virt-v2v pod after migration succeeds. We do it this way because even when migration succeeds there is no guarantee that the VM will boot. Removing the guest conversion pod every time would make it impossible to troubleshoot this problem using virt-v2v logs.
Ref: https://issues.redhat.com/browse/MTV-1589
=> MTV-1589 | Add option to delete virt-v2v pod

pkg/controller/migration/controller.go
Issue: A nil pointer dereference occurred when error happened inside `setOwnerReference` and migration obj was replaced with nil. Defer function then referenced nil migration obj.
Fix: Don't overwrite migration obj with nil on error and don't execute the `setOwnerReference` function at all when plan is not found.
Ref: https://issues.redhat.com/browse/MTV-2172
=> MTV-2172 | Fix nil ptr dereference

pkg/controller/migration/controller.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/validation.go
Issue:
All the bugs describe certain cenarios where additional manual steps are required to fully delete a plan.
A plan must be archived before deletion to ensure its associated resources are properly cleaned up in the correct order.
Solution
The current plan is now set as an OwnerReference for all of its dependent resources.
This enables Kubernetes automatic garbage collection, ensuring that when the plan is deleted,
all associated resources are also cleaned up without requiring extra steps.
Signed-off-by: ehazan <ehazan@redhat.com>
=> MTV-2054, MTV-2027, MTV-1962 |  Delete plan garbage collection

pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/datastore.go, pkg/controller/provider/web/vsphere/host.go
This PR add a collector for getting a `config.storageDevice.scsiLun` of host and `info.extent` of datastore, so we can pair datastore with host info, where for example vendor is stored. So we can inform the vendor of datastore.
=> Collect additional storage information

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go
Issue:
When a VM from VMware has a Hardware virtualization enabled we are not propagating this to the VM.
Fix:
If VM is using the Hardware virtualization use the CPU host-model and set the CPU feature flags for the nested virt as option, this way the VM can run on both architectures depending on the host.
Ref:
- https://issues.redhat.com/browse/MTV-2157
- https://access.redhat.com/solutions/6692341
- https://issues.redhat.com/browse/CNV-60150
=> MTV-2157 | Enable nested virt on VMs from VMware

.konflux/virt-v2v/redhat.repo, .konflux/virt-v2v/rpms.lock.yaml, build/virt-v2v/Containerfile-downstream
Bumps ubi9 versions from 9.4 to 9.5 in Containerfile for downstream builds.
=> Bump virt-v2v base containers versions

pkg/controller/plan/migration.go, pkg/controller/plan/migrator/base/doc.go, pkg/controller/plan/migrator/base/migrator.go, pkg/controller/plan/migrator/doc.go, pkg/lib/itinerary/simple.go, pkg/lib/itinerary/simple_test.go, tests/suit/utils/provider.go
This commit prepares the way for breaking up the migration runner into provider-specific implementations. Provider specific migrators will now handle the itineraries and progress through the pipeline steps, and eventually provide implementations of the phases. The current pipelines have been moved into a shared BaseMigrator that the migration runner delegates to during calls to `execute()`, though the phase implementations currently remain in the migration runner.
During each call the `execute()` the migration runner will call `ExecutePhase()` on the provider migrator, which will return a value indicating whether it provides the phase implementation. If that value is false, it will fall through to the implementation in the migration runner.
The KubeVirt live migration work will build on …
=> Prepare for provider-specific migrators

pkg/controller/plan/validation.go
Issue: All hook jobs gets deleted beofre they finish and recreated. In the logs I noticed lot of logs deleting the hook jobs with log:
```
Another validation job is active for this plan. Stopping...
```
Fix: This issue is caused by vddk job deletor, we check all jobs related to the migration plan and compare the vddk image hashes. If they are not equal we delete the old job. Beucase the hook jobs are missing the vddk label there is a difference as we compare the empty string to the vddk hash. So the deletor deletes the hook job.
Ref: https://issues.redhat.com/browse/MTV-2421
=> MTV-2421 | Skip deletion for non vddk jobs

pkg/controller/migration/controller.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/validation.go
Reverts kubev2v/forklift#1532
kubernetes doesn't support cross-namespace owner reference
=> Revert "MTV-2054, MTV-2027, MTV-1962 |  Delete plan garbage collection"

pkg/apis/forklift/v1beta1/doc.go, pkg/controller/plan/controller.go, pkg/controller/plan/migration.go, pkg/controller/plan/migrator/base/doc.go, pkg/controller/plan/migrator/base/migrator.go, pkg/controller/plan/validation.go
Goals:
- Reduce duplication by defining constants in a single place that can be imported elsewhere without import cycles.
- Expose constants that make up part of Forklift's API envelope (plan statuses, conditions) in the `api` package.
This could possibly be taken further, but this is a starting point for consideration. Importing from the `api` package and the new names do make the constants slightly harder to read while skimming code, but it avoids error-prone redefinition in multiple packages, and it prevents some confusing situations that currently exist where a vague constant like `Running` is defined in one package for a particular use and imported elsewhere for a conceptually unrelated purpose.
=> Move externally-facing constants to API package

.github/workflows/build-push-images.yml
Issue: The upstream build for the vsphere-xcopy-volume-populator is failing due to the context path not being configured  https://github.com/kubev2v/forklift/actions/runs/14706853156/job/41269190941
=> Add context to github actions

pkg/controller/provider/container/vsphere/cbt_disks_test.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, validation/policies/io/konveyor/forklift/vmware/changed_block_tracking_per_disk.rego, validation/policies/io/konveyor/forklift/vmware/changed_block_tracking_per_disks_test.rego
Issue:
For the warm migration to work, the CBT for individual disks needs to be enabled as well.
In case it's off  the whole disk snapshot will be copied after the cut-over resulting in a prolonged VM downtime.
Fix:
A warning about each disk which its CBT is disabled will be displayed while creating a provider. 
Ref:  https://issues.redhat.com/browse/MTV-2019
=>  MTV-2019 | Warn if CBT not enabled for individual volumes

pkg/controller/provider/container/openstack/collector.go, pkg/controller/provider/container/ova/collector.go, pkg/controller/provider/container/ovirt/collector.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/host.go, pkg/lib/cmd/inventory/main.go, pkg/lib/inventory/container/container.go, pkg/lib/inventory/container/ocp/collector.go
This PR add a collection of `advanedOption` field from `HostSystem` object. This option is only a reference so we store a reference in a database. User can fetch value of `advancedOption` setting from the `/hosts/{id}` endpoint by calling:
```
/providers/vsphere/1/hosts/{id}?advancedOption={optionName}
```
Issue: https://issues.redhat.com/browse/ECOPROJECT-2736
=> Add advancedOption parameter to /hosts/{id} API

Makefile
'xcopy' was 'xcoy'
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
=> build: Fix typo in the 'push-all-images'

cmd/ova-provider-server/ova-provider-server.go, pkg/controller/plan/adapter/ova/builder.go, pkg/controller/provider/container/ova/model.go, pkg/controller/provider/container/ova/resource.go, pkg/controller/provider/model/ova/model.go, pkg/controller/provider/web/ova/vm.go, validation/policies/io/konveyor/forklift/ova/export_source.rego, validation/policies/io/konveyor/forklift/ova/export_source_test.rego
Issue:
Errors in OVA import due to differences in expected OVF formatting, in this case "MegaBytes" as a unit instead of "bytes * 2^20".
Fix:
Address this one unit instance by allowing "MegaBytes" as a resource unit, and add a warning for OVFs that look like they might have been exported from anything other than VMware. 
Ref: https://issues.redhat.com/browse/MTV-2314
=> MTV-2314 | Warn about potentially unsupported OVAs.

pkg/controller/plan/kubevirt.go
Ref:
https://issues.redhat.com/browse/MTV-2075 - use correct vm name in migration status
https://issues.redhat.com/browse/MTV-2076 - add display name
Issue:
When changing the vm name to comply with DNS1123 we unintentionally remove the original name from the migration.
Fix:
Don't change the original name in the migration CR
Screenshots:
Before and After:
Before:
After:
VM annotations:
=> MTV-2075 | Dont override vm original name

pkg/controller/plan/adapter/vsphere/builder.go
This is mainly to allow live migrations in OCP
=> xcopy-populator: Make the populator PVC RWX

.tekton/vsphere-xcopy-volume-populator-dev-preview-pull-request.yaml, .tekton/vsphere-xcopy-volume-populator-dev-preview-push.yaml, build/vsphere-xcopy-volume-populator/Containerfile-downstream
Enable prefetch for vsphere-xcopy-volume-populator downstream image. 
Modify downstream containerfile.
Ref: https://issues.redhat.com/browse/MTV-2271
=> MTV-2271 | Enable prefetch for vsphere xcopy d/s

pkg/controller/provider/web/base/client.go, pkg/controller/validation/policy/client.go, pkg/settings/policy.go, pkg/settings/settings.go
Issue: When running controller locally for development the certificates are usually missing and the main controller can fail to send requests to some existing inventory.
Fix: Skip TLS check when the certs are missing.
=> controller: Skip TLS when missing certs

.konflux/virt-v2v/redhat.repo, .konflux/virt-v2v/rpms.lock.yaml, build/virt-v2v/Containerfile-downstream
As UBI image version changed in https://github.com/kubev2v/forklift/commit/3fbbee4ee2d9948a19a9f3ef30e7f0830994b827 the build of virt-v2v is failing. Fix by updating rpms-lock file.
Ref: https://issues.redhat.com/browse/MTV-2271
=> MTV-2271 | Update virt-v2v rpms-lock file

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go, pkg/virt-v2v/config/variables.go, pkg/virt-v2v/conversion/conversion.go, validation/policies/io/konveyor/forklift/vmware/hostname.rego, validation/policies/io/konveyor/forklift/vmware/hostname_test.rego
Issue:
Inconsistency in the hostname between the source and destination VMs Due to lack of host name in the incventory.
Fix:
Fetching the hostname for each VM and apply that to the destination VM.
Ref: https://issues.redhat.com/browse/MTV-2364
=> MTV-2364 | Inconsistent hostname

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/validator.go, pkg/controller/plan/adapter/vsphere/validator_test.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/container/vsphere/sort_nics_by_guest_network_test.go, pkg/controller/provider/model/vsphere/model.go
MTV-2025 | MTV-1673 | NICs mapping is unordered
MTV-2489 | Update warning message for VM static ip setting Issue:
1. When migrating VMs with multiple NICs the mapping order must match source VM order
2. Display warning when one or more interfaces lack static IP configuration
Fix:
1. Iterate over vm.NICs directly, preserving the original order of network interfaces from the source VM during migration. Previously, networks were generated based on the order of network mappings (netMapIn), which could result in a different NIC order in the target VM.
2. Get warning message when no interface in VM with static ip
Ref: https://issues.redhat.com/browse/MTV-2025
https://issues.redhat.com/browse/MTV-1673
https://issues.redhat.com/browse/MTV-2489
=> MTV-2025 | MTV-1673 | NICs mapping is unordered

.konflux/vsphere-xcopy-volume-populator/README.md, .konflux/vsphere-xcopy-volume-populator/rpms.in.yaml, .konflux/vsphere-xcopy-volume-populator/rpms.lock.yaml, .konflux/vsphere-xcopy-volume-populator/ubi.repo, .tekton/vsphere-xcopy-volume-populator-dev-preview-pull-request.yaml, .tekton/vsphere-xcopy-volume-populator-dev-preview-push.yaml, build/vsphere-xcopy-volume-populator/Containerfile-downstream
Enable konflux hermetic build for vsphere-xcopy-volume-populator downstream image.
- Add rpm prefetch files
- Modify containerfile
- Modify build pipelines
=> MTV-2271 | Enable hermetic build of vsphere-xcopy

operator/.kustomized_manifests, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/kubevirt.go, pkg/controller/plan/migrator/base/migrator.go
Issue: If there is a guest operating system which is not working with the virt-v2v the whole migration fails. This PR adds a way to work around this issue by skipping the guest conversion parts using the plan.spec.skipGuestConversion parameter. This parameter can true or false, defaults to false.
Fix: Skip the guest conversion, this causes a problem that we are right now using the Virtio buses on everything but if we do not install the drivers on the guest, the VM won't boot. I have defaulted to switch to the sata for disk and e1000e for networking.
Ref: [MTV-2315](https://issues.redhat.com/browse/MTV-2315)
=> MTV-2315 | Skip guest conversion

.github/workflows/validate-kustomized-manifests.yaml, Makefile
Adds a make target for QoL, to regenerate .kustomized_manifests file in
operator/ directory.
Change info in kustomized_manifests validation job about how to resolve .kustomized_manifests conflict.
=> QoL for generating .kustomized_manifests

pkg/controller/plan/migration.go
This PR adds a method to the migration runner called `NextPhase()` that will move the VM to the next phase and automatically complete the current pipeline step if the next phase belongs to a different one. It's no longer necessary for the last phase in a step to manually complete it which will allow phases to be reordered and moved between steps more easily.
(Extracted from https://github.com/kubev2v/forklift/pull/1648)
=> Automatically handle Pipeline step transitions when moving to the next phase

build/vsphere-xcopy-volume-populator/Containerfile
This is needed to run the vmkfstools-wrapper test
=> xcopy-populator: Add python to Containerfile

pkg/virt-v2v/customize/customize.go, pkg/virt-v2v/customize/scripts/windows/9999-network-config.ps1.tmpl, pkg/virt-v2v/customize/scripts/windows/9999-restore_config-legacy.ps1
Issue:
As of MTV 2.8.4, support for older drivers enables migration of Windows 2008 R2 guests. However, we encountered a new virt-v2v issue (RHEL-91611) where the `Get-NetAdapter` cmdlet is unavailable on Windows 2008 R2, causing static IP configuration to fail in firstboot scripts. Same as for re-enabling offline drivers script.
Fix:
Adding a  legacy-compatible scripts without relying on modern cmdlets. It ensures static IP preservation and disks re-enablement during migration of Windows 2008 R2 VMs
Ref: https://issues.redhat.com/browse/MTV-2522
=> MTV-2522 |  network config script isn't win-2008 compatible

pkg/controller/base/controller.go, pkg/controller/host/validation.go, pkg/controller/plan/adapter/ovirt/client.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/client.go, pkg/controller/plan/adapter/vsphere/host.go, pkg/controller/provider/container/ovirt/client.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/validation.go, pkg/controller/provider/web/vsphere/vddk.go
Issue:
1. Missing vddk-thumbprint during TLS verification.
2. Connection Failed with VMware Provider with Fetching CA
3. OCP provider created without CA or skip CA remains stuck even after manual fix
Fix:
1. Assigning provider Fingerprint upon successfull TLS verification.
2. Added TLS verification for OCP provider.
Ref: https://issues.redhat.com/browse/MTV-2539
https://issues.redhat.com/browse/MTV-2536
https://issues.redhat.com/browse/MTV-2500
=> MTV-2539 | MTV-2536 | MTV-2500 | Various CA certificate issues

pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/util/utils.go
Issue:
A VMware disk image was set to a number of bytes that did not align to 1MiB, and the imported VM would not start.
Fix:
I have not yet been able to set a disk to such a size in VMware, but a speculative fix is to change the conversion from bytes to MiB in the vSphere builder, which just divides by 0x100000 without rounding up first. With non-aligned size values, this division results in a smaller number, for example: 19000005632 / 0x100000 = 18999148544, vs. rounding up to 19000197120.
Reference:
https://issues.redhat.com/browse/MTV-2524
=> MTV-2524 | Round VMware disk capacity up to next megabyte.

pkg/controller/plan/controller.go, pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Issue:
Deleting a provider with existing related plan causes error when archiving, leading to leftovers if plan is force deleted
Fix:
Allowing archiving dangling plan in the provider hook.
Ref: https://issues.redhat.com/browse/MTV-2501
=> MTV-2501 | Dangling plan

pkg/controller/plan/adapter/vsphere/builder.go
Issue: need one more change for previously merged pull request #1886.
Fix: also align disk size in DataVolume creation request. I still haven't managed to reproduce the original bug, but this probably won't hurt anything.
Ref: https://github.com/kubev2v/forklift/pull/1886
=> MTV-2524 | Round VMware disk capacity up to next megabyte, part 2.

build/virt-v2v/Containerfile-downstream
Isuse:
The warm migraiton fails with
```
Building command:virt-v2v-in-place[-v -x -i libvirtxml --root first /mnt/v2v/input.xml]Failed to execute virt-v2v command exec: "virt-v2v-in-place": executable file not found in $PATH
```
Fix:
Add `ENV PATH="$PATH:/usr/libexec"`
=> Fix downstream v2v image to contain the virt-v2v-in-place

validation/policies/io/konveyor/forklift/vmware/vm_os.rego
Each concern is part of a VM, so, like any other Rego rule, it makes sense not to return the formatted` input.guestId`.
=> fix os assessment description

cmd/vsphere-xcopy-volume-populator/Makefile, cmd/vsphere-xcopy-volume-populator/internal/populator/populate.go, cmd/vsphere-xcopy-volume-populator/internal/populator/remote_esxcli.go, cmd/vsphere-xcopy-volume-populator/internal/populator/vib.go, cmd/vsphere-xcopy-volume-populator/internal/vmware/client.go, cmd/vsphere-xcopy-volume-populator/internal/vmware/mocks/vmware_mock_client.go, cmd/vsphere-xcopy-volume-populator/vmkfstools-wrapper/Makefile, cmd/vsphere-xcopy-volume-populator/vmkfstools-wrapper/create-vib.sh, cmd/vsphere-xcopy-volume-populator/vmkfstools-wrapper/esxcli-vmkfstools.xml, cmd/vsphere-xcopy-volume-populator/vmkfstools-wrapper/version.mk, cmd/vsphere-xcopy-volume-populator/vmkfstools-wrapper/vib-install-playbook.yaml, operator/.kustomized_manifests, operator/config/rbac/forklift-controller_role.yaml, pkg/controller/plan/adapter/vsphere/builder.go
https://issues.redhat.com/browse/ECOPROJECT-3066
Motivation
The VIB is a critical piece of the flow, and it will probably go under
changes as we go. We do have an ansible script to install it, but that
actions is manual. Instead we can try to always look for the vib on the
ESX in context, and check the version, and remediate if necessary. That
way we are always updated and aligned to the populator version.
Modification
With the former fix making the wrapper VIB not needing a restart of
hostd, the installation process becomes quicker and safer.
The populator will fetch the VIB version and compare to the desired
version. If not there it will upload the vib, from the container
filesystem, to the same datastore the VM is on, and then install it,
all through remote ESX commands through the …
=> VIB ensure install

Makefile
Issue:
The build times out
Fix:
Speicfy only needed files to validate
=> Limit golangci-lint to pkg and cmd

pkg/controller/base/controller.go, pkg/controller/host/validation.go, pkg/controller/plan/adapter/vsphere/host.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/validation.go, pkg/lib/util/util.go
Issue:
When Creating esxi provider
Changing migration network from host view under provider, Fails with: "failed to verify certificate: x509: certificate signed by unknown authority"
Fix:
Add un-trusted CA to cert pools in the missing parts we haven't caught so far.
Ref:
https://issues.redhat.com/browse/MTV-2628
=> MTV-2628 | TLS error when changing migration network

build/vsphere-xcopy-volume-populator/Containerfile, build/vsphere-xcopy-volume-populator/Containerfile-downstream, cmd/vsphere-xcopy-volume-populator/Makefile, cmd/vsphere-xcopy-volume-populator/go.mod, cmd/vsphere-xcopy-volume-populator/go.sum, cmd/vsphere-xcopy-volume-populator/internal/populator/storage.go, cmd/vsphere-xcopy-volume-populator/vendor/modules.txt
The build target contains the needed build tags to make sure the VIB
version is injected into the binary
=> xcopy-populator: Use the make 'build' target to build the container

pkg/templateutil/README.md, pkg/templateutil/templateutil.go, pkg/templateutil/templateutil_test.go
Ref:
https://issues.redhat.com/browse/MTV-2403
Issue
Users can't do complex string manipulation action
Fix:
Add `mustRegexReplaceAll` method from `sprig` lib to allow more fine tuned string manipulations 
Part of a fix for MTV-2403 -
Add an option to use more fine tuned string manipulations 
Example:
```
templateText: `disk-{{ mustRegexReplaceAll "([A-Za-z]+):.*" .Input "$1" | lower }}`,
data:         map[string]interface{}{"Input": "C:\\"},
expected:     "disk-c",
```
=> MTV-2403 | Add regexp string manipulation template helper

pkg/controller/plan/validation.go, pkg/controller/plan/validation_test.go
Issue:
Template validation errors are not very helpful
Fix:
Add more information about template validation errors
Examples:
``` bash
14:50 $ oc mtv plan create bad-template-1 -S vmw --vms mtv-func-win2022 --pvc-name-template "pvc-{{ .FileName }}"
No target provider specified, using default OpenShift provider: host
NetworkMap 'bad-template-1-hc77x' created in namespace 'openshift-mtv'
StorageMap 'bad-template-1-f5dzv' created in namespace 'openshift-mtv'
No target namespace specified, using plan namespace: openshift-mtv
Plan 'bad-template-1' created in namespace 'openshift-mtv'
14:51 $ oc mtv plan create bad-template-2 -S vmw --vms mtv-func-win2022 --pvc-name-template "pvc-{{ .fileName }}"
No target provider specified, using default OpenShift provider: host
NetworkMap …
```
=> chore | More verbose template validation errors

pkg/controller/plan/adapter/vsphere/builder.go
AccessMode is required for PVC, and when a
StorageMap.Map[].Destination.AccessMode doesn't specify
what accessMode to set, the migration fails on creating the PVC.
https://issues.redhat.com/browse/ECOPROJECT-3111
=> xcopy-populator: Add PVC accessMode=RWX by default

pkg/controller/provider/validation.go
Issue:
Connection failed when create OCP Provider with "Fetch certificate from URL"
Fix:
The validate connection status was added by mistake to ocp provider as part of a conclustive tls issues fixes.
Ref: https://issues.redhat.com/browse/MTV-2715
=> MTV-2715 | OCP provider failed to create

pkg/controller/plan/adapter/vsphere/builder.go, pkg/virt-v2v/config/variables.go, pkg/virt-v2v/customize/customize.go, pkg/virt-v2v/customize/scripts/windows/9999-preserve_complementry_ips_per_nic.ps1.tmpl
Issue:
Nics with multiple Ip's are not preserved.
Only the primary ip is preserved  from virt-v2v but the rest are droped due to re-assigning of default-gatway .
Fix:
Preserve the complementry IP's seperatly to avoid re-assigning of default-gatway .
Ref:
https://issues.redhat.com/browse/MTV-2471
=> MTV-2471 | Windows-Preserve multiple ip’s per nic

operator/.kustomized_manifests, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/validation.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go, pkg/controller/provider/web/vsphere/vm.go
Ref:
https://issues.redhat.com/browse/MTV-2403
Issue
Users can't use the vmware disk path when creating a PVC name template
Fix:
Add disk path to the vmware pvcnametemplate
Field name is: `{{ .WinDriveLetter }}`
```bash
19:00 $ oc mtv inventory vms vsphere -q "select name, guestName, disks[*].winDriveLetter as drive, guestDisks[*].diskPath as mount where guestName ~= 'Linux 8'"
name                                 guestName                            drive       mount
mtv-rhel8-sanity-ceph-rbd            Red Hat Enterprise Linux 8 (64-bit)  []          []
mtv-rhel8-sanity-nfs                 Red Hat Enterprise Linux 8 (64-bit)  []          []
mtv-rhel8-warm-2disks2nics-nfs-4-19  Red Hat Enterprise Linux 8 (64-bit)  []          [/boot]
mtv-rhel8-sanity                     Red Hat …
```
=> MTV-2403 | Collect guest disk info

Makefile, operator/.downstream_manifests, operator/.kustomized_manifests, operator/.upstream_manifests, operator/config/crd/bases/forklift.konveyor.io_hooks.yaml, operator/config/crd/bases/forklift.konveyor.io_hosts.yaml, operator/config/crd/bases/forklift.konveyor.io_migrations.yaml, operator/config/crd/bases/forklift.konveyor.io_networkmaps.yaml, operator/config/crd/bases/forklift.konveyor.io_openstackvolumepopulators.yaml, operator/config/crd/bases/forklift.konveyor.io_ovirtvolumepopulators.yaml, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, operator/config/crd/bases/forklift.konveyor.io_providers.yaml, operator/config/crd/bases/forklift.konveyor.io_storagemaps.yaml, operator/config/crd/bases/forklift.konveyor.io_vspherexcopyvolumepopulators.yaml
Issue:
controller-gen version must match the go tools used, we build our images using go 1.23
Fix:
Use controller-gen version 0.17.0
=> [chore] Match controller-gen version for go v1.23

build/forklift-operator-bundle/Containerfile-downstream, build/forklift-operator-bundle/images.conf
As we enabled automerge and autorelease of component images for dev-preview, we can use registry images.
=> Replace quay imgs for registry ones

pkg/controller/plan/adapter/vsphere/builder.go
Ref: https://issues.redhat.com/browse/MTV-2014
Issue:
In #1853 we disabled TPM only on BIOS machines, but we need to disable TPM on any machine that does not enable it on the source.
Fix:
Always disable TPM if the the source machine does not have TPM enabled
=> MTV-2014 | Force disable TPM if not enabled on source

pkg/controller/plan/adapter/vsphere/host.go
Issue:
The line `skipVerifying := base.GetInsecureSkipVerifyFlag(r.Secret)`  tests the host secret for the field `insecureSkipVerify`
We currently don't set this field, and so it is always false.
Fix:
Set the `soap.NewClient` to always use insecure connection.
Future fix:
Document and update UI to set the missing  `insecureSkipVerify` field
=> Always use insecure skip verify for ESX hosts

pkg/controller/provider/container/vsphere/model.go, pkg/controller/provider/model/vsphere/model.go
Ref: https://issues.redhat.com/browse/MTV-2403
**Issue:**
In https://github.com/kubev2v/forklift/pull/1974 we used the `Mappings` field in the guest disk info to map the guest info to hw disks.
In the wild  `Mappings` can be `null` preventing us from collecting the guest info data.
**Fix:**
Use guest disk info index, to match to hw disks
**Example of guest disk info with null mappings:**
``` bash
$ govc object.collect -json vm/mtv-func-win2022-uefi  guest.disk
[
{
"Name": "guest.disk",
"Op": "assign",
"Val": {
"GuestDiskInfo": [
{
"DiskPath": "C:\\",
"Capacity": 16404967424,
"FreeSpace": 4105310208,
"FilesystemType": "NTFS",
"Mappings": null
},
{
"DiskPath": "E:\\",
"Capacity": 1054863360,
"FreeSpace": 1037144064,
"FilesystemType": "NTFS",
"Mappings": null
},
{
"DiskPath": "F:\\", …
```
=> MTV-2403 | Augment hw disk information based on guest agent

pkg/controller/map/network/handler/ocp/handler.go, pkg/controller/map/storage/handler/ocp/handler.go, pkg/controller/plan/handler/ocp/handler.go, pkg/controller/watch/handler/watch.go
Since OCP providers no longer provide 'watch' functionality via the inventory web interface, we provide a fake watch implementation that simply drips events into the channel and causes the objects to re-reconcile periodically.
=> Fix "Not implemented" error for ensureWatch in ocp providers

Makefile
The makefile was attempting to set make variables GOOS and GOPATH like
this:
GOOS ?= `go env GOOS`
GOPATH ?= `go env GOPATH`
This resulted in warnings like this:
$ make build-controller-image
Makefile:333: warning: overriding recipe for target '`go'
Makefile:328: warning: ignoring old recipe for target '`go'
Makefile:333: warning: overriding recipe for target 'env'
Makefile:328: warning: ignoring old recipe for target 'env'
Makefile:338: warning: overriding recipe for target '`go'
Makefile:333: warning: ignoring old recipe for target '`go'
Makefile:338: warning: overriding recipe for target 'env'
Makefile:333: warning: ignoring old recipe for target 'env'
Makefile:550: warning: overriding recipe for target '`go'
Makefile:338: warning: ignoring old recipe for target '`go'
Makefile:550: …
=> Silence 'overriding recipe' warnings in makefile

pkg/controller/plan/controller.go, pkg/controller/plan/scheduler/vsphere/scheduler.go
Issue:
Reconciliation of every plan randomly fails if there is a plan that's referring to an inexistent VM
Fix:
1. Set deleted VM status as canceled and propagate it up.
2. Ignore canceled VM's during plans schedule builder.
Ref: https://issues.redhat.com/browse/MTV-2774
=> VM-2774 | Deleted VM causes entire plans reconciliations to fail

pkg/controller/provider/container/openstack/collector.go, pkg/controller/provider/container/ova/collector.go, pkg/controller/provider/container/ovirt/collector.go, pkg/controller/provider/container/vsphere/collector.go, pkg/controller/provider/validation.go, pkg/controller/provider/web/ocp/base.go, pkg/lib/cmd/inventory/main.go, pkg/lib/inventory/container/container.go, pkg/lib/inventory/container/ocp/collector.go
When creating a new ocp provider, if it is not configured correctly, it would
often get stuck in 'staging' state and never give the user any indication of
why wasn't working. This patch series attempts to improve the situation and
make the problem more debuggable to a user.
The first patch implements an actual connection test for ocp providers which
didnt' exist before and should allow the user to catch a lot of configuration
errors early.
The second patch may not be necessary since the first patch may be sufficient.
But it keeps a map of errors that were encountered during inventory requests and
provides an interface for the provider reconciler to get that information and
use it to report Conditions on the provider object.
Fixes: https://issues.redhat.com/browse/MTV-2447
=> Improve error reporting for ocp providers

pkg/controller/plan/adapter/ova/validator.go
Issue:
migration OVA plan for a VM that has two network cards (NICs). The issue is, both of these source NICs are incorrectly mapped to the same pod network, yet the plan still shows a "ready" status, even though this misconfiguration isn't reflected in the YAML.
Fix:
Compare nic's network (instead of name) to network's name.
Ref: https://issues.redhat.com/browse/MTV-2760
=> MTV-2760 | Dual NICs Mapped to Pod Network Show "Ready" Status.

pkg/virt-v2v/customize/scripts/windows/9999-remove_duplicate_persistent_routes.ps1
Issue:
Regression - default gateway settings are missing after a cold migration with preserve static ip.
The root cause is  the duplication routes being deleted. The remove duplications flow is:
1. Deletes all duplicates . 2.Tries to re-add the route using New-NetRoute.
3. If that fails, it falls back to the "route" command
If re-adding a route fails silently, the gateway route is simply gone, leading to:
1. No default gateway showing. 2.No connectivity despite a configured IP.
Fix:
Add InterfaceIndex to "route" command .
This removes all ambiguity and ensures:
1. The correct interface gets the route.
2. You avoid silent misrouting or ignored routes. 3.The default gateway is reliably assigned, even during early boot or interface flapping.
Ref: https://issues.redhat.com/browse/MTV-2849
=> MTV-2849 | Need to keep the default gateway setting after migration

.gitignore, .tekton/forklift-api-dev-preview-pull-request.yaml, .tekton/forklift-api-dev-preview-push.yaml, .tekton/forklift-controller-dev-preview-pull-request.yaml, .tekton/forklift-controller-dev-preview-push.yaml, .tekton/forklift-operator-bundle-dev-preview-pull-request.yaml, .tekton/forklift-operator-bundle-dev-preview-push.yaml, .tekton/forklift-operator-dev-preview-pull-request.yaml, .tekton/forklift-operator-dev-preview-push.yaml, .tekton/forklift-operator-virt-v2v-btrfs-comp-pull-request.yaml, .tekton/forklift-operator-virt-v2v-btrfs-comp-push.yaml, .tekton/openstack-populator-dev-preview-pull-request.yaml, .tekton/openstack-populator-dev-preview-push.yaml, .tekton/ova-provider-server-dev-preview-pull-request.yaml, .tekton/ova-provider-server-dev-preview-push.yaml, .tekton/ovirt-populator-dev-preview-pull-request.yaml, .tekton/ovirt-populator-dev-preview-push.yaml, .tekton/populator-controller-dev-preview-pull-request.yaml, .tekton/populator-controller-dev-preview-push.yaml, .tekton/validation-dev-preview-pull-request.yaml, .tekton/validation-dev-preview-push.yaml, .tekton/virt-v2v-dev-preview-pull-request.yaml, .tekton/virt-v2v-dev-preview-push.yaml, .tekton/vsphere-xcopy-volume-populator-dev-preview-pull-request.yaml, .tekton/vsphere-xcopy-volume-populator-dev-preview-push.yaml, renovate.json
Updating `renovate.json` in line with what is described in the the issue.
Ref: https://issues.redhat.com/browse/MTV-2922
=> MTV-2922 | Fix konflux nudges in release-x.y branches

build/virt-v2v/Containerfile, build/virt-v2v/Containerfile-downstream, build/virt-v2v/Containerfile-downstream-fssupport, build/virt-v2v/Containerfile-upstream, build/virt-v2v/Containerfile-upstream-fedora, build/virt-v2v/Containerfile-upstream-fssupport
This should *never* be used.  It causes libguestfs to use an untested code path.  It also stops libvirt from containerizing the qemu subprocess, reducing security.
Wherever this is seen, it should be removed.  If doing so causes a problem (which is unlikely as it puts us back on the tested code path) then file a detailed bug about the problem, but do not reintroduce the environment variable.
=> build: Remove LIBGUESTFS_BACKEND=direct everywhere

operator/roles/forkliftcontroller/defaults/main.yml, operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/uuid_to_vmware_serial.go, pkg/controller/plan/adapter/vsphere/uuid_to_vmware_serial_test.go, pkg/settings/features.go
Ref: https://issues.redhat.com/browse/CNV-64582
CNV PR: https://github.com/kubevirt/kubevirt/pull/15118 - merged and backported
**Issue**:
On VMWare clusters the VM serial number is set using VMWare specific format,
We currently use VMWare API to get the system UUID.
**Fix**:
On systems that require using the original VMWare system serial verbatim from VMWare env, we can use the UUID to reconstruct the original VMWare system serial 
**For future updates:**
Currently we mutate the system serial to pass Kubevirt verifiaction.
In future when all supported kubevirt deployments will support spaces in the system serail
we can drop the feature flag and always set the formatted system serial
On kubevirt that do not support this feature we will get an error:
```bash
yzamir@fedora:~$ oc get plan …
```
=> CNV-64582 | Add a feature flag to format vmware system serial

build/virt-v2v/Containerfile-downstream-fssupport
See individual commit messages for description.
I was only partially able to test this. Download worked (which is the main point of the change), but installation failed because of some broken dependencies.
=> build: virt-v2v: Simplify package download

build/virt-v2v/Containerfile, build/virt-v2v/Containerfile-downstream, build/virt-v2v/Containerfile-downstream-fssupport, build/virt-v2v/Containerfile-upstream, build/virt-v2v/Containerfile-upstream-fedora, build/virt-v2v/Containerfile-upstream-fssupport
The appliance build failed when we tried to use libvirt because of this libvirt bug: https://issues.redhat.com/browse/RHEL-104684
To temporarily work around this, use LIBGUESTFS_BACKEND=direct to run libguestfs-make-fixed-appliance.  We can revert this patch when the libvirt bug is fixed.
Thanks: Martin Necas
Updates: commit 96036cd9d2a77c4cf6d77ded358356b08b5f6218
=> build: virt-v2v: Use LIBGUESTFS_BACKEND=direct temporarily

operator/.downstream_manifests, operator/.kustomized_manifests, operator/.upstream_manifests, operator/config/crd/bases/forklift.konveyor.io_plans.yaml, pkg/apis/forklift/v1beta1/plan.go, pkg/controller/plan/adapter/vsphere/builder.go, pkg/controller/plan/adapter/vsphere/utils.go
**Issue:**
Right now when users migrate the VMs with Raw Copy Mode the VM will always have compatibility mode bus (SATA, E1000E, USB) even if the VM already has the virtio drivers installed before migration. MTV should add an option to use the virtio drivers with Raw Copy mode.
**Fix:**
useCompatibilityMode controls whether to use VirtIO devices when skipGuestConversion is true (Raw Copy mode).
This setting has no effect when skipGuestConversion is false (V2V Conversion always uses VirtIO).
- true (default): Use compatibility devices (SATA bus, E1000E NIC) to ensure bootability
- false: Use high-performance VirtIO devices (requires VirtIO drivers already installed in source VM)
Ref: https://issues.redhat.com/browse/MTV-3009
=> MTV-3009 | Add option to disable compatibility mode bus when using RCM

pkg/controller/provider/web/ocp/client.go
Issue:
OCP->OCP migrate VM with Pre/Post migration hooks, plan failed in Initialize phase, with the error below:
"invalid resource name "namespace/vm-name": [may not contain '/'], meaning that vm name was concatenated from    namespace and vm-name with / which is illegal.
Fix:
keep the vm-name as is.
Ref: https://issues.redhat.com/browse/MTV-2894
=> MTV-2894 | OCP->OCP migrate VM with Pre/Post migration hooks, plan failed in Initialize phase.

pkg/controller/plan/adapter/vsphere/host.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator.go, pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator_test.go
Ref: https://issues.redhat.com/browse/MTV-2802
**Issue:**
In https://github.com/kubev2v/forklift/pull/2073 we "hot fixed" the missing host secret field by forcing insecure skip verify to true.
**Fix:**
- Revert #2073
- Add a secret mutation hook to set the missing `insecureSkipVerify` field in the host secret based on provider settings.
**Concerns:**
- skip verify settings may be different for the vCenter and the ESXi.
- a ca cert that works for vCenter may not work for the ESXi , causing TLS error.
**Notes:**
- users can set skip verify flag in host secret manually, overriding copy from vCenter secret
- users can set `cacert` field in host secret to use custom cacert for the ESXi host
**How to tests:**
_Scenario I: host secret without skip flag, copy from provider_
a. create a vCenter …
=> MTV-2802 | Mutate host secret add skip verify flag

cmd/vsphere-xcopy-volume-populator/internal/pure/flashArray.go
- **MTV-3183 | Fix Pure FlashArray naa handling**
https://issues.redhat.com/browse/MTV-3183
=> bp mtv 3183 fix naa for pure

pkg/controller/provider/controller.go, pkg/controller/provider/validation.go
This patch resolves two related problems. The first is that a connection failure due to certificate or token expiration can go unnoticed because the connection test is only run when a provider is reconciled. This is resolved by adding a requeue with a 30-second timer to the provider reconcile loop. The second is that accumulated runtime errors can trap the provider is a failed state after the cause of the connection failure is resolved:
PR #2097 introduced a check for inventory runtime errors during the validation step in the Provider controller reconciliation loop. Runtime errors are accumulated when the inventory API endpoints fail, and the intention is to surface those errors in the Provider CR status. Unfortunately, this does not work as intended.
The connection test for OCP providers …
=> Fix hanging provider caused by runtime error check

pkg/controller/plan/adapter/vsphere/builder.go
Use default AccessMode ReadWriteMany if not set in the StorageMap
=> MTV 3204 | xcopy-populator: make sure accessMode has a default RWX (Backport of #2172)

build/ovirt-populator/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for ovirt-populator-2-8

build/ova-provider-server/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for ova-provider-server-2-8

build/forklift-operator/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for forklift-operator-2-8

build/validation/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for validation-2-8

build/openstack-populator/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for openstack-populator-dev-preview

build/virt-v2v/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for virt-v2v-2-8

build/forklift-operator-bundle/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for forklift-operator-bundle-dev-preview

build/ova-provider-server/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for ova-provider-server-dev-preview

build/validation/Containerfile-downstream, build/virt-v2v/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for virt-v2v-dev-preview

build/ovirt-populator/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for ovirt-populator-2-9

build/forklift-api/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for forklift-api-2-9

build/forklift-controller/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for forklift-controller-2-9

build/openstack-populator/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for openstack-populator-2-9

build/populator-controller/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for populator-controller-2-9

build/forklift-api/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for forklift-api-2-8

build/validation/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for validation-2-9

build/virt-v2v/Containerfile-downstream
=> chore(KONFLUX-6210): fix and set name and cpe label for virt-v2v-2-9
