kubev2v/forklift

- pkg/controller/provider/container/ovirt/client.go
- pkg/controller/provider/container/ovirt/collector.go
This would make the client usable with setups that have keycloak enabled, and is the standard way to access the API.
Since we cannot rely on the "exp" field return from oVirt, the current approach refreshes the client every 30 minutes (default session timeout) by requesting a new token or when the token is expired (in the event it doesn't use the default Long.MAX_VALUE).
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>
> ovirt: use access token with raw http client

- pkg/controller/plan/adapter/ovirt/client.go
add missing [PR](https://github.com/kubev2v/forklift-controller/pull/466)
> ovirt: use kvpair when creating error messages

- README.md
Adding to the readme the necassary dependencies we need to install.
> Add bazel requirements

- README.md
- Fix the broken 'CI' and 'Code Coverage' badges
- Add a new badge for the 'Build and push images' action
> Update badges on the Readme page

- WORKSPACE
- go.mod
- go.sum
- vendor/modules.txt
It is needed for building the virt-v2v image.
> Add github.com/xi2/xz as a dependency

- hack/release-images.sh
- hack/rpm-deps.sh
stops the execution of a script if a command or pipeline has an error
Signed-off-by: Evgeny Slutsky <eslutsky@redhat.com>
> forklift release script, avoid false positive builds.

- docs/forklift-2.4-conversion-wokflow.svg
- docs/use-of-virt-v2v-in-forklift.md
> docs: Document plans for use of virt-v2v in Forklift 2.4

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
This change switch the phasing of the migration. The disk will be created and transferred before posting the VM. Then, the VM will be posted with the relevant PVC.
> Create disks before posting the VM

- Makefile
- pkg/forklift-api/webhooks/webhooks.go
Adding push targets for forklift-operator and the upcoming forklift-api pod
This PR also includes minor changes in the code of forklift-api
> Add more push targets to the Makefile

- .github/workflows/pull-request.yml
See https://github.com/kubev2v/forkliftci/pull/47
> Propagate GITHUB_TOKEN to forkliftci

- pkg/controller/map/storage/handler/doc.go
- pkg/controller/map/storage/handler/openstack/BUILD.bazel
- pkg/controller/map/storage/handler/openstack/doc.go
- pkg/controller/map/storage/handler/openstack/handler.go
- pkg/controller/provider/web/client.go
- pkg/controller/provider/web/openstack/client.go
Network mapping handler is currently missing
> openstack: add placeholders for mapping

- pkg/controller/host/handler/BUILD.bazel
- pkg/controller/host/handler/doc.go
- pkg/controller/host/handler/openstack/BUILD.bazel
- pkg/controller/host/handler/openstack/doc.go
- pkg/controller/host/handler/openstack/handler.go
- pkg/controller/map/network/handler/doc.go
- pkg/controller/map/network/handler/openstack/BUILD.bazel
- pkg/controller/map/network/handler/openstack/doc.go
- pkg/controller/map/network/handler/openstack/handler.go
- pkg/controller/plan/adapter/BUILD.bazel
- pkg/controller/plan/adapter/doc.go
- pkg/controller/plan/adapter/openstack/BUILD.bazel
- pkg/controller/plan/adapter/openstack/adapter.go
- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/adapter/openstack/validator.go
- pkg/controller/plan/handler/BUILD.bazel
- pkg/controller/plan/handler/doc.go
- pkg/controller/plan/handler/openstack/BUILD.bazel
- pkg/controller/plan/handler/openstack/doc.go
- pkg/controller/plan/handler/openstack/handler.go
- pkg/controller/plan/scheduler/BUILD.bazel
- pkg/controller/plan/scheduler/doc.go
- pkg/controller/plan/scheduler/openstack/BUILD.bazel
- pkg/controller/plan/scheduler/openstack/scheduler.go
- pkg/controller/provider/container/openstack/client.go
- pkg/controller/provider/container/openstack/collector.go
- pkg/controller/provider/container/openstack/model.go
- pkg/controller/provider/container/openstack/resource.go
This PR is a checkpoint as a plan can currently be added and reconciled without crashing
> openstack: development checkpoint 

- .github/workflows/pull-request.yml
See https://github.com/kubev2v/forkliftci/pull/56
> Consume forkliftci outputs (cluster and token)

- .github/workflows/pull-request.yml
- Makefile
this pr include commits from https://github.com/kubev2v/forklift/pull/129 , plus commit  testing executing several concurrent jobs using gh-action matrix.
> gh-action  concurrent providers matrix test

- BUILD.bazel
- hack/release-images.sh
> Fix the populator controller image push

- pkg/controller/provider/container/openstack/client.go
- pkg/controller/provider/web/openstack/project.go
- Fix region method for the openstack client
- Use correct variable name.
> openstack fix region method

- Makefile
> Fix makefile syntax error

- cmd/ovirt-populator/ovirt-populator.go
- pkg/forklift-api/webhooks/mutating-webhook/mutators/ovirt-cert-mutator.go
This PR adds an option to support an insecure migration from RHV.
When enabled from the UI, the user will not be required to provide a CA cert at the provided adding stage,  and the disk transfer will instead be held in an insecure flow. 
> Adding insecure migration from RHV

- pkg/controller/provider/container/openstack/client.go
- pkg/controller/provider/web/openstack/BUILD.bazel
- pkg/controller/provider/web/openstack/base.go
- pkg/controller/provider/web/openstack/doc.go
- pkg/controller/provider/web/openstack/tree.go
Implement the "tree/project" endpoint showing
the list of projects with their associated VMs
in a tree like view
> Implement the tree endpoint

- pkg/forklift-api/webhooks/mutating-webhook/mutators/ovirt-cert-mutator.go
The following issues were fixed in this PR:
1. When adding a new provider, if the empty line at the end of the given certificate is deleted, the webhook gets an error, this fix checks that and adds a new line if necessary between the certificates.
2. When providing two CA certs in the provider adding window, if the lines count of the given engine CA differs from the retrieved engine CA (even if they are identical), the webhook thinks the certs are different and adds a redundant third cert in the secret, this PR fixes that. 
> Fixing mutating webhook issues

- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/kubevirt.go
> Cleanup in creation of secret for data transfers

- pkg/controller/plan/kubevirt.go
This addresses the following error when volume-mode is not specified within the storage profile:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x207aadc]
goroutine 678 [running]:
github.com/konveyor/forklift-controller/pkg/controller/plan.(*KubeVirt).getStorageProfileModes(0xc000ef7558, {0xc000c8a1ab, 0x3})
/remote-source/app/pkg/controller/plan/kubevirt.go:703 +0x39c
github.com/konveyor/forklift-controller/pkg/controller/plan.(*KubeVirt).createVolumesForOvirt(0xc000ef7558, {{0xc0007917a0, 0x24}, {0xc000c1f170, 0x10}, {0x0, 0x0}})
/remote-source/app/pkg/controller/plan/kubevirt.go:625 +0x3a5
github.com/konveyor/forklift-controller/pkg/controller/plan.(*Migration).execute(0xc000ef7540, 0xc0001e4540) …
```
> Handle the case volumeMode is omitted from StorageProfile

- pkg/controller/plan/kubevirt.go
When importing a VM from vSphere and the storage class is set with binding mode "wait for consumer" the migration gets stuck, as the PVC and DV will wait for consumer.
This patch solves it by creating a dummy pod to initiate the PVC. It continues PR #209.
> Create a consumer for PVCs for vsphere

- operator/README.md
- operator/config/manifests/bases/forklift-operator.clusterserviceversion.yaml
Backport of https://github.com/kubev2v/forklift/pull/218 to release-v2.4.0
> Backport: operator: Add 2.4 support infomation 

- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/provider/web/openstack/image.go
> openstack: add size field to image inventory

- pkg/controller/plan/kubevirt.go
The v2v container needs security context in order to run in restricted namespaces.
> Set security context to v2v

- pkg/controller/plan/kubevirt.go
The v2v container needs security context in order to run in restricted namespaces.
> Set security context to v2v (backport)

- pkg/controller/plan/adapter/vsphere/builder.go
When there is only a stand-alone host without cluster in the VMware environment VSphere creates a special Cluster resource with the same name in the hierarchy. This leads to duplicated last component in the path to the host resource e.g.: `/DC/my-host.example.com/my-host.example.com`. This confuses libvirt and/or VMware API. To get a proper path and avoid the duplicated last component we need to look at the path of the (artificial) cluster resource instead.
> controller: vsphere: Use parent path for hosts without cluster

- pkg/controller/plan/adapter/vsphere/builder.go
When there is only a stand-alone host without cluster in the VMware environment VSphere creates a special Cluster resource with the same name in the hierarchy. This leads to duplicated last component in the path to the host resource e.g.:
`/DC/my-host.example.com/my-host.example.com`. This confuses libvirt and/or VMware API. To get a proper path and avoid the duplicated last component we need to look at the path of the (artificial) cluster resource instead.
> controller: vsphere: Use parent path for hosts without cluster (backport)

- operator/roles/forkliftcontroller/tasks/main.yml
> Backport: operator: Fix console_plugins list in case there are no other plugins

- pkg/controller/plan/adapter/ovirt/builder.go
When running an import with CDI, the PVC is not named based on the source input. In that case we need to use the generated name of the PVC to be claimed by the VM. This relevant for non volume populator imports such as warm imports and imports to remote clusters.
> Attach the right PVC in different flows (backport)

- pkg/controller/plan/adapter/openstack/client.go
Use the REST resource type when looking up a resource in the inventory, otherwise lookup will fail 
Fix #281
> openstack: use the REST resource for lookup when finalizing

- pkg/controller/plan/adapter/openstack/builder.go
- openstack: fix graphics device mapping
> backport openstack graphics device mapping

- pkg/controller/plan/migration.go
Reduce code repetition a little bit
> Unify oVirt and OpenStack progress updates

- pkg/controller/plan/adapter/openstack/builder.go
- Fix the retrieval of vCPU topology and multi-queue properties from the Image.
- Prefer the Image properties over the Flavor extra specs.
Fixes #300 , Fixes #303
> openstack: fix image properties mappings and precedence 

- pkg/controller/provider/container/openstack/collector.go
- pkg/controller/provider/container/openstack/model.go
- pkg/controller/provider/container/openstack/resource.go
- openstack: make sure VMs are synchronized
- openstack: modify misleading log message
Fixes #302
> openstack fix vm sync

- pkg/controller/provider/container/openstack/model.go
The changes make the code a bit shorter and, arguably, more expressive
> opinionated cleanup in Openstack's VMAdapter#GetUpdates

- operator/config/manager/manager.yaml
- operator/config/prometheus/monitor.yaml
- operator/config/rbac/authproxy/service.yaml
- operator/roles/forkliftcontroller/templates/controller/configmap-controller.yml.j2
- operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
- operator/roles/forkliftcontroller/templates/controller/route-inventory.yml.j2
- operator/roles/forkliftcontroller/templates/controller/service-inventory.yml.j2
Backport of https://github.com/kubev2v/forklift/pull/313
> Backport: Operator: Use original control-plane name 

- virt-v2v/cold/WORKSPACE
A new image present while the older isn't.
> Bump the centos9 image

- pkg/controller/plan/adapter/openstack/builder.go
> openstack add missing constants (backport)

- pkg/controller/plan/kubevirt.go
> Use patch instead of update to set PVC owner references (backport)

- pkg/controller/plan/adapter/openstack/builder.go
> openstack: error handling for snapshots and volumes (backport)

- pkg/controller/plan/adapter/openstack/builder.go
> openstack: fix image properties mappings and precedence (backport)

- pkg/controller/plan/kubevirt.go
Fixes: https://github.com/kubev2v/forklift/issues/333
> Fix the pvc update with remote migration

- pkg/controller/provider/container/openstack/client.go
Support the application credentials and token authentication types.
To choose one of the new authentication types a new field `authType`
is expected in the secret (defaults to `password` if not specified),
which can have one of the supported authentication types:
- password
- token
- v3password
- v3token
- v3applicationcredential
When choosing the application credentials authentication type
(`v3applicationcredentials`) three new secret fields are available:
- applicationCredentialID
- applicationCredentialName
- applicationCredentialSecret
One of `applicationCredentialID` or `applicationCredentialName`
is required alongside `applicationCredentialSecret`.
If `applicationCredentialName` is used it's also mandatory to
specify the `username` and `userDomainName` fields.
The application …
> openstack: support new authentication types

- pkg/controller/provider/container/openstack/client.go
- pkg/controller/provider/container/openstack/collector.go
- openstack: rename function
- openstack: support unversioned authentication types
- openstack: configure TLS for https only
- openstack: allow to configure the endpoint interface
- openstack: make sure the TLS configuration is applied.
- openstack: make less connections to openstack
> openstack: fix insecure connections

- pkg/controller/provider/container/openstack/client.go
Wrap client errors to provide more context
and facilitate issue troubleshooting.
> openstack: wrap client errors

- Makefile
- operator/config/default/kustomization.yaml
- Fix install and deploy targets
- Improve Makefile readability
- Rename deprecated field name
> fix makefile install and deploy targets

- operator/roles/forkliftcontroller/templates/api/deployment-forklift-api.yml.j2
- pkg/controller/plan/adapter/vsphere/builder.go
- Fix typo: partent -> parent
- Removed unused environment variables for forklift-api (PORT, API_TLS_ENABLED)
> Minor cleanup

- pkg/controller/plan/adapter/vsphere/builder.go
When there is a Host resource for the ESXi host on which the converted VM is located we use the `esx://` transport when running virt-v2v. The Host resource is normally created when migration network is configured in UI for the provider. There is not switch or option whether to use `vpx://` or `esx://` and the choice is based solely on the existence of the Host resource. This mimics the behavior that exists with CDI.
This also fixes a bug with EL9 image. When user configured migration network, e.g. to be used for warm migrations with CDI, this prevented any cold migrations because we passed wrong credentials in conversion pod secret and no thumbprint.
> Use ESX transport for EL9 image when Host resource exists

- operator/config/rbac/api/role.yaml
- operator/roles/forkliftcontroller/templates/api/validatingwebhookconfiguration-forklift-api.yml.j2
- pkg/forklift-api/webhooks/util/util.go
- pkg/forklift-api/webhooks/validating-webhook.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/BUILD.bazel
- pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go
- pkg/forklift-api/webhooks/webhooks.go
Necessary refactoring is performed, extended Plan validation and added Provider validation.
> Vddk admission webhook

- .github/workflows/pull-request.yml
- tests/suit/forklift_test.go
- tests/suit/framework/ovirt.go
- tests/suit/ovirt_test.go
- tests/suit/tests_suite_test.go
Adding new VM in fakeovirt for the insecure test in this commit https://github.com/kubev2v/fakeovirt/pull/10
> Add test for ovirt insecure connection

- pkg/controller/provider/container/openstack/client.go
Dont fall back to system-CA cert pool.
> openstack fail early if the root CA is malformed

- .github/workflows/pull-request.yml
switch to  composite actions,  avoid code duplication in gh-actions.
> transition pull-request to composite shared actions from CI

- pkg/forklift-api/webhooks/mutating-webhook/mutators/plan-mutator.go
- tests/suit/forklift_test.go
When creating a new plan, the controller doesn't need to set the populator
labels because it's a new plan (not from previous versions). The webhook
will set the annotation to prevent the logic of setting the labels.
#366
> Webhook: set the annotation regarding populator labels on new plans

- Makefile
- pkg/controller/plan/adapter/ovirt/BUILD.bazel
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/migration.go
- tests/suit/framework/BUILD.bazel
- tests/suit/framework/framework.go
- tests/suit/framework/ovirt.go
- tests/suit/ovirt_test.go
- tests/suit/utils/migration.go
- fix for https://issues.redhat.com/browse/MTV-596: https://github.com/kubev2v/forklift/commit/bbdb7bd05109a2ddf2d6ddecc6b179f4eba1b862
- fix for https://issues.redhat.com/browse/MTV-597: https://github.com/kubev2v/forklift/pull/352/commits/27f854127776913eba6ece9f336c66ddc398a6b6
- improve logging related to snapshots: https://github.com/kubev2v/forklift/commit/4026ac85a9135db6ae6d1e475cadfaf0b0172d23
> Backports to v2.4.2

- pkg/controller/plan/adapter/openstack/client.go
- Make sure TLS client configuration is applied
- Support new authentication types (#309).
> openstack: Fix openstack client in Plan adapter

- cmd/openstack-populator/openstack-populator.go
Support the new authentication types introduced in #309
> openstack-populator: support new authentication types

- Makefile
- hack/verify-generate.sh
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/migration.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/provider-admitter.go
- Source code verifications on CI
- Fix formatting and add missing auto-generated code
> makefile verify generated code

- Makefile
- cmd/ova-provider-server/BUILD.bazel
- cmd/ova-provider-server/ova-provider-server.go
- hack/ova-provider-server/Containerfile
Add an OVA provider server that will create for each new ova provider in the system.
It will be in charge of filling the inventory by parsing the OVA files provided by the user.
> Add OVA provider server image

- pkg/controller/plan/migration.go
r.vmMap may be stale if a previous VM has created it and the current VM didn't exist yet
Fixes #281
> Fix vmMap race

- Makefile
> Remove dependencies on unexisting targets

- cmd/ova-provider-server/ova-provider-server.go
- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/migration.go
- pkg/controller/provider/web/base/client.go
- pkg/controller/validation/policy/client.go
- pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator_test.go
- pkg/forklift-api/webhooks/util/util.go
- pkg/lib-volume-populator/populator-machinery/controller.go
- pkg/lib-volume-populator/populator-machinery/metrics_test.go
- pkg/lib/inventory/web/client.go
- tests/suit/utils/common.go
https://github.com/kubev2v/forklift/pull/484
> backport: Remove usages of ioutil

- validation/policies/io/konveyor/forklift/openstack/shared_disk.rego
- validation/policies/io/konveyor/forklift/openstack/shared_disk_test.rego
Fix the shared disk validation when the attachments array is empty.
> validation: fix openstack shared disk validation

- pkg/controller/plan/adapter/ocp/adapter.go
- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/adapter/ocp/client.go
- pkg/controller/plan/adapter/ocp/validator.go
https://github.com/kubev2v/forklift/pull/474
> backport: fix OCP remote source

- .bazelrc
virt-v2v and ovirt-populator podman build is broken without it
> use --spawn_strategy=processwrapper-sandbox

- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/kubevirt.go
https://github.com/kubev2v/forklift/pull/490
> backport: OCP: add support for secrets and configmaps 

- operator/config/manager/manager.yaml
- operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/client.go
- pkg/settings/migration.go
> ocp: make export token TTL configurable

- pkg/lib/client/openstack/client.go
https://github.com/kubev2v/forklift/pull/516
> backport: openstack: use raw format for images

- pkg/controller/plan/adapter/ova/BUILD.bazel
- pkg/controller/plan/adapter/ova/builder.go
- pkg/controller/plan/adapter/ova/ova_capacity_test.go
backport https://github.com/kubev2v/forklift/pull/497
> Backport - Fix unit size calculation for memory and disk size

- pkg/apis/forklift/v1beta1/mapping.go
https://github.com/kubev2v/forklift/pull/522
> backport: ocp: fix mapping name check

- pkg/controller/plan/adapter/openstack/BUILD.bazel
- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/ovirt/BUILD.bazel
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/util/BUILD.bazel
- pkg/controller/plan/util/utils.go
backport https://github.com/kubev2v/forklift/pull/512
> Backport - fix disk size alignment when adding FS overhead 

- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/adapter.go
- pkg/controller/plan/adapter/ocp/validator.go
DV based disks need to be considered as well
> ocp: fix storage mapping validation

- pkg/controller/plan/adapter/ocp/builder.go
https://github.com/kubev2v/forklift/pull/533
> backport: ocp: preserve boot order for disks

- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/adapter.go
- pkg/controller/plan/adapter/ocp/validator.go
https://github.com/kubev2v/forklift/pull/531
> backport: ocp: fix storage mapping validation

- virt-v2v/cold/BUILD.bazel
> Fix configuration for disabling EMS check with FIPS

- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/validator.go
pkg/controller/plan/adapter/ocp/validator.go:24:23: undefined: logging.LevelLogger
> Fix 'undefined: logging.LevelLogger'

- .github/workflows/release-branch-pull-request.yml
https://github.com/kubev2v/forklift/pull/550
> backport: Add basic go build ./... for the stable branch

- pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
backport to https://github.com/kubev2v/forklift/pull/540
> Backport block url changes for OVA providers

- pkg/controller/plan/kubevirt.go
https://github.com/kubev2v/forklift/pull/557
> backport: ocp handle wffc

- pkg/controller/provider/container/ova/model.go
backport https://github.com/kubev2v/forklift/pull/560
> backport change ova storage name to represent source provider

- pkg/controller/plan/adapter/ova/builder.go
When starting a migration each disk that needed to be migrated should be assigned with task name to follow with it progress and switch between the phases, in the current implantation all disks are assigned with the same task name (the ova/folder path) this causing the first disk to finish successfully but for all other to be stuck in an endless loop.
This fix change the task name to be unique for each disk and composes from path + disk name as it appearing in the OVF file.
> ova: fix migration with multiple disks

- cmd/ova-provider-server/BUILD.bazel
- cmd/ova-provider-server/nfs_test.go
- cmd/ova-provider-server/ova-provider-server.go
backport https://github.com/kubev2v/forklift/pull/586
> OVA: Change the scanning for ova and ovf files inside the NFS directory

- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/validator.go
- pkg/controller/plan/adapter/ocp/validator_test.go
https://github.com/kubev2v/forklift/pull/594
> backport: ocp: consider missing namespace in network name

- pkg/controller/plan/adapter/ocp/validator.go
backport of https://github.com/kubev2v/forklift/pull/605
> backport: ocp: fix network lookup

- pkg/controller/plan/adapter/ocp/BUILD.bazel
- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/adapter/ocp/util.go
- pkg/controller/plan/adapter/ocp/util_test.go
- pkg/controller/plan/adapter/ocp/validator.go
backport of https://github.com/kubev2v/forklift/pull/608
> ocp: use GetNetworkNameAndNamespace in builder.go

- pkg/controller/provider/ova-setup.go
> Backport: Fix creation of ova provider in restricted namespaces

- pkg/controller/plan/kubevirt.go
This label is used for identification of the virtual machine instance(s) that will be created from the VM, for example for load balancing, see:
https://github.com/rhpds/roadshow_ocpvirt_instructions/blob/d3b008cb5d7855b54ab912dda9f8d174dd93dcbc/workshop/content/08_migrate_vms.adoc#review-and-configure-migrated-virtual-machines
https://issues.redhat.com/browse/MTV-845
> Add 'app' label to the template of the migrated VM

- cmd/image-converter/image-converter.go
- pkg/controller/plan/adapter/openstack/builder.go
> openstack: fix conversion for block volumes

- .golangci.yml
- cmd/ova-provider-server/nfs_test.go
- cmd/ova-provider-server/ova-provider-server.go
- Remove deprecated ioutil
- Add missing error checks
- ginkgo assertion
- Add local linter config
> reduce linter noise ova

- cmd/openstack-populator/BUILD.bazel
- cmd/openstack-populator/openstack-populator.go
- cmd/openstack-populator/openstack-populator_test.go
- cmd/ovirt-populator/BUILD.bazel
- cmd/ovirt-populator/ovirt-populator.go
- go.mod
- go.sum
- operator/config/crd/bases/forklift.konveyor.io_openstackvolumepopulators.yaml
- pkg/apis/forklift/v1beta1/openstackpopulator.go
- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/util/openstack.go
- pkg/controller/plan/util/ovirt.go
- pkg/lib-volume-populator/populator-machinery/BUILD.bazel
- pkg/lib-volume-populator/populator-machinery/controller.go
- pkg/metrics/BUILD.bazel
- pkg/metrics/promethousutil.go
- vendor/k8s.io/utils/integer/integer.go
- vendor/k8s.io/utils/pointer/BUILD.bazel
- vendor/k8s.io/utils/pointer/pointer.go
- vendor/k8s.io/utils/ptr/BUILD.bazel
- vendor/k8s.io/utils/ptr/OWNERS
- vendor/k8s.io/utils/ptr/README.md
- vendor/k8s.io/utils/ptr/ptr.go
- vendor/modules.txt
- Change the scheme to match that of CDI
- Remove event reporting in favor of simple logs
- Refactor the populators a little
> Change progress monitoring

- pkg/lib/client/openstack/client.go
- Missing return
- Redundant casting
> openstack: fix linter issues

- pkg/controller/provider/container/openstack/BUILD.bazel
- pkg/controller/provider/container/openstack/model.go
> openstack: fix logging discrepancy

- pkg/controller/plan/adapter/openstack/BUILD.bazel
- pkg/controller/plan/adapter/openstack/adapter_suite_test.go
Forgotten in previous commit, the tests were added but nothing triggers them.
> Enable openstack builder tests

- operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
- pkg/settings/settings.go
And also rename the env var OpenShift to OPENSHIFT
> Make the value of OpenShift var a string

- cmd/image-converter/image-converter.go
- pkg/controller/plan/adapter/BUILD.bazel
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/converter.go
- pkg/controller/plan/adapter/converter_test.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/kubevirt.go
- Fix NPEs
- Fix permission issue
- Switch to DVs to support WFFC
- Fix inventory race
> openstack: use DataVolume to support WFFC

- cmd/image-converter/image-converter.go
- pkg/controller/plan/adapter/BUILD.bazel
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/converter.go
- pkg/controller/plan/adapter/converter_test.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/kubevirt.go
> Backport: openstack: use DataVolume to support WFFC 

- WORKSPACE
> bump OPA version to get security fixes

- pkg/controller/provider/container/ova/watch.go
- pkg/controller/provider/web/ova/vm.go
- pkg/controller/provider/web/ova/workload.go
- validation/policies/io/konveyor/forklift/ova/debug.rego
Fix the workload construction for passing VM information to validations.
> OVA: Fix workload construction for validations and match vars names.

- cmd/ova-provider-server/ova-provider-server.go
> backport: OVA: map vm configuration from extraConfig in ovf file

- pkg/controller/provider/container/ova/watch.go
- pkg/controller/provider/web/ova/vm.go
- pkg/controller/provider/web/ova/workload.go
- validation/policies/io/konveyor/forklift/ova/debug.rego
> backport: OVA: Fix workload construction for validations and match vars names.

- pkg/controller/plan/BUILD.bazel
- pkg/controller/plan/adapter/converter.go
- pkg/controller/plan/adapter/openstack/BUILD.bazel
- pkg/controller/plan/adapter/openstack/adapter_suite_test.go
- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/openstack/destinationclient.go
- pkg/controller/plan/adapter/openstack/destionationclient_test.go
- pkg/controller/plan/adapter/ovirt/BUILD.bazel
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/ovirt/destinationclient.go
- pkg/controller/plan/adapter/ovirt/destinationclient_test.go
- pkg/controller/plan/adapter/ovirt/ovirt_suite_test.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/kubevirt_test.go
> use generated name for PVCs and populator CRs

- pkg/controller/plan/adapter/openstack/builder.go
Currently, because bootOrder was declared outside the loop, it would keep the same value from a previous iteration, being set on a disk that shouldn't be set.
> openstack: fix bootOrder setting

- pkg/controller/plan/adapter/openstack/client.go
The status of the snapshot might not be synced in the inventory. Check the status is up-to-date before proceeding
> openstack: attempt to fix race

- pkg/controller/plan/adapter/openstack/client.go
The status of the snapshot might not be synced in the inventory. Check the status is up-to-date before proceeding
> backport: openstack: attempt to fix race

- pkg/controller/plan/validation.go
https://github.com/kubev2v/forklift/pull/864
> backport: ocp: do not return error when setting condition

- pkg/controller/plan/migration.go
When MTV is not installed on the remote OCP cluster and we try to
cleanup we won't succeed. This patch won't try to remove or edit forklift
entities, as if MTV doesn't exist there, it will fail - causing the plan
to fail.
> Don't cleanup forklift entities on remote cluster 

- .github/workflows/pull-request.yml
- .github/workflows/release-branch-pull-request.yml
- WORKSPACE
- virt-v2v/cold/WORKSPACE
- virt-v2v/warm/WORKSPACE
> Bump Go to 1.21

- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- validation/policies/io/konveyor/forklift/vmware/disk_mode.rego
- validation/policies/io/konveyor/forklift/vmware/disk_mode_test.rego
> vSphere: warn when independent disks are detected

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/validator.go
- pkg/controller/plan/adapter/openstack/validator.go
- pkg/controller/plan/adapter/ova/validator.go
- pkg/controller/plan/adapter/ovirt/validator.go
- pkg/controller/plan/adapter/vsphere/BUILD.bazel
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/builder_test.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/adapter/vsphere/validator_test.go
- pkg/controller/plan/adapter/vsphere/vsphere_suite_test.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/validation.go
- pkg/controller/provider/container/vsphere/collector.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
- pkg/lib/condition/condition.go
- virt-v2v/cold/cold_test.go
- virt-v2v/cold/entrypoint.go
This patch will get the static IPs configurations from the vSphere provider to each guest and will propogate it to virt-v2v to set it up while converting the VM.
> Map vSphere static IPs

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/validator.go
- pkg/controller/plan/adapter/openstack/validator.go
- pkg/controller/plan/adapter/ova/validator.go
- pkg/controller/plan/adapter/ovirt/validator.go
- pkg/controller/plan/adapter/vsphere/BUILD.bazel
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/builder_test.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/adapter/vsphere/validator_test.go
- pkg/controller/plan/adapter/vsphere/vsphere_suite_test.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/validation.go
- pkg/controller/provider/container/vsphere/collector.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
- pkg/lib/condition/condition.go
- virt-v2v/cold/cold_test.go
- virt-v2v/cold/entrypoint.go
This patch will get the static IPs configurations from the vSphere provider to each guest and will propogate it to virt-v2v to set it up while converting the VM.
Backport #852
> Map vSphere static IPs (backport)

- virt-v2v/cold/entrypoint.go
Remove synchronization for the firmware detection scanner from the entrypoint. The firmware detection happens in an early stage of the conversion, and we are writing it to the VM configuration file and only after that starting the server. 
In that case, we can assume it will be retrieved by the time the command ends.
> OVA: remove synchronization for firmware detection scanner

- WORKSPACE
- operator/BUILD.bazel
- operator/config/default/manager_auth_proxy_patch.yaml
- operator/config/scorecard/patches/basic.config.yaml
- operator/config/scorecard/patches/olm.config.yaml
> bump sdk (backport)

- virt-v2v/warm/BUILD.bazel
Follow up on commit 8452cb9 (PR #939).
> Follow up stream8 fix

- pkg/monitoring/metrics/forklift-controller/metrics.go
- pkg/monitoring/metrics/forklift-controller/migration_metrics.go
backport https://github.com/kubev2v/forklift/pull/962
> Change the migration metrics type to counter

- pkg/monitoring/metrics/forklift-controller/metrics.go
Following @simonpasquier https://github.com/kubev2v/forklift/pull/916 review.
> Fix metrics description

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/builder_test.go
- pkg/controller/provider/container/vsphere/collector.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
- pkg/controller/provider/web/vsphere/vm.go
Collect the prefix length from vSphere and send it to virt-v2v to set it on destination.
> Add subnet mask, gateway and DNS to static IP preservation

- virt-v2v/cold/entrypoint.go
Ref: 
https://issues.redhat.com/browse/MTV-595
Addressing:
https://github.com/kubev2v/forklift/pull/984#pullrequestreview-2249952852
**Issue:**
We run the virt-v2v customization step in cases we know it is not needed
**Fix:**
Add checks, and exit the customization script when we identify that it's not neededL
- We can't parse .xml ( or .yaml in future ) virt-v2v output
- We don't recognize the OS name
- We did not find any disks to customize
> [MTV-595] Add checks before running virt-v2v customize step

- virt-v2v/cold/scripts/rhel/run/network_config_util.sh
- virt-v2v/cold/scripts/rhel/run/network_config_util_test
Ref: https://issues.redhat.com/browse/MTV-595
Followup to comments in https://github.com/kubev2v/forklift/pull/983
https://github.com/kubev2v/forklift/pull/983#discussion_r1732774288 - refactor network script
> [MTV-595]  Refactor network config bash script

- virt-v2v/cold/scripts/rhel/run/network_config_util.sh
- virt-v2v/cold/scripts/rhel/run/network_config_util_test
> Backport | Dashify network utils script

- virt-v2v/cold/scripts/rhel/run/network_config_util.sh
- virt-v2v/cold/scripts/rhel/run/network_config_util_test
> Backport | Allow more text after ip

- virt-v2v/cold/scripts/rhel/run/network_config_util.sh
- virt-v2v/cold/scripts/rhel/run/network_config_util_test
Backport of https://github.com/kubev2v/forklift/pull/1010
> Backport | Remove double quates from network config files

- virt-v2v/cold/scripts/rhel/run/network_config_util.sh
- virt-v2v/cold/scripts/rhel/run/network_config_util_test
> Backport | Redirect RHEL run network config utils sh script errors to stderr

- build/forklift-operator/Containerfile
Taking the Dockerfile from downstream to build image in upstream (in the meantime just commenting the not needed things)
> chore(KONFLUX-4255): Onboard mtv-operator

- pkg/controller/plan/migration.go
Related to: https://github.com/kubev2v/forklift/pull/1085
Fixes: https://issues.redhat.com/browse/MTV-1569
> MTV-1569 | Migration code cleanup

- virt-v2v/pkg/utils/command.go
Ref: https://issues.redhat.com/browse/MTV-1555
> MTV-1555 | Fix the v2v newname variable name

- virt-v2v/pkg/utils/command.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1098
> Backport for the 2.7.2 release

- docs/enhancements/template.md
For the upcoming larger changes inside the forklift either the design changes or larger enhancements, we will require the document describing the current situation and why to implement the changes.
Original template https://github.com/konveyor/enhancements/blob/master/guidelines/enhancement_template.md
> Add enhancements template.md for the design docs

- .tekton/forklift-api-pull-request.yaml
- .tekton/forklift-api-push.yaml
- .tekton/forklift-controller-pull-request.yaml
- .tekton/forklift-controller-push.yaml
- .tekton/forklift-operator-bundle-pull-request.yaml
- .tekton/forklift-operator-bundle-push.yaml
- .tekton/forklift-operator-pull-request.yaml
- .tekton/forklift-operator-push.yaml
- .tekton/openstack-populator-pull-request.yaml
- .tekton/openstack-populator-push.yaml
- .tekton/ova-provider-server-pull-request.yaml
- .tekton/ova-provider-server-push.yaml
- .tekton/ovirt-populator-pull-request.yaml
- .tekton/ovirt-populator-push.yaml
- .tekton/populator-controller-pull-request.yaml
- .tekton/populator-controller-push.yaml
- .tekton/validation-pull-request.yaml
- .tekton/validation-push.yaml
- .tekton/virt-v2v-pull-request.yaml
- .tekton/virt-v2v-push.yaml
- build/forklift-operator-bundle/Containerfile
- build/virt-v2v/Containerfile
- hack/multi-version-pipeline-fixes.py
- operator/config/manifests/bases/forklift-operator.clusterserviceversion.yaml
Change all pipelines to follow release-2.7 and add python script in `hack` folder to make this work easy for next versions needed to be supported
> change pipelines to follow release-2.7

- pkg/controller/plan/migration.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1189
> Backport to release-2.7

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/client.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/adapter/ova/client.go
- pkg/controller/plan/adapter/ovirt/client.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/migration.go
Reverts kubev2v/forklift#1193
as this causes further issues https://issues.redhat.com/browse/MTV-1681
> Revert "MTV-1656 | Disable snapshot consolidation"

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/client.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/adapter/ova/client.go
- pkg/controller/plan/adapter/ovirt/client.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/migration.go
Reverts kubev2v/forklift#1194
as this causes further issues https://issues.redhat.com/browse/MTV-1681
> Revert "Backport to release-2.7"

- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/ova/builder.go
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/provider/ova-setup.go
- pkg/forklift-api/webhooks/mutating-webhook/mutators/secret-mutator.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/secret-admitter.go
- virt-v2v/cmd/entrypoint.go
Backport to 2.7.8:
- https://github.com/kubev2v/forklift/pull/1295
- https://github.com/kubev2v/forklift/pull/1293
- https://github.com/kubev2v/forklift/pull/1291
- https://github.com/kubev2v/forklift/pull/1289
- https://github.com/kubev2v/forklift/pull/1287
> Backport to 2.7.8

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/scheduler/vsphere/scheduler.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1318
- https://github.com/kubev2v/forklift/pull/1325
- https://github.com/kubev2v/forklift/pull/1333
> Backport 2.7.10

- operator/roles/forkliftcontroller/templates/controller/deployment-controller.yml.j2
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/adapter/vsphere/host.go
- pkg/controller/provider/container/vsphere/collector.go
> Revert "MTV-1571 | Allow to customize the TLS config for the govmomi client"

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/client.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/scheduler/vsphere/scheduler.go
Revert of https://github.com/kubev2v/forklift/pull/1318 for main
> Revert shared disks in main

- pkg/controller/plan/adapter/vsphere/builder.go
Issue:
The controller is crashing with panic.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d2ac24]
goroutine 377 [running]:
github.com/konveyor/forklift-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x2c43d60?, 0x542d320?})
GOROOT/src/runtime/panic.go:914 +0x21f
github.com/konveyor/forklift-controller/pkg/controller/plan/adapter/vsphere.(*Builder).mapDisks(0xc00063c1c8, 0x2f47700?, {{0xc0005f5187, 0x5}, {0xc0005f51a0, 0xf}, {0x0, 0x0}, {0x0, 0x0}}, ...) …
```
> MTV-2164 | Remove snapshot suffix when user creates snapshot in middle of migration

- pkg/controller/plan/adapter/vsphere/builder.go
Backport of https://github.com/kubev2v/forklift/pull/1405 to 2.8
> Backport 2.8 | MTV-2164 | Remove snapshot suffix when user creates snapshot in middle of migration

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/utils.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/util/utils.go
Backport to release-2.8 of:
- https://github.com/kubev2v/forklift/pull/1419
- https://github.com/kubev2v/forklift/pull/1420
> Backports to release-2.8

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/utils.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/util/utils.go
Backport to release-2.7 of:
- https://github.com/kubev2v/forklift/pull/1419
- https://github.com/kubev2v/forklift/pull/1420
> Backports to release-2.7

- pkg/controller/plan/migration.go
Backport of: https://github.com/kubev2v/forklift/pull/1423
> Backport 2.8 | MTV-1796 | Cancel VM only once

- pkg/controller/provider/validation.go
Issue: When user specified they want to skip ceritificate verification we want to just inform the customer about failed connection and not about certificate. The reason behind this is that the GetTlsCertificate is our first attempt to connect to the provider and when connection fails, the customer will still get the certificate error even when they don't care about certificates.
Fix: 'TLS certificate cannot be retrieved' message is ignored when skipVerify flag is set to true and connection fails.
Ref: https://issues.redhat.com/browse/MTV-2146
> MTV-2146 | Ignore TLS Cert msg when skipCertVerify

- pkg/controller/plan/adapter/vsphere/utils.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/validation.go
- pkg/lib/condition/condition.go
Backport of https://github.com/kubev2v/forklift/pull/1436 to release-2.8
> Backport 2.8 | Fix shared disks validations

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/forklift-api/webhooks/validating-webhook/admitters/plan-admitter.go
Backport of https://github.com/kubev2v/forklift/pull/1435 to release-2.8
> Backport 2.8 | MTV-2199 | Deprecate plan.spec.DiskBus parameter

- pkg/controller/plan/scheduler/ocp/scheduler.go
- pkg/controller/plan/scheduler/openstack/scheduler.go
- pkg/controller/plan/scheduler/ova/scheduler.go
- pkg/controller/plan/scheduler/ovirt/scheduler.go
Follow up to https://github.com/kubev2v/forklift/pull/1465 that fixes the issue for the other providers.
> Ignore canceled VMs when scheduling

- pkg/controller/plan/adapter/vsphere/builder.go
Issue:
Cold migration failed when esxi host name can’t be resolved to an ip address
Fix:
Retrieve the corresponding ip address and use it by default, fallback will be host name. That way we avoid DNS resolving issue on virt-v2v
Ref: https://issues.redhat.com/browse/MTV-2153
> MTV-2153 | Cold migration failed when esxi host name can’t be resolved to an ip address

- cmd/virt-v2v/entrypoint.go
- operator/config/crd/bases/forklift.konveyor.io_networkmaps.yaml
- operator/roles/forkliftcontroller/templates/controller/controller-scc.yml.j2
- pkg/apis/forklift/v1beta1/mapping.go
- pkg/controller/map/network/validation.go
- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/adapter/ocp/client.go
- pkg/controller/plan/adapter/openstack/builder.go
- pkg/controller/plan/adapter/ova/builder.go
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/migration.go
- pkg/controller/plan/scheduler/vsphere/scheduler.go
- pkg/controller/plan/validation.go
- pkg/controller/plan/validation_test.go
- pkg/controller/plan/vm_name_handler.go
- pkg/controller/plan/vm_name_handler_test.go
- validation/policies/io/konveyor/forklift/openstack/name.rego
- validation/policies/io/konveyor/forklift/ova/name.rego
- validation/policies/io/konveyor/forklift/ovirt/name.rego
- validation/policies/io/konveyor/forklift/vmware/name.rego
Backport of commits to the release-2.8 branch:
- https://github.com/kubev2v/forklift/pull/1482
- https://github.com/kubev2v/forklift/pull/1469
- https://github.com/kubev2v/forklift/pull/1465
- https://github.com/kubev2v/forklift/pull/1460
- https://github.com/kubev2v/forklift/pull/1445
- https://github.com/kubev2v/forklift/pull/1433
- https://github.com/kubev2v/forklift/pull/1408
- https://github.com/kubev2v/forklift/pull/1383
- https://github.com/kubev2v/forklift/pull/1505
- https://github.com/kubev2v/forklift/pull/1489
- https://github.com/kubev2v/forklift/pull/1511
- https://github.com/kubev2v/forklift/pull/1512
- https://github.com/kubev2v/forklift/pull/1505
> Backport 2.8.1

- .gitignore
- vendor/github.com/nxadm/tail/Dockerfile
- vendor/github.com/pelletier/go-toml/v2/Dockerfile
- vendor/github.com/vmware/govmomi/Dockerfile.govc
- vendor/github.com/vmware/govmomi/Dockerfile.vcsim
Backport of https://github.com/kubev2v/forklift/pull/1519 to release-2.8
> Backport vendor fix for build

- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/vsphere/builder.go
Backport of:
- https://github.com/kubev2v/forklift/pull/1526
- https://github.com/kubev2v/forklift/pull/1501
> Backport 2349 2303 to 2.8.2

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/builder_test.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
Backport of: https://github.com/kubev2v/forklift/pull/1596 to release-2.8
> Backport #1596 to release-2.8

- pkg/controller/plan/adapter/ocp/builder.go
Ref: https://issues.redhat.com/browse/MTV-2387
Support ignoring networks in OCP
Issue:
We do not support "Ignored" as a network target from OCP sources.
Fix:
Add support for "Ignored" as a network target from OCP sources.
Screenshots:
Network map for OCP to OCP migration:
source VM:
target VM:
> MTV-2387 | Support ignoring networks in OCP

- .github/workflows/build-push-images.yml
Add vsphere-xcopy-volume-populator github action build
> Add vsphere-xcopy-volume-populator github action build

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/validation.go
Backport 2.8.3:
- https://github.com/kubev2v/forklift/pull/1580
- https://github.com/kubev2v/forklift/pull/1612
- https://github.com/kubev2v/forklift/pull/1480
> Backport 2.8.3

- operator/roles/forkliftcontroller/defaults/main.yml
- operator/roles/forkliftcontroller/templates/populator/deployment-populator-controller.yml.j2
Backport of https://github.com/kubev2v/forklift/pull/1635
> Add populator_vsphere_xcopy_volume_image_fqin to the operator [2.8.3]

- .github/workflows/build-push-images-hal.yml
- .gitignore
- cmd/vsphere-xcopy-volume-populator/internal/ontap/ontap.go
- cmd/vsphere-xcopy-volume-populator/internal/populator/mocks/storage_mock_client.go
- cmd/vsphere-xcopy-volume-populator/internal/populator/populate.go
- cmd/vsphere-xcopy-volume-populator/internal/populator/remote_esxcli.go
- cmd/vsphere-xcopy-volume-populator/internal/populator/storage.go
- cmd/vsphere-xcopy-volume-populator/internal/primera3par/clonner.go
- cmd/vsphere-xcopy-volume-populator/internal/primera3par/par3_test.go
- cmd/vsphere-xcopy-volume-populator/internal/vantara/vantara-api.go
- cmd/vsphere-xcopy-volume-populator/internal/vantara/vantara-hgid.go
- cmd/vsphere-xcopy-volume-populator/internal/vantara/vantara-storage.go
- cmd/vsphere-xcopy-volume-populator/internal/vantara/vantara.go
- cmd/vsphere-xcopy-volume-populator/vsphere-xcopy-volume-populator.go
Hitachi Vantara Storage API support for storage offload volume populator
> Hitachi API for vsphere-xcopy-volume-populator from tatsumir

- pkg/controller/plan/adapter/vsphere/builder.go
This reverts commit f1df4c94c7ae265e7598892f7cbef571e9a81d06.
> [2.8] Revert "MTV-2025 | MTV-1673 | NICs mapping is unordered" 

- build/forklift-operator-index/Containerfile
Backport of https://github.com/kubev2v/forklift/pull/1666
> Fix failing forklift index build (#1666)

- pkg/controller/plan/adapter/base/doc.go
- pkg/controller/plan/adapter/ocp/validator.go
- pkg/controller/plan/adapter/openstack/validator.go
- pkg/controller/plan/adapter/ova/validator.go
- pkg/controller/plan/adapter/ovirt/validator.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/validation.go
- pkg/controller/provider/container/vsphere/model.go
- pkg/controller/provider/model/vsphere/model.go
This reverts commit 40b20cbb0eac608a9faabec57a632483263ce437.
> Revert "MTV-2025 | NICs mapping is unordered - validation"

- pkg/controller/plan/adapter/vsphere/builder.go
This reverts commit 0242c871c7c446ca1e401981223eccf107c51b87.
> Revert "MTV-2025 | MTV-1673 | NICs mapping is unordered"

- .tekton/forklift-api-dev-preview-pull-request.yaml
- .tekton/forklift-api-dev-preview-push.yaml
- .tekton/forklift-controller-dev-preview-pull-request.yaml
- .tekton/forklift-controller-dev-preview-push.yaml
- .tekton/forklift-operator-bundle-dev-preview-pull-request.yaml
- .tekton/forklift-operator-bundle-dev-preview-push.yaml
- .tekton/forklift-operator-dev-preview-pull-request.yaml
- .tekton/forklift-operator-dev-preview-push.yaml
- .tekton/openstack-populator-dev-preview-pull-request.yaml
- .tekton/openstack-populator-dev-preview-push.yaml
- .tekton/ova-provider-server-dev-preview-pull-request.yaml
- .tekton/ova-provider-server-dev-preview-push.yaml
- .tekton/ovirt-populator-dev-preview-pull-request.yaml
- .tekton/ovirt-populator-dev-preview-push.yaml
- .tekton/populator-controller-dev-preview-pull-request.yaml
- .tekton/populator-controller-dev-preview-push.yaml
- .tekton/validation-dev-preview-pull-request.yaml
- .tekton/validation-dev-preview-push.yaml
- .tekton/virt-v2v-dev-preview-pull-request.yaml
- .tekton/virt-v2v-dev-preview-push.yaml
- .tekton/vsphere-xcopy-volume-populator-dev-preview-pull-request.yaml
- .tekton/vsphere-xcopy-volume-populator-dev-preview-push.yaml
We also need source images so enable them.
Ref: https://issues.redhat.com/browse/MTV-2271
> MTV-2271 | Enable source build in all pipelines

- cmd/vsphere-xcopy-volume-populator/Makefile
- cmd/vsphere-xcopy-volume-populator/internal/ontap/ontap.go
- cmd/vsphere-xcopy-volume-populator/internal/populator/remote_esxcli.go
- cmd/vsphere-xcopy-volume-populator/internal/primera3par/clonner.go
- cmd/vsphere-xcopy-volume-populator/internal/primera3par/par3client.go
- cmd/vsphere-xcopy-volume-populator/internal/primera3par/par3clientmock.go
Related to: https://issues.redhat.com/browse/ECOPROJECT-2822
> Support HP and Ontap Fiber Channel

- operator/config/crd/bases/forklift.konveyor.io_vspherexcopyvolumepopulators.yaml
- pkg/apis/forklift/v1beta1/mapping.go
- pkg/apis/forklift/v1beta1/vsphere_xcopy_volumepopulator.go
https://issues.redhat.com/browse/ECOPROJECT-2874
> xcopy-populator: Add missing enum values

- pkg/controller/provider/container/doc.go
- pkg/controller/provider/container/ocp/collection.go
- pkg/controller/provider/container/ocp/collector.go
- pkg/controller/provider/web/base/auth.go
- pkg/controller/provider/web/base/auth_test.go
- pkg/controller/provider/web/base/handler.go
- pkg/controller/provider/web/ocp/base.go
- pkg/controller/provider/web/ocp/clusterinstancetype.go
- pkg/controller/provider/web/ocp/doc.go
- pkg/controller/provider/web/ocp/instancetype.go
- pkg/controller/provider/web/ocp/namespace.go
- pkg/controller/provider/web/ocp/netattachdefinition.go
- pkg/controller/provider/web/ocp/provider.go
- pkg/controller/provider/web/ocp/storageclass.go
- pkg/controller/provider/web/ocp/tree.go
- pkg/controller/provider/web/ocp/vm.go
- pkg/controller/provider/web/provider.go
- pkg/lib/inventory/container/ocp/collection.go
- pkg/lib/inventory/container/ocp/collector.go
> Revert "MTV-1745"

- .github/workflows/pull-request.yml
Disable ova and vsphere CI as people accidentally overlook failing CI
> Disable ova and vsphere CI as people accidentally overlook failing CI

- .github/CODEOWNERS
> Add additional codeowners

- .github/workflows/build-push-images.yml
- build/virt-v2v/Containerfile-upstream-fssupport
Bump to centos 10 stream and add kmod-btrfs
> Bump to centos 10 stream and add kmod-btrfs

- docs/enhancements/vsphere-xcopy-volume-populator.md
https://issues.redhat.com/browse/ECOPROJECT-2932
> xcopy-populator: Enhancement document for vphere-xcopy-volume-populator

- cmd/vsphere-xcopy-volume-populator/README.md
https://issues.redhat.com/browse/ECOPROJECT-2955
> xcopy-populator: Add setup instructions to the README.md

- build/forklift-operator-bundle/Containerfile-downstream
Operator bundle had placeholder images instead of a real ones. Modify the images to dev-preview prod images.
> Use proper images for bundle

- pkg/controller/plan/adapter/ocp/builder.go
Issue:
When migrating the VM between two Kubernetes clusters, the disks are not sorted in the original order.
This causes the devices to be named differently.
Fix:
Right now, the disks are created from a map which does not have order.
We need to switch to the original disk order. 
Ref: https://issues.redhat.com/browse/MTV-2367
> MTV-2367 | Keep the disk order between Kubernetes clusters

- build/virt-v2v/Containerfile-upstream-fssupport
Fix Containerfile-upstream-fssupport kojihub paths
> Fix Containerfile-upstream-fssupport kojihub paths

- .konflux/forklift-api/redhat.repo
- .konflux/forklift-controller/redhat.repo
- .konflux/openstack-populator/redhat.repo
- .konflux/ova-provider-server/redhat.repo
- .konflux/populator-controller/redhat.repo
- .konflux/virt-v2v/redhat.repo
- .konflux/virt-v2v/rpms.lock.yaml
- build/forklift-api/Containerfile
- build/forklift-api/Containerfile-downstream
- build/forklift-controller/Containerfile
- build/forklift-controller/Containerfile-downstream
- build/forklift-operator-index/Containerfile
- build/openstack-populator/Containerfile
- build/openstack-populator/Containerfile-downstream
- build/ova-provider-server/Containerfile
- build/ova-provider-server/Containerfile-downstream
- build/populator-controller/Containerfile
- build/populator-controller/Containerfile-downstream
- build/validation/Containerfile
- build/validation/Containerfile-downstream
- build/virt-v2v/Containerfile
- build/virt-v2v/Containerfile-downstream
- build/virt-v2v/Containerfile-upstream
Bump to latest UBI version.
Ref https://issues.redhat.com/browse/MTV-2464
> MTV-2464 | Bump to UBI 9.6

- build/forklift-operator-bundle/Containerfile
Issue: bundle generation failed because PROJECT got updated to contain variable based on stream.
Fix: resolve the variable for upstream.
> Fix upstream bundle build

- operator/.kustomized_manifests
- operator/config/crd/bases/forklift.konveyor.io_storagemaps.yaml
- pkg/apis/forklift/v1beta1/mapping.go
Add primera3par to StorageVendorProduct enum
> Add primera3par to StorageVendorProduct enum

- pkg/controller/plan/adapter/vsphere/builder.go
> xcopy-populator: make sure accessMode has a default RWX

- pkg/controller/plan/adapter/ocp/builder.go
- pkg/controller/plan/adapter/openstack/client.go
- pkg/controller/plan/adapter/ovirt/builder.go
- pkg/controller/plan/adapter/ovirt/client.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/validation.go
- pkg/controller/plan/validation_test.go
- pkg/forklift-api/webhooks/mutating-webhook/mutators/plan-mutator.go
- **plan validator: use unused conditions**
- **Use unused hook validation conditions**
- **Remove duplicate nil check**
- **Remove duplicate module imports**
- **Remove unused pvcMap argument in ocp Builder**
- **Fix some impossible nil checks**
> [chore] Fix a bunch of lint warnings

- build/virt-v2v/Containerfile-downstream-fssupport
Choose consistent set of packages based on QE feedback.
Thanks: Tingting Zheng
> build: virt-v2v: Select tested set of packages

- .konflux/forklift-controller/redhat.repo
- .konflux/forklift-controller/rpms.in.yaml
- .konflux/forklift-controller/rpms.lock.yaml
- build/forklift-controller/Containerfile-downstream
These packages are needed by: https://github.com/kubev2v/forklift/pull/2223
> Add libvirt-devel and libvirt-libs to controller

- operator/.downstream_manifests
- operator/.kustomized_manifests
- operator/.upstream_manifests
- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/adapter/ova/validator.go
- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/controller/plan/adapter/vsphere/utils.go
- pkg/controller/plan/adapter/vsphere/validator.go
- pkg/controller/plan/adapter/vsphere/validator_test.go
- pkg/virt-v2v/customize/scripts/windows/9999-remove_duplicate_persistent_routes.ps1
- validation/policies/io/konveyor/forklift/vmware/power_state.rego
- validation/policies/io/konveyor/forklift/vmware/power_state_test.rego
Backport of following patches to 2.9.1:
- https://github.com/kubev2v/forklift/pull/2261
- https://github.com/kubev2v/forklift/pull/2102
- https://github.com/kubev2v/forklift/pull/2170
- https://github.com/kubev2v/forklift/pull/2176
> Backport 2.9.1

- pkg/controller/plan/adapter/vsphere/builder.go
- pkg/virt-v2v/customize/scripts/windows/9999-remove_duplicate_persistent_routes.ps1
> Backport 2.9 [2394]

- .konflux/virt-v2v/appliance/redhat.repo
- .konflux/virt-v2v/appliance/rpms.lock.yaml
- .konflux/virt-v2v/runtime/redhat.repo
- .konflux/virt-v2v/runtime/rpms.lock.yaml
- build/release.conf
Issue: new version guestfs-tools pkg was released with the required fix.
Fix: Update the pkg and bump the z-stream version of MTV
> RHEL-109544 | Update guestfs-tools and Z stream version

- cmd/vsphere-xcopy-volume-populator/README.md
Update default value for STORAGE_* secret keys
> chore: Update storage-offload README.md

- operator/.downstream_manifests
- operator/.kustomized_manifests
- operator/.upstream_manifests
- operator/config/crd/bases/forklift.konveyor.io_plans.yaml
- pkg/apis/forklift/v1beta1/plan.go
- pkg/controller/plan/context/migration.go
- pkg/controller/plan/controller.go
- pkg/controller/plan/kubevirt.go
- pkg/controller/plan/kubevirt_test.go
- pkg/controller/plan/migrator/base/doc.go
- pkg/controller/plan/migrator/base/migrator.go
- pkg/controller/plan/validation.go
Backport of https://github.com/kubev2v/forklift/pull/2448
> Backport 2.9 | MTV-3141 | Add only conversion mode
